# This is the cluster wide security-profiles-operator deployment, which listens for
# configMaps on all namespaces
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../cluster

patchesStrategicMerge:
  - deployment.yaml
  - no_certificate.yaml
  - svc_gen_cert.yaml
patchesJson6902:
  - target:
      version: v1
      kind: MutatingWebhookConfiguration
      name: spo-mutating-webhook-configuration
    path: mutatingwebhookconfig.yaml
