---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: security-profiles-operator
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhook-server-cert
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: security-profiles-operator
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: metrics-server-cert
