---
apiVersion: v1
kind: Service
metadata:
  name: profilebinding-webhook-service
  namespace: security-profiles-operator
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    name: security-profiles-operator-webhook
