/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by counterfeiter. DO NOT EDIT.
package profilerecorderfakes

import (
	"context"
	"sync"

	"google.golang.org/grpc"
	api_bpfrecorder "sigs.k8s.io/security-profiles-operator/api/grpc/bpfrecorder"
)

type FakeBpfRecorderImpl struct {
	ApparmorForProfileStub        func(context.Context, api_bpfrecorder.BpfRecorderClient, *api_bpfrecorder.ProfileRequest) (*api_bpfrecorder.ApparmorResponse, error)
	apparmorForProfileMutex       sync.RWMutex
	apparmorForProfileArgsForCall []struct {
		arg1 context.Context
		arg2 api_bpfrecorder.BpfRecorderClient
		arg3 *api_bpfrecorder.ProfileRequest
	}
	apparmorForProfileReturns struct {
		result1 *api_bpfrecorder.ApparmorResponse
		result2 error
	}
	apparmorForProfileReturnsOnCall map[int]struct {
		result1 *api_bpfrecorder.ApparmorResponse
		result2 error
	}
	DialBpfRecorderStub        func() (*grpc.ClientConn, error)
	dialBpfRecorderMutex       sync.RWMutex
	dialBpfRecorderArgsForCall []struct {
	}
	dialBpfRecorderReturns struct {
		result1 *grpc.ClientConn
		result2 error
	}
	dialBpfRecorderReturnsOnCall map[int]struct {
		result1 *grpc.ClientConn
		result2 error
	}
	ResetApparmorForProfileStub        func(context.Context, api_bpfrecorder.BpfRecorderClient, *api_bpfrecorder.ProfileRequest) error
	resetApparmorForProfileMutex       sync.RWMutex
	resetApparmorForProfileArgsForCall []struct {
		arg1 context.Context
		arg2 api_bpfrecorder.BpfRecorderClient
		arg3 *api_bpfrecorder.ProfileRequest
	}
	resetApparmorForProfileReturns struct {
		result1 error
	}
	resetApparmorForProfileReturnsOnCall map[int]struct {
		result1 error
	}
	ResetSyscallsForProfileStub        func(context.Context, api_bpfrecorder.BpfRecorderClient, *api_bpfrecorder.ProfileRequest) error
	resetSyscallsForProfileMutex       sync.RWMutex
	resetSyscallsForProfileArgsForCall []struct {
		arg1 context.Context
		arg2 api_bpfrecorder.BpfRecorderClient
		arg3 *api_bpfrecorder.ProfileRequest
	}
	resetSyscallsForProfileReturns struct {
		result1 error
	}
	resetSyscallsForProfileReturnsOnCall map[int]struct {
		result1 error
	}
	StartBpfRecorderStub        func(context.Context, api_bpfrecorder.BpfRecorderClient) error
	startBpfRecorderMutex       sync.RWMutex
	startBpfRecorderArgsForCall []struct {
		arg1 context.Context
		arg2 api_bpfrecorder.BpfRecorderClient
	}
	startBpfRecorderReturns struct {
		result1 error
	}
	startBpfRecorderReturnsOnCall map[int]struct {
		result1 error
	}
	StopBpfRecorderStub        func(context.Context, api_bpfrecorder.BpfRecorderClient) error
	stopBpfRecorderMutex       sync.RWMutex
	stopBpfRecorderArgsForCall []struct {
		arg1 context.Context
		arg2 api_bpfrecorder.BpfRecorderClient
	}
	stopBpfRecorderReturns struct {
		result1 error
	}
	stopBpfRecorderReturnsOnCall map[int]struct {
		result1 error
	}
	SyscallsForProfileStub        func(context.Context, api_bpfrecorder.BpfRecorderClient, *api_bpfrecorder.ProfileRequest) (*api_bpfrecorder.SyscallsResponse, error)
	syscallsForProfileMutex       sync.RWMutex
	syscallsForProfileArgsForCall []struct {
		arg1 context.Context
		arg2 api_bpfrecorder.BpfRecorderClient
		arg3 *api_bpfrecorder.ProfileRequest
	}
	syscallsForProfileReturns struct {
		result1 *api_bpfrecorder.SyscallsResponse
		result2 error
	}
	syscallsForProfileReturnsOnCall map[int]struct {
		result1 *api_bpfrecorder.SyscallsResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBpfRecorderImpl) ApparmorForProfile(arg1 context.Context, arg2 api_bpfrecorder.BpfRecorderClient, arg3 *api_bpfrecorder.ProfileRequest) (*api_bpfrecorder.ApparmorResponse, error) {
	fake.apparmorForProfileMutex.Lock()
	ret, specificReturn := fake.apparmorForProfileReturnsOnCall[len(fake.apparmorForProfileArgsForCall)]
	fake.apparmorForProfileArgsForCall = append(fake.apparmorForProfileArgsForCall, struct {
		arg1 context.Context
		arg2 api_bpfrecorder.BpfRecorderClient
		arg3 *api_bpfrecorder.ProfileRequest
	}{arg1, arg2, arg3})
	stub := fake.ApparmorForProfileStub
	fakeReturns := fake.apparmorForProfileReturns
	fake.recordInvocation("ApparmorForProfile", []interface{}{arg1, arg2, arg3})
	fake.apparmorForProfileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBpfRecorderImpl) ApparmorForProfileCallCount() int {
	fake.apparmorForProfileMutex.RLock()
	defer fake.apparmorForProfileMutex.RUnlock()
	return len(fake.apparmorForProfileArgsForCall)
}

func (fake *FakeBpfRecorderImpl) ApparmorForProfileCalls(stub func(context.Context, api_bpfrecorder.BpfRecorderClient, *api_bpfrecorder.ProfileRequest) (*api_bpfrecorder.ApparmorResponse, error)) {
	fake.apparmorForProfileMutex.Lock()
	defer fake.apparmorForProfileMutex.Unlock()
	fake.ApparmorForProfileStub = stub
}

func (fake *FakeBpfRecorderImpl) ApparmorForProfileArgsForCall(i int) (context.Context, api_bpfrecorder.BpfRecorderClient, *api_bpfrecorder.ProfileRequest) {
	fake.apparmorForProfileMutex.RLock()
	defer fake.apparmorForProfileMutex.RUnlock()
	argsForCall := fake.apparmorForProfileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBpfRecorderImpl) ApparmorForProfileReturns(result1 *api_bpfrecorder.ApparmorResponse, result2 error) {
	fake.apparmorForProfileMutex.Lock()
	defer fake.apparmorForProfileMutex.Unlock()
	fake.ApparmorForProfileStub = nil
	fake.apparmorForProfileReturns = struct {
		result1 *api_bpfrecorder.ApparmorResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeBpfRecorderImpl) ApparmorForProfileReturnsOnCall(i int, result1 *api_bpfrecorder.ApparmorResponse, result2 error) {
	fake.apparmorForProfileMutex.Lock()
	defer fake.apparmorForProfileMutex.Unlock()
	fake.ApparmorForProfileStub = nil
	if fake.apparmorForProfileReturnsOnCall == nil {
		fake.apparmorForProfileReturnsOnCall = make(map[int]struct {
			result1 *api_bpfrecorder.ApparmorResponse
			result2 error
		})
	}
	fake.apparmorForProfileReturnsOnCall[i] = struct {
		result1 *api_bpfrecorder.ApparmorResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeBpfRecorderImpl) DialBpfRecorder() (*grpc.ClientConn, error) {
	fake.dialBpfRecorderMutex.Lock()
	ret, specificReturn := fake.dialBpfRecorderReturnsOnCall[len(fake.dialBpfRecorderArgsForCall)]
	fake.dialBpfRecorderArgsForCall = append(fake.dialBpfRecorderArgsForCall, struct {
	}{})
	stub := fake.DialBpfRecorderStub
	fakeReturns := fake.dialBpfRecorderReturns
	fake.recordInvocation("DialBpfRecorder", []interface{}{})
	fake.dialBpfRecorderMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBpfRecorderImpl) DialBpfRecorderCallCount() int {
	fake.dialBpfRecorderMutex.RLock()
	defer fake.dialBpfRecorderMutex.RUnlock()
	return len(fake.dialBpfRecorderArgsForCall)
}

func (fake *FakeBpfRecorderImpl) DialBpfRecorderCalls(stub func() (*grpc.ClientConn, error)) {
	fake.dialBpfRecorderMutex.Lock()
	defer fake.dialBpfRecorderMutex.Unlock()
	fake.DialBpfRecorderStub = stub
}

func (fake *FakeBpfRecorderImpl) DialBpfRecorderReturns(result1 *grpc.ClientConn, result2 error) {
	fake.dialBpfRecorderMutex.Lock()
	defer fake.dialBpfRecorderMutex.Unlock()
	fake.DialBpfRecorderStub = nil
	fake.dialBpfRecorderReturns = struct {
		result1 *grpc.ClientConn
		result2 error
	}{result1, result2}
}

func (fake *FakeBpfRecorderImpl) DialBpfRecorderReturnsOnCall(i int, result1 *grpc.ClientConn, result2 error) {
	fake.dialBpfRecorderMutex.Lock()
	defer fake.dialBpfRecorderMutex.Unlock()
	fake.DialBpfRecorderStub = nil
	if fake.dialBpfRecorderReturnsOnCall == nil {
		fake.dialBpfRecorderReturnsOnCall = make(map[int]struct {
			result1 *grpc.ClientConn
			result2 error
		})
	}
	fake.dialBpfRecorderReturnsOnCall[i] = struct {
		result1 *grpc.ClientConn
		result2 error
	}{result1, result2}
}

func (fake *FakeBpfRecorderImpl) ResetApparmorForProfile(arg1 context.Context, arg2 api_bpfrecorder.BpfRecorderClient, arg3 *api_bpfrecorder.ProfileRequest) error {
	fake.resetApparmorForProfileMutex.Lock()
	ret, specificReturn := fake.resetApparmorForProfileReturnsOnCall[len(fake.resetApparmorForProfileArgsForCall)]
	fake.resetApparmorForProfileArgsForCall = append(fake.resetApparmorForProfileArgsForCall, struct {
		arg1 context.Context
		arg2 api_bpfrecorder.BpfRecorderClient
		arg3 *api_bpfrecorder.ProfileRequest
	}{arg1, arg2, arg3})
	stub := fake.ResetApparmorForProfileStub
	fakeReturns := fake.resetApparmorForProfileReturns
	fake.recordInvocation("ResetApparmorForProfile", []interface{}{arg1, arg2, arg3})
	fake.resetApparmorForProfileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBpfRecorderImpl) ResetApparmorForProfileCallCount() int {
	fake.resetApparmorForProfileMutex.RLock()
	defer fake.resetApparmorForProfileMutex.RUnlock()
	return len(fake.resetApparmorForProfileArgsForCall)
}

func (fake *FakeBpfRecorderImpl) ResetApparmorForProfileCalls(stub func(context.Context, api_bpfrecorder.BpfRecorderClient, *api_bpfrecorder.ProfileRequest) error) {
	fake.resetApparmorForProfileMutex.Lock()
	defer fake.resetApparmorForProfileMutex.Unlock()
	fake.ResetApparmorForProfileStub = stub
}

func (fake *FakeBpfRecorderImpl) ResetApparmorForProfileArgsForCall(i int) (context.Context, api_bpfrecorder.BpfRecorderClient, *api_bpfrecorder.ProfileRequest) {
	fake.resetApparmorForProfileMutex.RLock()
	defer fake.resetApparmorForProfileMutex.RUnlock()
	argsForCall := fake.resetApparmorForProfileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBpfRecorderImpl) ResetApparmorForProfileReturns(result1 error) {
	fake.resetApparmorForProfileMutex.Lock()
	defer fake.resetApparmorForProfileMutex.Unlock()
	fake.ResetApparmorForProfileStub = nil
	fake.resetApparmorForProfileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBpfRecorderImpl) ResetApparmorForProfileReturnsOnCall(i int, result1 error) {
	fake.resetApparmorForProfileMutex.Lock()
	defer fake.resetApparmorForProfileMutex.Unlock()
	fake.ResetApparmorForProfileStub = nil
	if fake.resetApparmorForProfileReturnsOnCall == nil {
		fake.resetApparmorForProfileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resetApparmorForProfileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBpfRecorderImpl) ResetSyscallsForProfile(arg1 context.Context, arg2 api_bpfrecorder.BpfRecorderClient, arg3 *api_bpfrecorder.ProfileRequest) error {
	fake.resetSyscallsForProfileMutex.Lock()
	ret, specificReturn := fake.resetSyscallsForProfileReturnsOnCall[len(fake.resetSyscallsForProfileArgsForCall)]
	fake.resetSyscallsForProfileArgsForCall = append(fake.resetSyscallsForProfileArgsForCall, struct {
		arg1 context.Context
		arg2 api_bpfrecorder.BpfRecorderClient
		arg3 *api_bpfrecorder.ProfileRequest
	}{arg1, arg2, arg3})
	stub := fake.ResetSyscallsForProfileStub
	fakeReturns := fake.resetSyscallsForProfileReturns
	fake.recordInvocation("ResetSyscallsForProfile", []interface{}{arg1, arg2, arg3})
	fake.resetSyscallsForProfileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBpfRecorderImpl) ResetSyscallsForProfileCallCount() int {
	fake.resetSyscallsForProfileMutex.RLock()
	defer fake.resetSyscallsForProfileMutex.RUnlock()
	return len(fake.resetSyscallsForProfileArgsForCall)
}

func (fake *FakeBpfRecorderImpl) ResetSyscallsForProfileCalls(stub func(context.Context, api_bpfrecorder.BpfRecorderClient, *api_bpfrecorder.ProfileRequest) error) {
	fake.resetSyscallsForProfileMutex.Lock()
	defer fake.resetSyscallsForProfileMutex.Unlock()
	fake.ResetSyscallsForProfileStub = stub
}

func (fake *FakeBpfRecorderImpl) ResetSyscallsForProfileArgsForCall(i int) (context.Context, api_bpfrecorder.BpfRecorderClient, *api_bpfrecorder.ProfileRequest) {
	fake.resetSyscallsForProfileMutex.RLock()
	defer fake.resetSyscallsForProfileMutex.RUnlock()
	argsForCall := fake.resetSyscallsForProfileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBpfRecorderImpl) ResetSyscallsForProfileReturns(result1 error) {
	fake.resetSyscallsForProfileMutex.Lock()
	defer fake.resetSyscallsForProfileMutex.Unlock()
	fake.ResetSyscallsForProfileStub = nil
	fake.resetSyscallsForProfileReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBpfRecorderImpl) ResetSyscallsForProfileReturnsOnCall(i int, result1 error) {
	fake.resetSyscallsForProfileMutex.Lock()
	defer fake.resetSyscallsForProfileMutex.Unlock()
	fake.ResetSyscallsForProfileStub = nil
	if fake.resetSyscallsForProfileReturnsOnCall == nil {
		fake.resetSyscallsForProfileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resetSyscallsForProfileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBpfRecorderImpl) StartBpfRecorder(arg1 context.Context, arg2 api_bpfrecorder.BpfRecorderClient) error {
	fake.startBpfRecorderMutex.Lock()
	ret, specificReturn := fake.startBpfRecorderReturnsOnCall[len(fake.startBpfRecorderArgsForCall)]
	fake.startBpfRecorderArgsForCall = append(fake.startBpfRecorderArgsForCall, struct {
		arg1 context.Context
		arg2 api_bpfrecorder.BpfRecorderClient
	}{arg1, arg2})
	stub := fake.StartBpfRecorderStub
	fakeReturns := fake.startBpfRecorderReturns
	fake.recordInvocation("StartBpfRecorder", []interface{}{arg1, arg2})
	fake.startBpfRecorderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBpfRecorderImpl) StartBpfRecorderCallCount() int {
	fake.startBpfRecorderMutex.RLock()
	defer fake.startBpfRecorderMutex.RUnlock()
	return len(fake.startBpfRecorderArgsForCall)
}

func (fake *FakeBpfRecorderImpl) StartBpfRecorderCalls(stub func(context.Context, api_bpfrecorder.BpfRecorderClient) error) {
	fake.startBpfRecorderMutex.Lock()
	defer fake.startBpfRecorderMutex.Unlock()
	fake.StartBpfRecorderStub = stub
}

func (fake *FakeBpfRecorderImpl) StartBpfRecorderArgsForCall(i int) (context.Context, api_bpfrecorder.BpfRecorderClient) {
	fake.startBpfRecorderMutex.RLock()
	defer fake.startBpfRecorderMutex.RUnlock()
	argsForCall := fake.startBpfRecorderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBpfRecorderImpl) StartBpfRecorderReturns(result1 error) {
	fake.startBpfRecorderMutex.Lock()
	defer fake.startBpfRecorderMutex.Unlock()
	fake.StartBpfRecorderStub = nil
	fake.startBpfRecorderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBpfRecorderImpl) StartBpfRecorderReturnsOnCall(i int, result1 error) {
	fake.startBpfRecorderMutex.Lock()
	defer fake.startBpfRecorderMutex.Unlock()
	fake.StartBpfRecorderStub = nil
	if fake.startBpfRecorderReturnsOnCall == nil {
		fake.startBpfRecorderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.startBpfRecorderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBpfRecorderImpl) StopBpfRecorder(arg1 context.Context, arg2 api_bpfrecorder.BpfRecorderClient) error {
	fake.stopBpfRecorderMutex.Lock()
	ret, specificReturn := fake.stopBpfRecorderReturnsOnCall[len(fake.stopBpfRecorderArgsForCall)]
	fake.stopBpfRecorderArgsForCall = append(fake.stopBpfRecorderArgsForCall, struct {
		arg1 context.Context
		arg2 api_bpfrecorder.BpfRecorderClient
	}{arg1, arg2})
	stub := fake.StopBpfRecorderStub
	fakeReturns := fake.stopBpfRecorderReturns
	fake.recordInvocation("StopBpfRecorder", []interface{}{arg1, arg2})
	fake.stopBpfRecorderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBpfRecorderImpl) StopBpfRecorderCallCount() int {
	fake.stopBpfRecorderMutex.RLock()
	defer fake.stopBpfRecorderMutex.RUnlock()
	return len(fake.stopBpfRecorderArgsForCall)
}

func (fake *FakeBpfRecorderImpl) StopBpfRecorderCalls(stub func(context.Context, api_bpfrecorder.BpfRecorderClient) error) {
	fake.stopBpfRecorderMutex.Lock()
	defer fake.stopBpfRecorderMutex.Unlock()
	fake.StopBpfRecorderStub = stub
}

func (fake *FakeBpfRecorderImpl) StopBpfRecorderArgsForCall(i int) (context.Context, api_bpfrecorder.BpfRecorderClient) {
	fake.stopBpfRecorderMutex.RLock()
	defer fake.stopBpfRecorderMutex.RUnlock()
	argsForCall := fake.stopBpfRecorderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBpfRecorderImpl) StopBpfRecorderReturns(result1 error) {
	fake.stopBpfRecorderMutex.Lock()
	defer fake.stopBpfRecorderMutex.Unlock()
	fake.StopBpfRecorderStub = nil
	fake.stopBpfRecorderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBpfRecorderImpl) StopBpfRecorderReturnsOnCall(i int, result1 error) {
	fake.stopBpfRecorderMutex.Lock()
	defer fake.stopBpfRecorderMutex.Unlock()
	fake.StopBpfRecorderStub = nil
	if fake.stopBpfRecorderReturnsOnCall == nil {
		fake.stopBpfRecorderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.stopBpfRecorderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBpfRecorderImpl) SyscallsForProfile(arg1 context.Context, arg2 api_bpfrecorder.BpfRecorderClient, arg3 *api_bpfrecorder.ProfileRequest) (*api_bpfrecorder.SyscallsResponse, error) {
	fake.syscallsForProfileMutex.Lock()
	ret, specificReturn := fake.syscallsForProfileReturnsOnCall[len(fake.syscallsForProfileArgsForCall)]
	fake.syscallsForProfileArgsForCall = append(fake.syscallsForProfileArgsForCall, struct {
		arg1 context.Context
		arg2 api_bpfrecorder.BpfRecorderClient
		arg3 *api_bpfrecorder.ProfileRequest
	}{arg1, arg2, arg3})
	stub := fake.SyscallsForProfileStub
	fakeReturns := fake.syscallsForProfileReturns
	fake.recordInvocation("SyscallsForProfile", []interface{}{arg1, arg2, arg3})
	fake.syscallsForProfileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBpfRecorderImpl) SyscallsForProfileCallCount() int {
	fake.syscallsForProfileMutex.RLock()
	defer fake.syscallsForProfileMutex.RUnlock()
	return len(fake.syscallsForProfileArgsForCall)
}

func (fake *FakeBpfRecorderImpl) SyscallsForProfileCalls(stub func(context.Context, api_bpfrecorder.BpfRecorderClient, *api_bpfrecorder.ProfileRequest) (*api_bpfrecorder.SyscallsResponse, error)) {
	fake.syscallsForProfileMutex.Lock()
	defer fake.syscallsForProfileMutex.Unlock()
	fake.SyscallsForProfileStub = stub
}

func (fake *FakeBpfRecorderImpl) SyscallsForProfileArgsForCall(i int) (context.Context, api_bpfrecorder.BpfRecorderClient, *api_bpfrecorder.ProfileRequest) {
	fake.syscallsForProfileMutex.RLock()
	defer fake.syscallsForProfileMutex.RUnlock()
	argsForCall := fake.syscallsForProfileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBpfRecorderImpl) SyscallsForProfileReturns(result1 *api_bpfrecorder.SyscallsResponse, result2 error) {
	fake.syscallsForProfileMutex.Lock()
	defer fake.syscallsForProfileMutex.Unlock()
	fake.SyscallsForProfileStub = nil
	fake.syscallsForProfileReturns = struct {
		result1 *api_bpfrecorder.SyscallsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeBpfRecorderImpl) SyscallsForProfileReturnsOnCall(i int, result1 *api_bpfrecorder.SyscallsResponse, result2 error) {
	fake.syscallsForProfileMutex.Lock()
	defer fake.syscallsForProfileMutex.Unlock()
	fake.SyscallsForProfileStub = nil
	if fake.syscallsForProfileReturnsOnCall == nil {
		fake.syscallsForProfileReturnsOnCall = make(map[int]struct {
			result1 *api_bpfrecorder.SyscallsResponse
			result2 error
		})
	}
	fake.syscallsForProfileReturnsOnCall[i] = struct {
		result1 *api_bpfrecorder.SyscallsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeBpfRecorderImpl) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBpfRecorderImpl) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
