apiVersion: security-profiles-operator.x-k8s.io/v1
kind: SecurityProfilesOperatorDaemon
metadata:
  labels:
    {{- include "security-profiles-operator.labels" . | nindent 4 }}
  name: spod
  namespace: {{ .Release.Namespace }}
spec:
  scheduling:
    {{- with .Values.daemon.affinity }}
    affinity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.daemon.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  daemonResourceRequirements:
    {{- toYaml .Values.daemon.resources | nindent 4 }}
  selinux:
    enable: {{ or .Values.enableSelinux .Values.selinux.enable }}
    enableRawSelinuxProfiles: {{ .Values.selinux.enableRawSelinuxProfiles }}
    typeTag: {{ .Values.selinux.typeTag }}
    {{- with .Values.selinux.options }}
    options:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  enricher:
    enableLogEnricher: {{ .Values.enableLogEnricher }}
    enableJsonEnricher: {{ .Values.enableJsonEnricher }}
    enableBpfRecorder: {{ .Values.enableBpfRecorder }}
  enableAppArmor: {{ .Values.enableAppArmor }}
  enableProfiling: {{ .Values.enableProfiling }}
  verbosity: {{ .Values.verbosity }}
