---
run:
  concurrency: 6
  timeout: 10m
issues:
  exclude-rules:
    - path: internal/pkg/daemon/bpfrecorder/generated.go
      linters:
        - gofumpt
        - lll
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - ineffassign
    - intrange
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
    # - cyclop
    # - depguard
    # - err113
    # - exhaustruct
    # - forbidigo
    # - funlen
    # - gochecknoglobals
    # - gomoddirectives
    # - inamedparam
    # - interfacebloat
    # - ireturn
    # - maintidx
    # - mnd
    # - nlreturn
    # - nonamedreturns
    # - testpackage
    # - varnamelen
    # - wrapcheck
    # - wsl
linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  goconst:
    min-occurrences: 6
  gomoddirectives:
    replace-allow-list:
      - golang.org/x/sys
  gocognit:
    min-complexity: 40
  gosec:
    excludes:
      - G115  # Potential integer overflow when converting between types
  nestif:
    min-complexity: 15
  gci:
    sections:
      - standard
      - default
      - localmodule
  errcheck:
    check-type-assertions: true
    check-blank: true
  godox:
    keywords:
      - BUG
      - FIXME
      - HACK
  gocritic:
    enable-all: true
