---
version: "2"
run:
  concurrency: 6
linters:
  default: none
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - ineffassign
    - intrange
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl_v5
    - zerologlint
    # - cyclop
    # - depguard
    # - embeddedstructfieldcheck
    # - err113
    # - exhaustruct
    # - forbidigo
    # - funcorder
    # - funlen
    # - gochecknoglobals
    # - gomoddirectives
    # - inamedparam
    # - interfacebloat
    # - ireturn
    # - maintidx
    # - mnd
    # - noctx
    # - noinlineerr
    # - nonamedreturns
    # - testpackage
    # - varnamelen
    # - wrapcheck
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocognit:
      min-complexity: 40
    goconst:
      min-occurrences: 6
    gocritic:
      enable-all: true
    godox:
      keywords:
        - BUG
        - FIXME
        - HACK
    gomoddirectives:
      replace-allow-list:
        - golang.org/x/sys
    gosec:
      excludes:
        - G115
    nestif:
      min-complexity: 15
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        path: internal/pkg/daemon/bpfrecorder/generated.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/pkg/daemon/bpfrecorder/generated.go
