---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

patchesJson6902:
  - target:
      group: security-profiles-operator.x-k8s.io
      version: v1alpha1
      kind: SeccompProfile
      name: nginx-1.19.1
      namespace: security-profiles-operator
    path: seccompprofile.yaml
