# This is a OpenShift-specific deployment. It is not meant for consumption by
# upstream users but rather as a base for downstream OCP packaging. For pure
# upstream deployments, please use deploy/operator.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo

resources:
- ../cluster
patches:
- patch: |-
    - op: replace
      path: "/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/webhookOptions/default"
      value:
        - name: nodedebuggingpod.spo.io
          objectSelector:
            matchLabels:
              debug.openshift.io/managed-by: "oc-debug"
  target:
    kind: CustomResourceDefinition
    name: securityprofilesoperatordaemons.security-profiles-operator.x-k8s.io
- path: service_discovery_rules.yaml
  target:
    kind: ClusterRole
    name: spo-metrics-client
- path: bind_monitoring_sa.yaml
  target:
    kind: ClusterRoleBinding
    name: spo-metrics-client
