/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by counterfeiter. DO NOT EDIT.
package enricherfakes

import (
	"context"
	"io"
	"net"
	"os"
	"sync"
	"time"

	ttlcache "github.com/jellydator/ttlcache/v3"
	"google.golang.org/grpc"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	api_metrics "sigs.k8s.io/security-profiles-operator/api/grpc/metrics"
	"sigs.k8s.io/security-profiles-operator/internal/pkg/daemon/enricher/auditsource"
	"sigs.k8s.io/security-profiles-operator/internal/pkg/daemon/enricher/tailer"
	"sigs.k8s.io/security-profiles-operator/internal/pkg/daemon/enricher/types"
	"sigs.k8s.io/security-profiles-operator/internal/pkg/daemon/podindex"
)

type FakeImpl struct {
	AuditIncStub        func(context.Context, api_metrics.MetricsClient) (api_metrics.Metrics_AuditIncClient, error)
	auditIncMutex       sync.RWMutex
	auditIncArgsForCall []FakeImplAuditIncArgs
	auditIncReturns     struct {
		result1 api_metrics.Metrics_AuditIncClient
		result2 error
	}
	auditIncReturnsOnCall map[int]struct {
		result1 api_metrics.Metrics_AuditIncClient
		result2 error
	}
	ChownStub        func(string, int, int) error
	chownMutex       sync.RWMutex
	chownArgsForCall []FakeImplChownArgs
	chownReturns     struct {
		result1 error
	}
	chownReturnsOnCall map[int]struct {
		result1 error
	}
	CloseStub        func(*grpc.ClientConn) error
	closeMutex       sync.RWMutex
	closeArgsForCall []FakeImplCloseArgs
	closeReturns     struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	CmdlineForPIDStub        func(int) (string, error)
	cmdlineForPIDMutex       sync.RWMutex
	cmdlineForPIDArgsForCall []FakeImplCmdlineForPIDArgs
	cmdlineForPIDReturns     struct {
		result1 string
		result2 error
	}
	cmdlineForPIDReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ContainerIDForPIDStub        func(*ttlcache.Cache[string, string], int) (string, time.Duration, error)
	containerIDForPIDMutex       sync.RWMutex
	containerIDForPIDArgsForCall []FakeImplContainerIDForPIDArgs
	containerIDForPIDReturns     struct {
		result1 string
		result2 time.Duration
		result3 error
	}
	containerIDForPIDReturnsOnCall map[int]struct {
		result1 string
		result2 time.Duration
		result3 error
	}
	DialStub        func() (*grpc.ClientConn, error)
	dialMutex       sync.RWMutex
	dialArgsForCall []struct{}
	dialReturns     struct {
		result1 *grpc.ClientConn
		result2 error
	}
	dialReturnsOnCall map[int]struct {
		result1 *grpc.ClientConn
		result2 error
	}
	EnvForPidStub        func(int) (map[string]string, error)
	envForPidMutex       sync.RWMutex
	envForPidArgsForCall []FakeImplEnvForPidArgs
	envForPidReturns     struct {
		result1 map[string]string
		result2 error
	}
	envForPidReturnsOnCall map[int]struct {
		result1 map[string]string
		result2 error
	}
	InClusterConfigStub        func() (*rest.Config, error)
	inClusterConfigMutex       sync.RWMutex
	inClusterConfigArgsForCall []struct{}
	inClusterConfigReturns     struct {
		result1 *rest.Config
		result2 error
	}
	inClusterConfigReturnsOnCall map[int]struct {
		result1 *rest.Config
		result2 error
	}
	LinesStub        func(*tailer.Tailer) <-chan string
	linesMutex       sync.RWMutex
	linesArgsForCall []FakeImplLinesArgs
	linesReturns     struct {
		result1 <-chan string
	}
	linesReturnsOnCall map[int]struct {
		result1 <-chan string
	}
	ListenStub        func(context.Context, string, string) (net.Listener, error)
	listenMutex       sync.RWMutex
	listenArgsForCall []FakeImplListenArgs
	listenReturns     struct {
		result1 net.Listener
		result2 error
	}
	listenReturnsOnCall map[int]struct {
		result1 net.Listener
		result2 error
	}
	NewForConfigStub        func(*rest.Config) (*kubernetes.Clientset, error)
	newForConfigMutex       sync.RWMutex
	newForConfigArgsForCall []FakeImplNewForConfigArgs
	newForConfigReturns     struct {
		result1 *kubernetes.Clientset
		result2 error
	}
	newForConfigReturnsOnCall map[int]struct {
		result1 *kubernetes.Clientset
		result2 error
	}
	PodListerWatcherStub        func(kubernetes.Interface, string) podindex.ListerWatcher
	podListerWatcherMutex       sync.RWMutex
	podListerWatcherArgsForCall []FakeImplPodListerWatcherArgs
	podListerWatcherReturns     struct {
		result1 podindex.ListerWatcher
	}
	podListerWatcherReturnsOnCall map[int]struct {
		result1 podindex.ListerWatcher
	}
	PrintJsonOutputStub         func(io.Writer, []byte)
	printJsonOutputMutex        sync.RWMutex
	printJsonOutputArgsForCall  []FakeImplPrintJsonOutputArgs
	ProcessStartTimeStub        func(int) (time.Duration, error)
	processStartTimeMutex       sync.RWMutex
	processStartTimeArgsForCall []FakeImplProcessStartTimeArgs
	processStartTimeReturns     struct {
		result1 time.Duration
		result2 error
	}
	processStartTimeReturnsOnCall map[int]struct {
		result1 time.Duration
		result2 error
	}
	ReasonStub        func(*tailer.Tailer) error
	reasonMutex       sync.RWMutex
	reasonArgsForCall []FakeImplReasonArgs
	reasonReturns     struct {
		result1 error
	}
	reasonReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveAllStub        func(string) error
	removeAllMutex       sync.RWMutex
	removeAllArgsForCall []FakeImplRemoveAllArgs
	removeAllReturns     struct {
		result1 error
	}
	removeAllReturnsOnCall map[int]struct {
		result1 error
	}
	SendMetricStub        func(api_metrics.Metrics_AuditIncClient, *api_metrics.AuditRequest) error
	sendMetricMutex       sync.RWMutex
	sendMetricArgsForCall []FakeImplSendMetricArgs
	sendMetricReturns     struct {
		result1 error
	}
	sendMetricReturnsOnCall map[int]struct {
		result1 error
	}
	ServeStub        func(*grpc.Server, net.Listener) error
	serveMutex       sync.RWMutex
	serveArgsForCall []FakeImplServeArgs
	serveReturns     struct {
		result1 error
	}
	serveReturnsOnCall map[int]struct {
		result1 error
	}
	StartTailStub        func(auditsource.AuditLineSource) (chan *types.AuditLine, error)
	startTailMutex       sync.RWMutex
	startTailArgsForCall []FakeImplStartTailArgs
	startTailReturns     struct {
		result1 chan *types.AuditLine
		result2 error
	}
	startTailReturnsOnCall map[int]struct {
		result1 chan *types.AuditLine
		result2 error
	}
	StatStub        func(string) (os.FileInfo, error)
	statMutex       sync.RWMutex
	statArgsForCall []FakeImplStatArgs
	statReturns     struct {
		result1 os.FileInfo
		result2 error
	}
	statReturnsOnCall map[int]struct {
		result1 os.FileInfo
		result2 error
	}
	StopTailStub        func(*tailer.Tailer)
	stopTailMutex       sync.RWMutex
	stopTailArgsForCall []FakeImplStopTailArgs
	TailErrStub         func(auditsource.AuditLineSource) error
	tailErrMutex        sync.RWMutex
	tailErrArgsForCall  []FakeImplTailErrArgs
	tailErrReturns      struct {
		result1 error
	}
	tailErrReturnsOnCall map[int]struct {
		result1 error
	}
	TailFileStub        func(string, tailer.Config) (*tailer.Tailer, error)
	tailFileMutex       sync.RWMutex
	tailFileArgsForCall []FakeImplTailFileArgs
	tailFileReturns     struct {
		result1 *tailer.Tailer
		result2 error
	}
	tailFileReturnsOnCall map[int]struct {
		result1 *tailer.Tailer
		result2 error
	}
	UptimeStub        func() (time.Duration, error)
	uptimeMutex       sync.RWMutex
	uptimeArgsForCall []struct{}
	uptimeReturns     struct {
		result1 time.Duration
		result2 error
	}
	uptimeReturnsOnCall map[int]struct {
		result1 time.Duration
		result2 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// FakeImplAuditIncArgs holds the arguments of one call to AuditInc.
type FakeImplAuditIncArgs struct {
	Arg1 context.Context
	Arg2 api_metrics.MetricsClient
}

// FakeImplChownArgs holds the arguments of one call to Chown.
type FakeImplChownArgs struct {
	Arg1 string
	Arg2 int
	Arg3 int
}

// FakeImplCloseArgs holds the arguments of one call to Close.
type FakeImplCloseArgs struct {
	Arg1 *grpc.ClientConn
}

// FakeImplCmdlineForPIDArgs holds the arguments of one call to CmdlineForPID.
type FakeImplCmdlineForPIDArgs struct {
	Arg1 int
}

// FakeImplContainerIDForPIDArgs holds the arguments of one call to ContainerIDForPID.
type FakeImplContainerIDForPIDArgs struct {
	Arg1 *ttlcache.Cache[string, string]
	Arg2 int
}

// FakeImplEnvForPidArgs holds the arguments of one call to EnvForPid.
type FakeImplEnvForPidArgs struct {
	Arg1 int
}

// FakeImplLinesArgs holds the arguments of one call to Lines.
type FakeImplLinesArgs struct {
	Arg1 *tailer.Tailer
}

// FakeImplListenArgs holds the arguments of one call to Listen.
type FakeImplListenArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 string
}

// FakeImplNewForConfigArgs holds the arguments of one call to NewForConfig.
type FakeImplNewForConfigArgs struct {
	Arg1 *rest.Config
}

// FakeImplPodListerWatcherArgs holds the arguments of one call to PodListerWatcher.
type FakeImplPodListerWatcherArgs struct {
	Arg1 kubernetes.Interface
	Arg2 string
}

// FakeImplPrintJsonOutputArgs holds the arguments of one call to PrintJsonOutput.
type FakeImplPrintJsonOutputArgs struct {
	Arg1 io.Writer
	Arg2 []byte
}

// FakeImplProcessStartTimeArgs holds the arguments of one call to ProcessStartTime.
type FakeImplProcessStartTimeArgs struct {
	Arg1 int
}

// FakeImplReasonArgs holds the arguments of one call to Reason.
type FakeImplReasonArgs struct {
	Arg1 *tailer.Tailer
}

// FakeImplRemoveAllArgs holds the arguments of one call to RemoveAll.
type FakeImplRemoveAllArgs struct {
	Arg1 string
}

// FakeImplSendMetricArgs holds the arguments of one call to SendMetric.
type FakeImplSendMetricArgs struct {
	Arg1 api_metrics.Metrics_AuditIncClient
	Arg2 *api_metrics.AuditRequest
}

// FakeImplServeArgs holds the arguments of one call to Serve.
type FakeImplServeArgs struct {
	Arg1 *grpc.Server
	Arg2 net.Listener
}

// FakeImplStartTailArgs holds the arguments of one call to StartTail.
type FakeImplStartTailArgs struct {
	Arg1 auditsource.AuditLineSource
}

// FakeImplStatArgs holds the arguments of one call to Stat.
type FakeImplStatArgs struct {
	Arg1 string
}

// FakeImplStopTailArgs holds the arguments of one call to StopTail.
type FakeImplStopTailArgs struct {
	Arg1 *tailer.Tailer
}

// FakeImplTailErrArgs holds the arguments of one call to TailErr.
type FakeImplTailErrArgs struct {
	Arg1 auditsource.AuditLineSource
}

// FakeImplTailFileArgs holds the arguments of one call to TailFile.
type FakeImplTailFileArgs struct {
	Arg1 string
	Arg2 tailer.Config
}

func (fake *FakeImpl) AuditInc(arg1 context.Context, arg2 api_metrics.MetricsClient) (api_metrics.Metrics_AuditIncClient, error) {
	fake.auditIncMutex.Lock()
	ret, specificReturn := fake.auditIncReturnsOnCall[len(fake.auditIncArgsForCall)]
	fake.auditIncArgsForCall = append(fake.auditIncArgsForCall, FakeImplAuditIncArgs{arg1, arg2})
	stub := fake.AuditIncStub
	fakeReturns := fake.auditIncReturns
	fake.recordInvocation("AuditInc", []interface{}{arg1, arg2})
	fake.auditIncMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) AuditIncCallCount() int {
	fake.auditIncMutex.RLock()
	defer fake.auditIncMutex.RUnlock()
	return len(fake.auditIncArgsForCall)
}

func (fake *FakeImpl) AuditIncCalls(stub func(context.Context, api_metrics.MetricsClient) (api_metrics.Metrics_AuditIncClient, error)) {
	fake.auditIncMutex.Lock()
	defer fake.auditIncMutex.Unlock()
	fake.AuditIncStub = stub
}

func (fake *FakeImpl) AuditIncArgsForCall(i int) (context.Context, api_metrics.MetricsClient) {
	fake.auditIncMutex.RLock()
	defer fake.auditIncMutex.RUnlock()
	argsForCall := fake.auditIncArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeImpl) AuditIncArgs() []FakeImplAuditIncArgs {
	fake.auditIncMutex.RLock()
	defer fake.auditIncMutex.RUnlock()
	args := make([]FakeImplAuditIncArgs, len(fake.auditIncArgsForCall))
	copy(args, fake.auditIncArgsForCall)
	return args
}

func (fake *FakeImpl) AuditIncReturns(result1 api_metrics.Metrics_AuditIncClient, result2 error) {
	fake.auditIncMutex.Lock()
	defer fake.auditIncMutex.Unlock()
	fake.AuditIncStub = nil
	fake.auditIncReturns = struct {
		result1 api_metrics.Metrics_AuditIncClient
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) AuditIncReturnsOnCall(i int, result1 api_metrics.Metrics_AuditIncClient, result2 error) {
	fake.auditIncMutex.Lock()
	defer fake.auditIncMutex.Unlock()
	fake.AuditIncStub = nil
	if fake.auditIncReturnsOnCall == nil {
		fake.auditIncReturnsOnCall = make(map[int]struct {
			result1 api_metrics.Metrics_AuditIncClient
			result2 error
		})
	}
	fake.auditIncReturnsOnCall[i] = struct {
		result1 api_metrics.Metrics_AuditIncClient
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) Chown(arg1 string, arg2 int, arg3 int) error {
	fake.chownMutex.Lock()
	ret, specificReturn := fake.chownReturnsOnCall[len(fake.chownArgsForCall)]
	fake.chownArgsForCall = append(fake.chownArgsForCall, FakeImplChownArgs{arg1, arg2, arg3})
	stub := fake.ChownStub
	fakeReturns := fake.chownReturns
	fake.recordInvocation("Chown", []interface{}{arg1, arg2, arg3})
	fake.chownMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) ChownCallCount() int {
	fake.chownMutex.RLock()
	defer fake.chownMutex.RUnlock()
	return len(fake.chownArgsForCall)
}

func (fake *FakeImpl) ChownCalls(stub func(string, int, int) error) {
	fake.chownMutex.Lock()
	defer fake.chownMutex.Unlock()
	fake.ChownStub = stub
}

func (fake *FakeImpl) ChownArgsForCall(i int) (string, int, int) {
	fake.chownMutex.RLock()
	defer fake.chownMutex.RUnlock()
	argsForCall := fake.chownArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeImpl) ChownArgs() []FakeImplChownArgs {
	fake.chownMutex.RLock()
	defer fake.chownMutex.RUnlock()
	args := make([]FakeImplChownArgs, len(fake.chownArgsForCall))
	copy(args, fake.chownArgsForCall)
	return args
}

func (fake *FakeImpl) ChownReturns(result1 error) {
	fake.chownMutex.Lock()
	defer fake.chownMutex.Unlock()
	fake.ChownStub = nil
	fake.chownReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) ChownReturnsOnCall(i int, result1 error) {
	fake.chownMutex.Lock()
	defer fake.chownMutex.Unlock()
	fake.ChownStub = nil
	if fake.chownReturnsOnCall == nil {
		fake.chownReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.chownReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) Close(arg1 *grpc.ClientConn) error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, FakeImplCloseArgs{arg1})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{arg1})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeImpl) CloseCalls(stub func(*grpc.ClientConn) error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeImpl) CloseArgsForCall(i int) *grpc.ClientConn {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	argsForCall := fake.closeArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) CloseArgs() []FakeImplCloseArgs {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	args := make([]FakeImplCloseArgs, len(fake.closeArgsForCall))
	copy(args, fake.closeArgsForCall)
	return args
}

func (fake *FakeImpl) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) CmdlineForPID(arg1 int) (string, error) {
	fake.cmdlineForPIDMutex.Lock()
	ret, specificReturn := fake.cmdlineForPIDReturnsOnCall[len(fake.cmdlineForPIDArgsForCall)]
	fake.cmdlineForPIDArgsForCall = append(fake.cmdlineForPIDArgsForCall, FakeImplCmdlineForPIDArgs{arg1})
	stub := fake.CmdlineForPIDStub
	fakeReturns := fake.cmdlineForPIDReturns
	fake.recordInvocation("CmdlineForPID", []interface{}{arg1})
	fake.cmdlineForPIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) CmdlineForPIDCallCount() int {
	fake.cmdlineForPIDMutex.RLock()
	defer fake.cmdlineForPIDMutex.RUnlock()
	return len(fake.cmdlineForPIDArgsForCall)
}

func (fake *FakeImpl) CmdlineForPIDCalls(stub func(int) (string, error)) {
	fake.cmdlineForPIDMutex.Lock()
	defer fake.cmdlineForPIDMutex.Unlock()
	fake.CmdlineForPIDStub = stub
}

func (fake *FakeImpl) CmdlineForPIDArgsForCall(i int) int {
	fake.cmdlineForPIDMutex.RLock()
	defer fake.cmdlineForPIDMutex.RUnlock()
	argsForCall := fake.cmdlineForPIDArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) CmdlineForPIDArgs() []FakeImplCmdlineForPIDArgs {
	fake.cmdlineForPIDMutex.RLock()
	defer fake.cmdlineForPIDMutex.RUnlock()
	args := make([]FakeImplCmdlineForPIDArgs, len(fake.cmdlineForPIDArgsForCall))
	copy(args, fake.cmdlineForPIDArgsForCall)
	return args
}

func (fake *FakeImpl) CmdlineForPIDReturns(result1 string, result2 error) {
	fake.cmdlineForPIDMutex.Lock()
	defer fake.cmdlineForPIDMutex.Unlock()
	fake.CmdlineForPIDStub = nil
	fake.cmdlineForPIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) CmdlineForPIDReturnsOnCall(i int, result1 string, result2 error) {
	fake.cmdlineForPIDMutex.Lock()
	defer fake.cmdlineForPIDMutex.Unlock()
	fake.CmdlineForPIDStub = nil
	if fake.cmdlineForPIDReturnsOnCall == nil {
		fake.cmdlineForPIDReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.cmdlineForPIDReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ContainerIDForPID(arg1 *ttlcache.Cache[string, string], arg2 int) (string, time.Duration, error) {
	fake.containerIDForPIDMutex.Lock()
	ret, specificReturn := fake.containerIDForPIDReturnsOnCall[len(fake.containerIDForPIDArgsForCall)]
	fake.containerIDForPIDArgsForCall = append(fake.containerIDForPIDArgsForCall, FakeImplContainerIDForPIDArgs{arg1, arg2})
	stub := fake.ContainerIDForPIDStub
	fakeReturns := fake.containerIDForPIDReturns
	fake.recordInvocation("ContainerIDForPID", []interface{}{arg1, arg2})
	fake.containerIDForPIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeImpl) ContainerIDForPIDCallCount() int {
	fake.containerIDForPIDMutex.RLock()
	defer fake.containerIDForPIDMutex.RUnlock()
	return len(fake.containerIDForPIDArgsForCall)
}

func (fake *FakeImpl) ContainerIDForPIDCalls(stub func(*ttlcache.Cache[string, string], int) (string, time.Duration, error)) {
	fake.containerIDForPIDMutex.Lock()
	defer fake.containerIDForPIDMutex.Unlock()
	fake.ContainerIDForPIDStub = stub
}

func (fake *FakeImpl) ContainerIDForPIDArgsForCall(i int) (*ttlcache.Cache[string, string], int) {
	fake.containerIDForPIDMutex.RLock()
	defer fake.containerIDForPIDMutex.RUnlock()
	argsForCall := fake.containerIDForPIDArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeImpl) ContainerIDForPIDArgs() []FakeImplContainerIDForPIDArgs {
	fake.containerIDForPIDMutex.RLock()
	defer fake.containerIDForPIDMutex.RUnlock()
	args := make([]FakeImplContainerIDForPIDArgs, len(fake.containerIDForPIDArgsForCall))
	copy(args, fake.containerIDForPIDArgsForCall)
	return args
}

func (fake *FakeImpl) ContainerIDForPIDReturns(result1 string, result2 time.Duration, result3 error) {
	fake.containerIDForPIDMutex.Lock()
	defer fake.containerIDForPIDMutex.Unlock()
	fake.ContainerIDForPIDStub = nil
	fake.containerIDForPIDReturns = struct {
		result1 string
		result2 time.Duration
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeImpl) ContainerIDForPIDReturnsOnCall(i int, result1 string, result2 time.Duration, result3 error) {
	fake.containerIDForPIDMutex.Lock()
	defer fake.containerIDForPIDMutex.Unlock()
	fake.ContainerIDForPIDStub = nil
	if fake.containerIDForPIDReturnsOnCall == nil {
		fake.containerIDForPIDReturnsOnCall = make(map[int]struct {
			result1 string
			result2 time.Duration
			result3 error
		})
	}
	fake.containerIDForPIDReturnsOnCall[i] = struct {
		result1 string
		result2 time.Duration
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeImpl) Dial() (*grpc.ClientConn, error) {
	fake.dialMutex.Lock()
	ret, specificReturn := fake.dialReturnsOnCall[len(fake.dialArgsForCall)]
	fake.dialArgsForCall = append(fake.dialArgsForCall, struct{}{})
	stub := fake.DialStub
	fakeReturns := fake.dialReturns
	fake.recordInvocation("Dial", []interface{}{})
	fake.dialMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) DialCallCount() int {
	fake.dialMutex.RLock()
	defer fake.dialMutex.RUnlock()
	return len(fake.dialArgsForCall)
}

func (fake *FakeImpl) DialCalls(stub func() (*grpc.ClientConn, error)) {
	fake.dialMutex.Lock()
	defer fake.dialMutex.Unlock()
	fake.DialStub = stub
}

func (fake *FakeImpl) DialReturns(result1 *grpc.ClientConn, result2 error) {
	fake.dialMutex.Lock()
	defer fake.dialMutex.Unlock()
	fake.DialStub = nil
	fake.dialReturns = struct {
		result1 *grpc.ClientConn
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) DialReturnsOnCall(i int, result1 *grpc.ClientConn, result2 error) {
	fake.dialMutex.Lock()
	defer fake.dialMutex.Unlock()
	fake.DialStub = nil
	if fake.dialReturnsOnCall == nil {
		fake.dialReturnsOnCall = make(map[int]struct {
			result1 *grpc.ClientConn
			result2 error
		})
	}
	fake.dialReturnsOnCall[i] = struct {
		result1 *grpc.ClientConn
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) EnvForPid(arg1 int) (map[string]string, error) {
	fake.envForPidMutex.Lock()
	ret, specificReturn := fake.envForPidReturnsOnCall[len(fake.envForPidArgsForCall)]
	fake.envForPidArgsForCall = append(fake.envForPidArgsForCall, FakeImplEnvForPidArgs{arg1})
	stub := fake.EnvForPidStub
	fakeReturns := fake.envForPidReturns
	fake.recordInvocation("EnvForPid", []interface{}{arg1})
	fake.envForPidMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) EnvForPidCallCount() int {
	fake.envForPidMutex.RLock()
	defer fake.envForPidMutex.RUnlock()
	return len(fake.envForPidArgsForCall)
}

func (fake *FakeImpl) EnvForPidCalls(stub func(int) (map[string]string, error)) {
	fake.envForPidMutex.Lock()
	defer fake.envForPidMutex.Unlock()
	fake.EnvForPidStub = stub
}

func (fake *FakeImpl) EnvForPidArgsForCall(i int) int {
	fake.envForPidMutex.RLock()
	defer fake.envForPidMutex.RUnlock()
	argsForCall := fake.envForPidArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) EnvForPidArgs() []FakeImplEnvForPidArgs {
	fake.envForPidMutex.RLock()
	defer fake.envForPidMutex.RUnlock()
	args := make([]FakeImplEnvForPidArgs, len(fake.envForPidArgsForCall))
	copy(args, fake.envForPidArgsForCall)
	return args
}

func (fake *FakeImpl) EnvForPidReturns(result1 map[string]string, result2 error) {
	fake.envForPidMutex.Lock()
	defer fake.envForPidMutex.Unlock()
	fake.EnvForPidStub = nil
	fake.envForPidReturns = struct {
		result1 map[string]string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) EnvForPidReturnsOnCall(i int, result1 map[string]string, result2 error) {
	fake.envForPidMutex.Lock()
	defer fake.envForPidMutex.Unlock()
	fake.EnvForPidStub = nil
	if fake.envForPidReturnsOnCall == nil {
		fake.envForPidReturnsOnCall = make(map[int]struct {
			result1 map[string]string
			result2 error
		})
	}
	fake.envForPidReturnsOnCall[i] = struct {
		result1 map[string]string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) InClusterConfig() (*rest.Config, error) {
	fake.inClusterConfigMutex.Lock()
	ret, specificReturn := fake.inClusterConfigReturnsOnCall[len(fake.inClusterConfigArgsForCall)]
	fake.inClusterConfigArgsForCall = append(fake.inClusterConfigArgsForCall, struct{}{})
	stub := fake.InClusterConfigStub
	fakeReturns := fake.inClusterConfigReturns
	fake.recordInvocation("InClusterConfig", []interface{}{})
	fake.inClusterConfigMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) InClusterConfigCallCount() int {
	fake.inClusterConfigMutex.RLock()
	defer fake.inClusterConfigMutex.RUnlock()
	return len(fake.inClusterConfigArgsForCall)
}

func (fake *FakeImpl) InClusterConfigCalls(stub func() (*rest.Config, error)) {
	fake.inClusterConfigMutex.Lock()
	defer fake.inClusterConfigMutex.Unlock()
	fake.InClusterConfigStub = stub
}

func (fake *FakeImpl) InClusterConfigReturns(result1 *rest.Config, result2 error) {
	fake.inClusterConfigMutex.Lock()
	defer fake.inClusterConfigMutex.Unlock()
	fake.InClusterConfigStub = nil
	fake.inClusterConfigReturns = struct {
		result1 *rest.Config
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) InClusterConfigReturnsOnCall(i int, result1 *rest.Config, result2 error) {
	fake.inClusterConfigMutex.Lock()
	defer fake.inClusterConfigMutex.Unlock()
	fake.InClusterConfigStub = nil
	if fake.inClusterConfigReturnsOnCall == nil {
		fake.inClusterConfigReturnsOnCall = make(map[int]struct {
			result1 *rest.Config
			result2 error
		})
	}
	fake.inClusterConfigReturnsOnCall[i] = struct {
		result1 *rest.Config
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) Lines(arg1 *tailer.Tailer) <-chan string {
	fake.linesMutex.Lock()
	ret, specificReturn := fake.linesReturnsOnCall[len(fake.linesArgsForCall)]
	fake.linesArgsForCall = append(fake.linesArgsForCall, FakeImplLinesArgs{arg1})
	stub := fake.LinesStub
	fakeReturns := fake.linesReturns
	fake.recordInvocation("Lines", []interface{}{arg1})
	fake.linesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) LinesCallCount() int {
	fake.linesMutex.RLock()
	defer fake.linesMutex.RUnlock()
	return len(fake.linesArgsForCall)
}

func (fake *FakeImpl) LinesCalls(stub func(*tailer.Tailer) <-chan string) {
	fake.linesMutex.Lock()
	defer fake.linesMutex.Unlock()
	fake.LinesStub = stub
}

func (fake *FakeImpl) LinesArgsForCall(i int) *tailer.Tailer {
	fake.linesMutex.RLock()
	defer fake.linesMutex.RUnlock()
	argsForCall := fake.linesArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) LinesArgs() []FakeImplLinesArgs {
	fake.linesMutex.RLock()
	defer fake.linesMutex.RUnlock()
	args := make([]FakeImplLinesArgs, len(fake.linesArgsForCall))
	copy(args, fake.linesArgsForCall)
	return args
}

func (fake *FakeImpl) LinesReturns(result1 <-chan string) {
	fake.linesMutex.Lock()
	defer fake.linesMutex.Unlock()
	fake.LinesStub = nil
	fake.linesReturns = struct {
		result1 <-chan string
	}{result1}
}

func (fake *FakeImpl) LinesReturnsOnCall(i int, result1 <-chan string) {
	fake.linesMutex.Lock()
	defer fake.linesMutex.Unlock()
	fake.LinesStub = nil
	if fake.linesReturnsOnCall == nil {
		fake.linesReturnsOnCall = make(map[int]struct {
			result1 <-chan string
		})
	}
	fake.linesReturnsOnCall[i] = struct {
		result1 <-chan string
	}{result1}
}

func (fake *FakeImpl) Listen(arg1 context.Context, arg2 string, arg3 string) (net.Listener, error) {
	fake.listenMutex.Lock()
	ret, specificReturn := fake.listenReturnsOnCall[len(fake.listenArgsForCall)]
	fake.listenArgsForCall = append(fake.listenArgsForCall, FakeImplListenArgs{arg1, arg2, arg3})
	stub := fake.ListenStub
	fakeReturns := fake.listenReturns
	fake.recordInvocation("Listen", []interface{}{arg1, arg2, arg3})
	fake.listenMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) ListenCallCount() int {
	fake.listenMutex.RLock()
	defer fake.listenMutex.RUnlock()
	return len(fake.listenArgsForCall)
}

func (fake *FakeImpl) ListenCalls(stub func(context.Context, string, string) (net.Listener, error)) {
	fake.listenMutex.Lock()
	defer fake.listenMutex.Unlock()
	fake.ListenStub = stub
}

func (fake *FakeImpl) ListenArgsForCall(i int) (context.Context, string, string) {
	fake.listenMutex.RLock()
	defer fake.listenMutex.RUnlock()
	argsForCall := fake.listenArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeImpl) ListenArgs() []FakeImplListenArgs {
	fake.listenMutex.RLock()
	defer fake.listenMutex.RUnlock()
	args := make([]FakeImplListenArgs, len(fake.listenArgsForCall))
	copy(args, fake.listenArgsForCall)
	return args
}

func (fake *FakeImpl) ListenReturns(result1 net.Listener, result2 error) {
	fake.listenMutex.Lock()
	defer fake.listenMutex.Unlock()
	fake.ListenStub = nil
	fake.listenReturns = struct {
		result1 net.Listener
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ListenReturnsOnCall(i int, result1 net.Listener, result2 error) {
	fake.listenMutex.Lock()
	defer fake.listenMutex.Unlock()
	fake.ListenStub = nil
	if fake.listenReturnsOnCall == nil {
		fake.listenReturnsOnCall = make(map[int]struct {
			result1 net.Listener
			result2 error
		})
	}
	fake.listenReturnsOnCall[i] = struct {
		result1 net.Listener
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) NewForConfig(arg1 *rest.Config) (*kubernetes.Clientset, error) {
	fake.newForConfigMutex.Lock()
	ret, specificReturn := fake.newForConfigReturnsOnCall[len(fake.newForConfigArgsForCall)]
	fake.newForConfigArgsForCall = append(fake.newForConfigArgsForCall, FakeImplNewForConfigArgs{arg1})
	stub := fake.NewForConfigStub
	fakeReturns := fake.newForConfigReturns
	fake.recordInvocation("NewForConfig", []interface{}{arg1})
	fake.newForConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) NewForConfigCallCount() int {
	fake.newForConfigMutex.RLock()
	defer fake.newForConfigMutex.RUnlock()
	return len(fake.newForConfigArgsForCall)
}

func (fake *FakeImpl) NewForConfigCalls(stub func(*rest.Config) (*kubernetes.Clientset, error)) {
	fake.newForConfigMutex.Lock()
	defer fake.newForConfigMutex.Unlock()
	fake.NewForConfigStub = stub
}

func (fake *FakeImpl) NewForConfigArgsForCall(i int) *rest.Config {
	fake.newForConfigMutex.RLock()
	defer fake.newForConfigMutex.RUnlock()
	argsForCall := fake.newForConfigArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) NewForConfigArgs() []FakeImplNewForConfigArgs {
	fake.newForConfigMutex.RLock()
	defer fake.newForConfigMutex.RUnlock()
	args := make([]FakeImplNewForConfigArgs, len(fake.newForConfigArgsForCall))
	copy(args, fake.newForConfigArgsForCall)
	return args
}

func (fake *FakeImpl) NewForConfigReturns(result1 *kubernetes.Clientset, result2 error) {
	fake.newForConfigMutex.Lock()
	defer fake.newForConfigMutex.Unlock()
	fake.NewForConfigStub = nil
	fake.newForConfigReturns = struct {
		result1 *kubernetes.Clientset
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) NewForConfigReturnsOnCall(i int, result1 *kubernetes.Clientset, result2 error) {
	fake.newForConfigMutex.Lock()
	defer fake.newForConfigMutex.Unlock()
	fake.NewForConfigStub = nil
	if fake.newForConfigReturnsOnCall == nil {
		fake.newForConfigReturnsOnCall = make(map[int]struct {
			result1 *kubernetes.Clientset
			result2 error
		})
	}
	fake.newForConfigReturnsOnCall[i] = struct {
		result1 *kubernetes.Clientset
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) PodListerWatcher(arg1 kubernetes.Interface, arg2 string) podindex.ListerWatcher {
	fake.podListerWatcherMutex.Lock()
	ret, specificReturn := fake.podListerWatcherReturnsOnCall[len(fake.podListerWatcherArgsForCall)]
	fake.podListerWatcherArgsForCall = append(fake.podListerWatcherArgsForCall, FakeImplPodListerWatcherArgs{arg1, arg2})
	stub := fake.PodListerWatcherStub
	fakeReturns := fake.podListerWatcherReturns
	fake.recordInvocation("PodListerWatcher", []interface{}{arg1, arg2})
	fake.podListerWatcherMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) PodListerWatcherCallCount() int {
	fake.podListerWatcherMutex.RLock()
	defer fake.podListerWatcherMutex.RUnlock()
	return len(fake.podListerWatcherArgsForCall)
}

func (fake *FakeImpl) PodListerWatcherCalls(stub func(kubernetes.Interface, string) podindex.ListerWatcher) {
	fake.podListerWatcherMutex.Lock()
	defer fake.podListerWatcherMutex.Unlock()
	fake.PodListerWatcherStub = stub
}

func (fake *FakeImpl) PodListerWatcherArgsForCall(i int) (kubernetes.Interface, string) {
	fake.podListerWatcherMutex.RLock()
	defer fake.podListerWatcherMutex.RUnlock()
	argsForCall := fake.podListerWatcherArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeImpl) PodListerWatcherArgs() []FakeImplPodListerWatcherArgs {
	fake.podListerWatcherMutex.RLock()
	defer fake.podListerWatcherMutex.RUnlock()
	args := make([]FakeImplPodListerWatcherArgs, len(fake.podListerWatcherArgsForCall))
	copy(args, fake.podListerWatcherArgsForCall)
	return args
}

func (fake *FakeImpl) PodListerWatcherReturns(result1 podindex.ListerWatcher) {
	fake.podListerWatcherMutex.Lock()
	defer fake.podListerWatcherMutex.Unlock()
	fake.PodListerWatcherStub = nil
	fake.podListerWatcherReturns = struct {
		result1 podindex.ListerWatcher
	}{result1}
}

func (fake *FakeImpl) PodListerWatcherReturnsOnCall(i int, result1 podindex.ListerWatcher) {
	fake.podListerWatcherMutex.Lock()
	defer fake.podListerWatcherMutex.Unlock()
	fake.PodListerWatcherStub = nil
	if fake.podListerWatcherReturnsOnCall == nil {
		fake.podListerWatcherReturnsOnCall = make(map[int]struct {
			result1 podindex.ListerWatcher
		})
	}
	fake.podListerWatcherReturnsOnCall[i] = struct {
		result1 podindex.ListerWatcher
	}{result1}
}

func (fake *FakeImpl) PrintJsonOutput(arg1 io.Writer, arg2 []byte) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.printJsonOutputMutex.Lock()
	fake.printJsonOutputArgsForCall = append(fake.printJsonOutputArgsForCall, FakeImplPrintJsonOutputArgs{arg1, arg2Copy})
	stub := fake.PrintJsonOutputStub
	fake.recordInvocation("PrintJsonOutput", []interface{}{arg1, arg2Copy})
	fake.printJsonOutputMutex.Unlock()
	if stub != nil {
		stub(arg1, arg2)
	}
}

func (fake *FakeImpl) PrintJsonOutputCallCount() int {
	fake.printJsonOutputMutex.RLock()
	defer fake.printJsonOutputMutex.RUnlock()
	return len(fake.printJsonOutputArgsForCall)
}

func (fake *FakeImpl) PrintJsonOutputCalls(stub func(io.Writer, []byte)) {
	fake.printJsonOutputMutex.Lock()
	defer fake.printJsonOutputMutex.Unlock()
	fake.PrintJsonOutputStub = stub
}

func (fake *FakeImpl) PrintJsonOutputArgsForCall(i int) (io.Writer, []byte) {
	fake.printJsonOutputMutex.RLock()
	defer fake.printJsonOutputMutex.RUnlock()
	argsForCall := fake.printJsonOutputArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeImpl) PrintJsonOutputArgs() []FakeImplPrintJsonOutputArgs {
	fake.printJsonOutputMutex.RLock()
	defer fake.printJsonOutputMutex.RUnlock()
	args := make([]FakeImplPrintJsonOutputArgs, len(fake.printJsonOutputArgsForCall))
	copy(args, fake.printJsonOutputArgsForCall)
	return args
}

func (fake *FakeImpl) ProcessStartTime(arg1 int) (time.Duration, error) {
	fake.processStartTimeMutex.Lock()
	ret, specificReturn := fake.processStartTimeReturnsOnCall[len(fake.processStartTimeArgsForCall)]
	fake.processStartTimeArgsForCall = append(fake.processStartTimeArgsForCall, FakeImplProcessStartTimeArgs{arg1})
	stub := fake.ProcessStartTimeStub
	fakeReturns := fake.processStartTimeReturns
	fake.recordInvocation("ProcessStartTime", []interface{}{arg1})
	fake.processStartTimeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) ProcessStartTimeCallCount() int {
	fake.processStartTimeMutex.RLock()
	defer fake.processStartTimeMutex.RUnlock()
	return len(fake.processStartTimeArgsForCall)
}

func (fake *FakeImpl) ProcessStartTimeCalls(stub func(int) (time.Duration, error)) {
	fake.processStartTimeMutex.Lock()
	defer fake.processStartTimeMutex.Unlock()
	fake.ProcessStartTimeStub = stub
}

func (fake *FakeImpl) ProcessStartTimeArgsForCall(i int) int {
	fake.processStartTimeMutex.RLock()
	defer fake.processStartTimeMutex.RUnlock()
	argsForCall := fake.processStartTimeArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) ProcessStartTimeArgs() []FakeImplProcessStartTimeArgs {
	fake.processStartTimeMutex.RLock()
	defer fake.processStartTimeMutex.RUnlock()
	args := make([]FakeImplProcessStartTimeArgs, len(fake.processStartTimeArgsForCall))
	copy(args, fake.processStartTimeArgsForCall)
	return args
}

func (fake *FakeImpl) ProcessStartTimeReturns(result1 time.Duration, result2 error) {
	fake.processStartTimeMutex.Lock()
	defer fake.processStartTimeMutex.Unlock()
	fake.ProcessStartTimeStub = nil
	fake.processStartTimeReturns = struct {
		result1 time.Duration
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ProcessStartTimeReturnsOnCall(i int, result1 time.Duration, result2 error) {
	fake.processStartTimeMutex.Lock()
	defer fake.processStartTimeMutex.Unlock()
	fake.ProcessStartTimeStub = nil
	if fake.processStartTimeReturnsOnCall == nil {
		fake.processStartTimeReturnsOnCall = make(map[int]struct {
			result1 time.Duration
			result2 error
		})
	}
	fake.processStartTimeReturnsOnCall[i] = struct {
		result1 time.Duration
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) Reason(arg1 *tailer.Tailer) error {
	fake.reasonMutex.Lock()
	ret, specificReturn := fake.reasonReturnsOnCall[len(fake.reasonArgsForCall)]
	fake.reasonArgsForCall = append(fake.reasonArgsForCall, FakeImplReasonArgs{arg1})
	stub := fake.ReasonStub
	fakeReturns := fake.reasonReturns
	fake.recordInvocation("Reason", []interface{}{arg1})
	fake.reasonMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) ReasonCallCount() int {
	fake.reasonMutex.RLock()
	defer fake.reasonMutex.RUnlock()
	return len(fake.reasonArgsForCall)
}

func (fake *FakeImpl) ReasonCalls(stub func(*tailer.Tailer) error) {
	fake.reasonMutex.Lock()
	defer fake.reasonMutex.Unlock()
	fake.ReasonStub = stub
}

func (fake *FakeImpl) ReasonArgsForCall(i int) *tailer.Tailer {
	fake.reasonMutex.RLock()
	defer fake.reasonMutex.RUnlock()
	argsForCall := fake.reasonArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) ReasonArgs() []FakeImplReasonArgs {
	fake.reasonMutex.RLock()
	defer fake.reasonMutex.RUnlock()
	args := make([]FakeImplReasonArgs, len(fake.reasonArgsForCall))
	copy(args, fake.reasonArgsForCall)
	return args
}

func (fake *FakeImpl) ReasonReturns(result1 error) {
	fake.reasonMutex.Lock()
	defer fake.reasonMutex.Unlock()
	fake.ReasonStub = nil
	fake.reasonReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) ReasonReturnsOnCall(i int, result1 error) {
	fake.reasonMutex.Lock()
	defer fake.reasonMutex.Unlock()
	fake.ReasonStub = nil
	if fake.reasonReturnsOnCall == nil {
		fake.reasonReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.reasonReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) RemoveAll(arg1 string) error {
	fake.removeAllMutex.Lock()
	ret, specificReturn := fake.removeAllReturnsOnCall[len(fake.removeAllArgsForCall)]
	fake.removeAllArgsForCall = append(fake.removeAllArgsForCall, FakeImplRemoveAllArgs{arg1})
	stub := fake.RemoveAllStub
	fakeReturns := fake.removeAllReturns
	fake.recordInvocation("RemoveAll", []interface{}{arg1})
	fake.removeAllMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) RemoveAllCallCount() int {
	fake.removeAllMutex.RLock()
	defer fake.removeAllMutex.RUnlock()
	return len(fake.removeAllArgsForCall)
}

func (fake *FakeImpl) RemoveAllCalls(stub func(string) error) {
	fake.removeAllMutex.Lock()
	defer fake.removeAllMutex.Unlock()
	fake.RemoveAllStub = stub
}

func (fake *FakeImpl) RemoveAllArgsForCall(i int) string {
	fake.removeAllMutex.RLock()
	defer fake.removeAllMutex.RUnlock()
	argsForCall := fake.removeAllArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) RemoveAllArgs() []FakeImplRemoveAllArgs {
	fake.removeAllMutex.RLock()
	defer fake.removeAllMutex.RUnlock()
	args := make([]FakeImplRemoveAllArgs, len(fake.removeAllArgsForCall))
	copy(args, fake.removeAllArgsForCall)
	return args
}

func (fake *FakeImpl) RemoveAllReturns(result1 error) {
	fake.removeAllMutex.Lock()
	defer fake.removeAllMutex.Unlock()
	fake.RemoveAllStub = nil
	fake.removeAllReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) RemoveAllReturnsOnCall(i int, result1 error) {
	fake.removeAllMutex.Lock()
	defer fake.removeAllMutex.Unlock()
	fake.RemoveAllStub = nil
	if fake.removeAllReturnsOnCall == nil {
		fake.removeAllReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeAllReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) SendMetric(arg1 api_metrics.Metrics_AuditIncClient, arg2 *api_metrics.AuditRequest) error {
	fake.sendMetricMutex.Lock()
	ret, specificReturn := fake.sendMetricReturnsOnCall[len(fake.sendMetricArgsForCall)]
	fake.sendMetricArgsForCall = append(fake.sendMetricArgsForCall, FakeImplSendMetricArgs{arg1, arg2})
	stub := fake.SendMetricStub
	fakeReturns := fake.sendMetricReturns
	fake.recordInvocation("SendMetric", []interface{}{arg1, arg2})
	fake.sendMetricMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) SendMetricCallCount() int {
	fake.sendMetricMutex.RLock()
	defer fake.sendMetricMutex.RUnlock()
	return len(fake.sendMetricArgsForCall)
}

func (fake *FakeImpl) SendMetricCalls(stub func(api_metrics.Metrics_AuditIncClient, *api_metrics.AuditRequest) error) {
	fake.sendMetricMutex.Lock()
	defer fake.sendMetricMutex.Unlock()
	fake.SendMetricStub = stub
}

func (fake *FakeImpl) SendMetricArgsForCall(i int) (api_metrics.Metrics_AuditIncClient, *api_metrics.AuditRequest) {
	fake.sendMetricMutex.RLock()
	defer fake.sendMetricMutex.RUnlock()
	argsForCall := fake.sendMetricArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeImpl) SendMetricArgs() []FakeImplSendMetricArgs {
	fake.sendMetricMutex.RLock()
	defer fake.sendMetricMutex.RUnlock()
	args := make([]FakeImplSendMetricArgs, len(fake.sendMetricArgsForCall))
	copy(args, fake.sendMetricArgsForCall)
	return args
}

func (fake *FakeImpl) SendMetricReturns(result1 error) {
	fake.sendMetricMutex.Lock()
	defer fake.sendMetricMutex.Unlock()
	fake.SendMetricStub = nil
	fake.sendMetricReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) SendMetricReturnsOnCall(i int, result1 error) {
	fake.sendMetricMutex.Lock()
	defer fake.sendMetricMutex.Unlock()
	fake.SendMetricStub = nil
	if fake.sendMetricReturnsOnCall == nil {
		fake.sendMetricReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendMetricReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) Serve(arg1 *grpc.Server, arg2 net.Listener) error {
	fake.serveMutex.Lock()
	ret, specificReturn := fake.serveReturnsOnCall[len(fake.serveArgsForCall)]
	fake.serveArgsForCall = append(fake.serveArgsForCall, FakeImplServeArgs{arg1, arg2})
	stub := fake.ServeStub
	fakeReturns := fake.serveReturns
	fake.recordInvocation("Serve", []interface{}{arg1, arg2})
	fake.serveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) ServeCallCount() int {
	fake.serveMutex.RLock()
	defer fake.serveMutex.RUnlock()
	return len(fake.serveArgsForCall)
}

func (fake *FakeImpl) ServeCalls(stub func(*grpc.Server, net.Listener) error) {
	fake.serveMutex.Lock()
	defer fake.serveMutex.Unlock()
	fake.ServeStub = stub
}

func (fake *FakeImpl) ServeArgsForCall(i int) (*grpc.Server, net.Listener) {
	fake.serveMutex.RLock()
	defer fake.serveMutex.RUnlock()
	argsForCall := fake.serveArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeImpl) ServeArgs() []FakeImplServeArgs {
	fake.serveMutex.RLock()
	defer fake.serveMutex.RUnlock()
	args := make([]FakeImplServeArgs, len(fake.serveArgsForCall))
	copy(args, fake.serveArgsForCall)
	return args
}

func (fake *FakeImpl) ServeReturns(result1 error) {
	fake.serveMutex.Lock()
	defer fake.serveMutex.Unlock()
	fake.ServeStub = nil
	fake.serveReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) ServeReturnsOnCall(i int, result1 error) {
	fake.serveMutex.Lock()
	defer fake.serveMutex.Unlock()
	fake.ServeStub = nil
	if fake.serveReturnsOnCall == nil {
		fake.serveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.serveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) StartTail(arg1 auditsource.AuditLineSource) (chan *types.AuditLine, error) {
	fake.startTailMutex.Lock()
	ret, specificReturn := fake.startTailReturnsOnCall[len(fake.startTailArgsForCall)]
	fake.startTailArgsForCall = append(fake.startTailArgsForCall, FakeImplStartTailArgs{arg1})
	stub := fake.StartTailStub
	fakeReturns := fake.startTailReturns
	fake.recordInvocation("StartTail", []interface{}{arg1})
	fake.startTailMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) StartTailCallCount() int {
	fake.startTailMutex.RLock()
	defer fake.startTailMutex.RUnlock()
	return len(fake.startTailArgsForCall)
}

func (fake *FakeImpl) StartTailCalls(stub func(auditsource.AuditLineSource) (chan *types.AuditLine, error)) {
	fake.startTailMutex.Lock()
	defer fake.startTailMutex.Unlock()
	fake.StartTailStub = stub
}

func (fake *FakeImpl) StartTailArgsForCall(i int) auditsource.AuditLineSource {
	fake.startTailMutex.RLock()
	defer fake.startTailMutex.RUnlock()
	argsForCall := fake.startTailArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) StartTailArgs() []FakeImplStartTailArgs {
	fake.startTailMutex.RLock()
	defer fake.startTailMutex.RUnlock()
	args := make([]FakeImplStartTailArgs, len(fake.startTailArgsForCall))
	copy(args, fake.startTailArgsForCall)
	return args
}

func (fake *FakeImpl) StartTailReturns(result1 chan *types.AuditLine, result2 error) {
	fake.startTailMutex.Lock()
	defer fake.startTailMutex.Unlock()
	fake.StartTailStub = nil
	fake.startTailReturns = struct {
		result1 chan *types.AuditLine
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) StartTailReturnsOnCall(i int, result1 chan *types.AuditLine, result2 error) {
	fake.startTailMutex.Lock()
	defer fake.startTailMutex.Unlock()
	fake.StartTailStub = nil
	if fake.startTailReturnsOnCall == nil {
		fake.startTailReturnsOnCall = make(map[int]struct {
			result1 chan *types.AuditLine
			result2 error
		})
	}
	fake.startTailReturnsOnCall[i] = struct {
		result1 chan *types.AuditLine
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) Stat(arg1 string) (os.FileInfo, error) {
	fake.statMutex.Lock()
	ret, specificReturn := fake.statReturnsOnCall[len(fake.statArgsForCall)]
	fake.statArgsForCall = append(fake.statArgsForCall, FakeImplStatArgs{arg1})
	stub := fake.StatStub
	fakeReturns := fake.statReturns
	fake.recordInvocation("Stat", []interface{}{arg1})
	fake.statMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) StatCallCount() int {
	fake.statMutex.RLock()
	defer fake.statMutex.RUnlock()
	return len(fake.statArgsForCall)
}

func (fake *FakeImpl) StatCalls(stub func(string) (os.FileInfo, error)) {
	fake.statMutex.Lock()
	defer fake.statMutex.Unlock()
	fake.StatStub = stub
}

func (fake *FakeImpl) StatArgsForCall(i int) string {
	fake.statMutex.RLock()
	defer fake.statMutex.RUnlock()
	argsForCall := fake.statArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) StatArgs() []FakeImplStatArgs {
	fake.statMutex.RLock()
	defer fake.statMutex.RUnlock()
	args := make([]FakeImplStatArgs, len(fake.statArgsForCall))
	copy(args, fake.statArgsForCall)
	return args
}

func (fake *FakeImpl) StatReturns(result1 os.FileInfo, result2 error) {
	fake.statMutex.Lock()
	defer fake.statMutex.Unlock()
	fake.StatStub = nil
	fake.statReturns = struct {
		result1 os.FileInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) StatReturnsOnCall(i int, result1 os.FileInfo, result2 error) {
	fake.statMutex.Lock()
	defer fake.statMutex.Unlock()
	fake.StatStub = nil
	if fake.statReturnsOnCall == nil {
		fake.statReturnsOnCall = make(map[int]struct {
			result1 os.FileInfo
			result2 error
		})
	}
	fake.statReturnsOnCall[i] = struct {
		result1 os.FileInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) StopTail(arg1 *tailer.Tailer) {
	fake.stopTailMutex.Lock()
	fake.stopTailArgsForCall = append(fake.stopTailArgsForCall, FakeImplStopTailArgs{arg1})
	stub := fake.StopTailStub
	fake.recordInvocation("StopTail", []interface{}{arg1})
	fake.stopTailMutex.Unlock()
	if stub != nil {
		stub(arg1)
	}
}

func (fake *FakeImpl) StopTailCallCount() int {
	fake.stopTailMutex.RLock()
	defer fake.stopTailMutex.RUnlock()
	return len(fake.stopTailArgsForCall)
}

func (fake *FakeImpl) StopTailCalls(stub func(*tailer.Tailer)) {
	fake.stopTailMutex.Lock()
	defer fake.stopTailMutex.Unlock()
	fake.StopTailStub = stub
}

func (fake *FakeImpl) StopTailArgsForCall(i int) *tailer.Tailer {
	fake.stopTailMutex.RLock()
	defer fake.stopTailMutex.RUnlock()
	argsForCall := fake.stopTailArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) StopTailArgs() []FakeImplStopTailArgs {
	fake.stopTailMutex.RLock()
	defer fake.stopTailMutex.RUnlock()
	args := make([]FakeImplStopTailArgs, len(fake.stopTailArgsForCall))
	copy(args, fake.stopTailArgsForCall)
	return args
}

func (fake *FakeImpl) TailErr(arg1 auditsource.AuditLineSource) error {
	fake.tailErrMutex.Lock()
	ret, specificReturn := fake.tailErrReturnsOnCall[len(fake.tailErrArgsForCall)]
	fake.tailErrArgsForCall = append(fake.tailErrArgsForCall, FakeImplTailErrArgs{arg1})
	stub := fake.TailErrStub
	fakeReturns := fake.tailErrReturns
	fake.recordInvocation("TailErr", []interface{}{arg1})
	fake.tailErrMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) TailErrCallCount() int {
	fake.tailErrMutex.RLock()
	defer fake.tailErrMutex.RUnlock()
	return len(fake.tailErrArgsForCall)
}

func (fake *FakeImpl) TailErrCalls(stub func(auditsource.AuditLineSource) error) {
	fake.tailErrMutex.Lock()
	defer fake.tailErrMutex.Unlock()
	fake.TailErrStub = stub
}

func (fake *FakeImpl) TailErrArgsForCall(i int) auditsource.AuditLineSource {
	fake.tailErrMutex.RLock()
	defer fake.tailErrMutex.RUnlock()
	argsForCall := fake.tailErrArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) TailErrArgs() []FakeImplTailErrArgs {
	fake.tailErrMutex.RLock()
	defer fake.tailErrMutex.RUnlock()
	args := make([]FakeImplTailErrArgs, len(fake.tailErrArgsForCall))
	copy(args, fake.tailErrArgsForCall)
	return args
}

func (fake *FakeImpl) TailErrReturns(result1 error) {
	fake.tailErrMutex.Lock()
	defer fake.tailErrMutex.Unlock()
	fake.TailErrStub = nil
	fake.tailErrReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) TailErrReturnsOnCall(i int, result1 error) {
	fake.tailErrMutex.Lock()
	defer fake.tailErrMutex.Unlock()
	fake.TailErrStub = nil
	if fake.tailErrReturnsOnCall == nil {
		fake.tailErrReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.tailErrReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) TailFile(arg1 string, arg2 tailer.Config) (*tailer.Tailer, error) {
	fake.tailFileMutex.Lock()
	ret, specificReturn := fake.tailFileReturnsOnCall[len(fake.tailFileArgsForCall)]
	fake.tailFileArgsForCall = append(fake.tailFileArgsForCall, FakeImplTailFileArgs{arg1, arg2})
	stub := fake.TailFileStub
	fakeReturns := fake.tailFileReturns
	fake.recordInvocation("TailFile", []interface{}{arg1, arg2})
	fake.tailFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) TailFileCallCount() int {
	fake.tailFileMutex.RLock()
	defer fake.tailFileMutex.RUnlock()
	return len(fake.tailFileArgsForCall)
}

func (fake *FakeImpl) TailFileCalls(stub func(string, tailer.Config) (*tailer.Tailer, error)) {
	fake.tailFileMutex.Lock()
	defer fake.tailFileMutex.Unlock()
	fake.TailFileStub = stub
}

func (fake *FakeImpl) TailFileArgsForCall(i int) (string, tailer.Config) {
	fake.tailFileMutex.RLock()
	defer fake.tailFileMutex.RUnlock()
	argsForCall := fake.tailFileArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeImpl) TailFileArgs() []FakeImplTailFileArgs {
	fake.tailFileMutex.RLock()
	defer fake.tailFileMutex.RUnlock()
	args := make([]FakeImplTailFileArgs, len(fake.tailFileArgsForCall))
	copy(args, fake.tailFileArgsForCall)
	return args
}

func (fake *FakeImpl) TailFileReturns(result1 *tailer.Tailer, result2 error) {
	fake.tailFileMutex.Lock()
	defer fake.tailFileMutex.Unlock()
	fake.TailFileStub = nil
	fake.tailFileReturns = struct {
		result1 *tailer.Tailer
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) TailFileReturnsOnCall(i int, result1 *tailer.Tailer, result2 error) {
	fake.tailFileMutex.Lock()
	defer fake.tailFileMutex.Unlock()
	fake.TailFileStub = nil
	if fake.tailFileReturnsOnCall == nil {
		fake.tailFileReturnsOnCall = make(map[int]struct {
			result1 *tailer.Tailer
			result2 error
		})
	}
	fake.tailFileReturnsOnCall[i] = struct {
		result1 *tailer.Tailer
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) Uptime() (time.Duration, error) {
	fake.uptimeMutex.Lock()
	ret, specificReturn := fake.uptimeReturnsOnCall[len(fake.uptimeArgsForCall)]
	fake.uptimeArgsForCall = append(fake.uptimeArgsForCall, struct{}{})
	stub := fake.UptimeStub
	fakeReturns := fake.uptimeReturns
	fake.recordInvocation("Uptime", []interface{}{})
	fake.uptimeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) UptimeCallCount() int {
	fake.uptimeMutex.RLock()
	defer fake.uptimeMutex.RUnlock()
	return len(fake.uptimeArgsForCall)
}

func (fake *FakeImpl) UptimeCalls(stub func() (time.Duration, error)) {
	fake.uptimeMutex.Lock()
	defer fake.uptimeMutex.Unlock()
	fake.UptimeStub = stub
}

func (fake *FakeImpl) UptimeReturns(result1 time.Duration, result2 error) {
	fake.uptimeMutex.Lock()
	defer fake.uptimeMutex.Unlock()
	fake.UptimeStub = nil
	fake.uptimeReturns = struct {
		result1 time.Duration
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) UptimeReturnsOnCall(i int, result1 time.Duration, result2 error) {
	fake.uptimeMutex.Lock()
	defer fake.uptimeMutex.Unlock()
	fake.UptimeStub = nil
	if fake.uptimeReturnsOnCall == nil {
		fake.uptimeReturnsOnCall = make(map[int]struct {
			result1 time.Duration
			result2 error
		})
	}
	fake.uptimeReturnsOnCall[i] = struct {
		result1 time.Duration
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeImpl) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeImpl) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
