apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
  labels:
    app: security-profiles-operator
  name: metrics-token
type: kubernetes.io/service-account-token
