apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: spo-metrics-client
  labels:
    app: security-profiles-operator
  name: spo-metrics-client-token
type: kubernetes.io/service-account-token
