apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: security-profiles-operator
  name: spo-metrics-client
rules:
- nonResourceURLs:
  - /metrics
  - /metrics-spod
  verbs:
  - get
