apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: security-profiles-operator
  name: spo-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spo-webhook
subjects:
- kind: ServiceAccount
  name: spo-webhook
