apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: security-profiles-operator
  name: spod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spod
subjects:
- kind: ServiceAccount
  name: spod
  namespace: security-profiles-operator
