apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy

images:
- name: security-profiles-operator
  # newName: us-central1-docker.pkg.dev/k8s-staging-images/sp-operator/security-profiles-operator
  # newTag: latest
  # For images to be released:
  newName: registry.k8s.io/security-profiles-operator/security-profiles-operator
  newTag: v1.1.0


resources:
- manager_deployment.yaml
labels:
- includeSelectors: true
  pairs:
    app: security-profiles-operator
