apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: security-profiles-operator
  labels:
    security-profiles-operator/config: ""
data:
  SPOdImagePullPolicy: Always
  EnableSelinux: "false"
