---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-profiles-operator
rules:
- apiGroups:
  - ""
  resourceNames:
  - security-profiles-operator-profile
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - spo-mutating-webhook-configuration
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingadmissionpolicies
  - validatingadmissionpolicybindings
  - validatingwebhookconfigurations
  verbs:
  - create
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - spo-recording-profiles
  resources:
  - validatingadmissionpolicies
  - validatingadmissionpolicybindings
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - spo-validating-webhook-configuration
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - config.openshift.io
  resources:
  - apiservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators
  verbs:
  - get
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - apparmorprofiles
  - seccompprofiles
  - selinuxprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - apparmorprofiles/finalizers
  - apparmorprofiles/status
  - profilebindings/finalizers
  - profilebindings/status
  - profilerecordings/finalizers
  - profilerecordings/status
  - rawselinuxprofiles/finalizers
  - rawselinuxprofiles/status
  - seccompprofiles/finalizers
  - seccompprofiles/status
  - securityprofilesoperatordaemons/finalizers
  - securityprofilesoperatordaemons/status
  - selinuxprofiles/finalizers
  - selinuxprofiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - profilebindings
  - profilerecordings
  - rawselinuxprofiles
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - securityprofilenodestatuses
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - securityprofilesoperatordaemons
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: security-profiles-operator
  namespace: security-profiles-operator
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - restricted-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spod
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - spo-mutating-webhook-configuration
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - config.openshift.io
  resources:
  - apiservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators
  verbs:
  - get
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - apparmorprofiles
  - seccompprofiles
  - selinuxprofiles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - apparmorprofiles/finalizers
  - rawselinuxprofiles/finalizers
  - seccompprofiles/finalizers
  - securityprofilenodestatuses/status
  - selinuxprofiles/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - profilerecordings
  - rawselinuxprofiles
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - securityprofilenodestatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - securityprofilesoperatordaemons
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spod
  namespace: security-profiles-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spo-webhook
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - config.openshift.io
  resources:
  - apiservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators
  verbs:
  - get
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - apparmorprofiles
  - profilebindings
  - profilerecordings
  - seccompprofiles
  - selinuxprofiles
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spo-webhook
  namespace: security-profiles-operator
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - security-profiles-operator-webhook-lock
  resources:
  - leases
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - securityprofilesoperatordaemons
  verbs:
  - get
- apiGroups:
  - security.openshift.io
  resourceNames:
  - restricted-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
