---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: security-profiles-operator
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    name: security-profiles-operator-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: security-profiles-operator
spec:
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: spod
