#!/usr/bin/env bash
set -euo pipefail

# assume a Debian based golang image
apt-get update
apt-get install -y \
    libapparmor-dev \
    libseccomp-dev \
    libzstd-dev

./hack/install-libelf.sh
./hack/install-libbpf.sh
