#!/usr/bin/env bash
set -euo pipefail

# assume a Debian based golang image
apt-get update
apt-get install -y \
    libapparmor-dev \
    libelf-dev \
    libseccomp-dev \
    libzstd-dev \
    lsb-release

./hack/install-libbpf.sh
