#!/usr/bin/env bash
set -euo pipefail

./hack/install-packages

CLANG_VERSION=14
apt-get install -y software-properties-common
curl -sSfL --retry 5 --retry-delay 3 https://apt.llvm.org/llvm.sh | bash -s -- $CLANG_VERSION all
ln -sf /usr/bin/clang-format-$CLANG_VERSION /usr/bin/clang-format

make verify
