#!/usr/bin/env bash
set -euo pipefail

BTFHUB_COMMIT=807c5c41894143513100ac58fa07e72df221baa1
TEMP_DIR=$(mktemp -u)
ROOT_DIR=$(git rev-parse --show-toplevel)
BPF_OBJECT="$ROOT_DIR/build/recorder.bpf.o"
BTF_DIR="$ROOT_DIR/internal/pkg/daemon/bpfrecorder/btf"

rm -rf "$BTF_DIR"
git clone https://github.com/aquasecurity/btfhub "$TEMP_DIR"

pushd "$TEMP_DIR"/tools
git checkout $BTFHUB_COMMIT

bash ./extract.sh -a x86_64
bash ./extract.sh -a arm64

bash ./btfgen.sh -a x86_64 -o "$BPF_OBJECT".amd64
bash ./btfgen.sh -a arm64 -o "$BPF_OBJECT".arm64

OUTPUT=../custom-archive
rm -rf $OUTPUT/.gitignore
cp -R $OUTPUT "$BTF_DIR"
popd

rm -rf "$TEMP_DIR"
go run ./internal/pkg/daemon/bpfrecorder/generate
