flowchart LR
    U(User)
    subgraph Node
        FS1[(FileSystem)]
        P1[Pod]
        D1[Daemon]
        R1[eBpfRecorder]
        E1[LogEnricher]
        J1[JsonEnricher]
        M1[Metrics]

        D1 -.->|install profile|FS1
        P1 -.-> |use profile|FS1
        D1 --> |gRPC: record profile| R1
        D1 --> |gRPC: record profile| E1
        D1 --> |gRPC: update metric| M1
        R1 --> |record profile| P1
        E1 --> |record profile| P1
        J1 --> |audit in-pod activity| P1
        D1 -->|get/watch| P1
    end

    Recording[/ProfileRecording<br> CR/]
    Config[/SPOD CR/]
    Profile[/SeccompProfile CR<br>SelinuxProfile CR<br>RawSelinuxProfile CR<br>AppArmorProfile CR/]
    NodeStatus[/SecurityProfileNodeStatus<br> CR/]
    Binding[/ProfileBinding CR/]
    W[Mutating Webhooks]
    VW[Validating Webhook]
    M[Manager]
    D[Daemonset]

    U -->|deploy|M
    U -->|update|Config
    U -->|create|Recording
    U -->|create|Binding
    U -->|create/update/get/delete|Profile

    W -.->|watch| Recording
    W -->|add annotations| P1

    M -.->|watch|Config
    M -->|create/update|D
    M -->|create/update<br>unless statically configured|W
    M -->|create/update<br>unless statically configured|VW
    M -->|aggregate node states|Profile
    M -.->|watch|NodeStatus

    D -.->|start|D1
    D1 -.->|watch|Config
    D1-.->|get/update|Recording
    D1 -->|create/update/watch|Profile
    D1 -->|create/update|NodeStatus

    W-->|get|Binding
    W-->|get|Profile
    W-->|add SecurityContext<br>when profile binding is defined|P1
    VW-->|validate|Profile

  classDef green fill:#9f6,stroke:#333,stroke-width:2px;
  classDef orange fill:#f96,stroke:#333,stroke-width:4px;
  classDef purple fill:#f9f,stroke:#333,stroke-width:4px
  class W,VW,M,D,D1,R1,E1,J1,M1 green
  class U orange
  class P1 purple
