/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package clidocs

import (
	"bytes"
	"slices"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/urfave/cli/v2"
)

var testEnv = []EnvVar{{Name: "RUNTIME_VAR", Description: "read at runtime"}}

func newTestApp() *cli.App {
	app := cli.NewApp()
	app.Name = "tool"
	app.Usage = "a test tool"
	app.UsageText = "tool [flags]\n# not a heading"
	app.Flags = []cli.Flag{
		&cli.IntFlag{Name: "level", Value: 1, Usage: "the level", EnvVars: []string{"TOOL_LEVEL"}},
	}
	app.Commands = []*cli.Command{
		{
			Name:  "run",
			Usage: "run it",
			Flags: []cli.Flag{
				&cli.BoolFlag{
					Name:    "fast",
					Usage:   "go fast",
					EnvVars: []string{"TOOL_FAST", "FAST"},
				},
				&cli.StringFlag{Name: "secret", Hidden: true, EnvVars: []string{"TOOL_SECRET"}},
				&cli.BoolFlag{Name: "enabled", Usage: "enable it", Value: true},
				&cli.BoolFlag{
					Name:        "documented",
					Usage:       "document it",
					Value:       true,
					DefaultText: "on",
				},
				&cli.BoolFlag{
					Name:               "quiet",
					Usage:              "do not tell",
					Value:              true,
					DisableDefaultText: true,
				},
			},
			Subcommands: []*cli.Command{
				{
					Name:  "sub",
					Usage: "a subcommand",
					Flags: []cli.Flag{
						&cli.StringFlag{
							Name:    "name",
							Usage:   "the name",
							EnvVars: []string{"TOOL_NAME"},
						},
					},
				},
			},
		},
		{
			Name:   "hidden",
			Hidden: true,
			Flags:  []cli.Flag{&cli.StringFlag{Name: "x", EnvVars: []string{"TOOL_HIDDEN"}}},
		},
		Command(newTestApp, testEnv),
	}

	return app
}

func TestMarkdown(t *testing.T) {
	t.Parallel()

	doc, err := Markdown(newTestApp(), testEnv)
	require.NoError(t, err)

	require.Contains(t, doc, "<!-- Code generated by \"tool docs\", DO NOT EDIT. -->\n\n"+
		"# tool command line reference\n\n## NAME\n\ntool - a test tool\n")
	require.Contains(t, doc, "\n## GLOBAL OPTIONS\n")
	require.Contains(t, doc, "\n### run\n")
	require.Contains(t, doc, "\n#### sub\n")
	// Lines in code blocks are no headings.
	require.Contains(t, doc, "\n# not a heading\n")
	require.NotContains(t, doc, "\n\n\n")
	require.NotContains(t, doc, "hidden")
	require.NotContains(t, doc, "### docs")

	require.Contains(t, doc, "\n## ENVIRONMENT VARIABLES\n")
	require.Contains(t, doc, "| `TOOL_LEVEL` | `--level` | (global) |\n")
	require.Contains(t, doc, "| `TOOL_FAST` | `--fast` | run |\n| `FAST` | `--fast` | run |\n")
	require.Contains(t, doc, "| `TOOL_NAME` | `--name` | run sub |\n")
	require.Contains(t, doc, "| `RUNTIME_VAR` | read at runtime |\n")
	require.NotContains(t, doc, "TOOL_SECRET")
	require.NotContains(t, doc, "TOOL_HIDDEN")

	// Boolean flags show their default if it is true or has a default text.
	require.Contains(t, doc, "\n**--enabled**: enable it (default: true)\n")
	require.Contains(t, doc, "\n**--documented**: document it (default: on)\n")
	require.Contains(t, doc, "\n**--fast**: go fast\n")
	require.Contains(t, doc, "\n**--quiet**: do not tell\n")
}

func TestMarkdownRestoresBoolFlags(t *testing.T) {
	t.Parallel()

	app := newTestApp()
	flags := slices.Clone(app.Commands[0].Flags)

	_, err := Markdown(app, nil)
	require.NoError(t, err)
	require.Equal(t, flags, app.Commands[0].Flags)
}

func TestMarkdownWithoutEnvVars(t *testing.T) {
	t.Parallel()

	app := cli.NewApp()
	app.Name = "plain"

	doc, err := Markdown(app, nil)
	require.NoError(t, err)
	require.NotContains(t, doc, "ENVIRONMENT VARIABLES")
}

func TestCommand(t *testing.T) {
	// The environment must not end up in the documented defaults.
	t.Setenv("TOOL_LEVEL", "42")

	var out bytes.Buffer

	app := newTestApp()
	app.Writer = &out

	require.NoError(t, app.Run([]string{"tool", CommandName}))

	want, err := Markdown(newTestApp(), testEnv)
	require.NoError(t, err)
	require.Equal(t, want, out.String())
	require.Contains(t, out.String(), "(default: 1)")
	require.NotContains(t, out.String(), "42")
}
