---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: security-profiles-operator

resources:
  - nginx-1.19.1.yaml

generatorOptions:
  disableNameSuffixHash: true
