---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: security-profiles-operator

resources:
  - crds/profilebinding.yaml
  - crds/profilerecording.yaml
  - crds/seccompprofile.yaml
  - crds/securityprofilenodestatus.yaml
  - crds/securityprofilesoperatordaemon.yaml
  - crds/selinuxpolicy.yaml
  - crds/apparmorprofile.yaml

generatorOptions:
  disableNameSuffixHash: true
