---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: AppArmorProfile
metadata:
  name: test-profile
  annotations:
    description: Block writing to any files in the disk.
spec:
  abstract:
    filesystem: # Denies all file write and read access.
      readOnlyPaths: []
      writeOnlyPaths: []
      readWritePaths: []
