apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: AppArmorProfile
metadata:
  labels:
    spo.x-k8s.io/container-id: test-pod
    spo.x-k8s.io/profile-id: AppArmorProfile-test-recording-test-pod
    spo.x-k8s.io/recording-id: test-recording
  name: test-recording-test-pod
  namespace: security-profiles-operator
spec:
  complainMode: true
  abstract:
    filesystem:
      readOnlyPaths: []
      readWritePaths: []
      writeOnlyPaths: []
  disabled: false
