---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SeccompProfile
metadata:
  name: crun-v0.17
spec:
  defaultAction: SCMP_ACT_ERRNO
  architectures:
  - SCMP_ARCH_X86_64
  syscalls:
  - action: SCMP_ACT_ALLOW
    names:
    - arch_prctl
    - capset
    - close
    - execve
    - exit_group
    - prctl
    - read
    - rt_sigaction
    - rt_sigprocmask
    - select
    - set_tid_address
    - setresgid
    - setresuid
    - write
