---
apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  name: runc-v1.2.3
spec:
  defaultAction: SCMP_ACT_ERRNO
  architectures:
    - SCMP_ARCH_X86_64
  syscalls:
    - action: SCMP_ACT_ALLOW
      names:
        - arch_prctl
        - brk
        - capget
        - capset
        - chdir
        - close
        - close_range
        - epoll_ctl
        - epoll_pwait
        - execve
        - exit_group
        - faccessat2
        - fcntl
        - fstat
        - fstatfs
        - futex
        - getcwd
        - getdents64
        - getpid
        - getppid
        - getuid
        - mmap
        - mprotect
        - nanosleep
        - newfstatat
        - openat
        - prctl
        - read
        - recvfrom
        - rt_sigreturn
        - sched_yield
        - set_tid_address
        - setgid
        - setgroups
        - setuid
        - tgkill
        - write
