---
apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  name: runc-v1.1.11
spec:
  defaultAction: SCMP_ACT_ERRNO
  architectures:
    - SCMP_ARCH_X86_64
  syscalls:
    - action: SCMP_ACT_ALLOW
      names:
        - arch_prctl
        - brk
        - capget
        - capset
        - chdir
        - clone
        - close
        - dup3
        - epoll_create1
        - epoll_ctl
        - epoll_pwait
        - execve
        - exit_group
        - faccessat2
        - fchdir
        - fchmodat
        - fchownat
        - fcntl
        - fstat
        - fstatfs
        - futex
        - getdents64
        - getpid
        - getppid
        - getrlimit
        - gettid
        - getuid
        - keyctl
        - madvise
        - mkdirat
        - mknodat
        - mmap
        - mount
        - mprotect
        - munmap
        - nanosleep
        - newfstatat
        - openat
        - openat2
        - pipe2
        - pivot_root
        - prctl
        - pread64
        - read
        - readlinkat
        - rt_sigaction
        - rt_sigprocmask
        - rt_sigreturn
        - sched_getaffinity
        - sched_yield
        - seccomp
        - set_robust_list
        - set_tid_address
        - setgid
        - setgroups
        - sethostname
        - setsid
        - setuid
        - sigaltstack
        - statfs
        - symlinkat
        - tgkill
        - umask
        - umount2
        - unlinkat
        - unshare
        - utimensat
        - write
