---
apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  name: runc-v1.2.3
spec:
  defaultAction: SCMP_ACT_ERRNO
  architectures:
    - SCMP_ARCH_X86_64
  syscalls:
    - action: SCMP_ACT_ALLOW
      names:
        - arch_prctl
        - brk
        - close
        - epoll_ctl
        - epoll_pwait
        - execve
        - exit
        - exit_group
        - faccessat2
        - fcntl
        - fstatfs
        - futex
        - getdents64
        - getpid
        - getuid
        - madvise
        - mmap
        - mprotect
        - nanosleep
        - newfstatat
        - openat
        - rt_sigprocmask
        - rt_sigreturn
        - sched_yield
        - set_tid_address
        - sigaltstack
        - tgkill
        - write
