---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SeccompProfile
metadata:
  name: runc-v1.0.0-rc92
spec:
  defaultAction: SCMP_ACT_ERRNO
  architectures:
  - SCMP_ARCH_X86_64
  syscalls:
  - action: SCMP_ACT_ALLOW
    names:
    - capget
    - capset
    - chdir
    - close
    - epoll_ctl
    - epoll_pwait
    - execve
    - fchown
    - fcntl
    - fstat
    - fstatfs
    - futex
    - getdents64
    - getpid
    - getppid
    - nanosleep
    - newfstatat
    - openat
    - prctl
    - read
    - sched_yield
    - setgid
    - setgroups
    - setuid
    - write
