---
apiVersion: security-profiles-operator.x-k8s.io/v1beta1
kind: SeccompProfile
metadata:
  name: crun-v1.21
spec:
  defaultAction: SCMP_ACT_ERRNO
  architectures:
    - SCMP_ARCH_X86_64
  syscalls:
    - action: SCMP_ACT_ALLOW
      names:
        - access
        - arch_prctl
        - brk
        - capset
        - chdir
        - chmod
        - chown
        - close
        - close_range
        - dup2
        - execve
        - exit_group
        - fchdir
        - fchown
        - fstat
        - fstatfs
        - getcwd
        - getegid
        - geteuid
        - getgid
        - getuid
        - ioctl
        - lseek
        - mkdirat
        - mknodat
        - mmap
        - mount
        - mprotect
        - nanosleep
        - newfstatat
        - openat
        - openat2
        - pivot_root
        - prctl
        - pselect6
        - read
        - readlink
        - rt_sigaction
        - rt_sigprocmask
        - set_tid_address
        - setgroups
        - sethostname
        - setns
        - setresgid
        - setresuid
        - setsid
        - statfs
        - statx
        - symlinkat
        - umask
        - umount2
        - unshare
        - write
