---
apiVersion: security-profiles-operator.x-k8s.io/v1
kind: SeccompProfile
metadata:
  name: crun-v1.29.1
spec:
  defaultAction: SCMP_ACT_ERRNO
  architectures:
    - SCMP_ARCH_X86_64
  syscalls:
    - action: SCMP_ACT_ALLOW
      names:
        - access
        - arch_prctl
        - brk
        - capset
        - chdir
        - close
        - close_range
        - dup
        - dup2
        - execve
        - exit_group
        - fchdir
        - fchmodat
        - fchown
        - fchownat
        - fsconfig
        - fsmount
        - fsopen
        - fstat
        - fstatfs
        - getcwd
        - getegid
        - geteuid
        - getgid
        - getuid
        - ioctl
        - lseek
        - mkdirat
        - mknodat
        - mmap
        - mount
        - mount_setattr
        - move_mount
        - mprotect
        - nanosleep
        - newfstatat
        - open_tree
        - openat
        - openat2
        - pivot_root
        - prctl
        - pselect6
        - read
        - rt_sigaction
        - rt_sigprocmask
        - set_tid_address
        - sethostname
        - setresgid
        - setresuid
        - setsid
        - statx
        - symlinkat
        - umask
        - umount2
        - write
