---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SecurityProfilesOperatorDaemon
metadata:
  name: spod
  namespace: security-profiles-operator
spec:
  selinux:
    enable: false
  enricher:
    enableLogEnricher: false
  enableAppArmor: false

