apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: 'localhost/operator/test-profile/profile-allow.json'
spec:
  containers:
  - name: test-container
    image: nginx