apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    # Use the default nginx profile
    seccomp.security.alpha.kubernetes.io/pod: 'localhost/operator/security-profiles-operator/nginx-1.19.1.json'
    # Or one example within this directory
    # Please note the syntax:
    # `localhost/operator/{namespace}/{profile-name}`
    # seccomp.security.alpha.kubernetes.io/pod: 'localhost/operator/default/profile-allow-unsafe.json'
spec:
  containers:
  - name: test-container
    # Use the seccomp field for Kubernetes versions > v1.19.0
    # securityContext:
      # seccompProfile:
        # type: Localhost
        # localhostProfile: operator/security-profiles-operator/nginx-1.19.1.json
    image: docker.io/nginx:1.19.1
