apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    # Use the seccomp field for Kubernetes versions > v1.19.0
    # securityContext:
      # seccompProfile:
        # type: Localhost
        # localhostProfile: operator/security-profiles-operator/nginx-1.23.2.json
    image: nginx:1.23.2
