apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: nginx:1.23.2
    securityContext:
      seccompProfile:
        type: Localhost
        # Installed from the profile-complain-unsafe SeccompProfile of
        # examples/seccompprofile.yaml.
        localhostProfile: operator/profile-complain-unsafe.json
