---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SeccompProfile
metadata:
  name: profile-block
spec:
  defaultAction: "SCMP_ACT_ERRNO"
---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SeccompProfile
metadata:
  name: profile-complain
spec:
  defaultAction: "SCMP_ACT_LOG"
---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SeccompProfile
metadata:
  name: profile-allow
spec:
  defaultAction: "SCMP_ACT_ALLOW"
