apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: AppArmorProfile
metadata:
  labels:
    spo.x-k8s.io/container-id: bpf-recorder
  name: bpfrecorder-apparmor
  namespace: security-profiles-operator
spec:
  abstract:
    capability:
      allowedCapabilities:
      - bpf
      - chown
      - perfmon
      - sys_resource
    executable:
      allowedExecutables:
      - /security-profiles-operator
    filesystem:
      readOnlyPaths:
      - /proc/@{pid}/cgroup
      - /proc/@{pid}/maps
      - /proc/sys/net/core/somaxconn
      - /sys/devices/kprobe/type
      - /sys/devices/system/cpu/online
      - /sys/fs/bpf/
      - /sys/kernel/btf/vmlinux
      - /sys/kernel/debug/tracing/events/**/id
      - /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
      - /sys/kernel/security/lsm
      - /var/run/secrets/kubernetes.io/serviceaccount/**
      - /var/run/secrets/kubernetes.io/serviceaccount/**
      readWritePaths:
      - "ptrace (read),\n# ugly template injection hack"
      - /var/run/grpc/bpf-recorder.sock
    network:
      allowedProtocols:
        allowTcp: true
        allowUdp: true
  disabled: false
