apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: AppArmorProfile
metadata:
  labels:
    spo.x-k8s.io/container-id: bpf-recorder
  name: bpfrecorder-apparmor
  namespace: security-profiles-operator
spec:
  abstract:
    capability:
      allowedCapabilities:
      - bpf
      - chown
      - perfmon
      - sys_resource
    executable:
      allowedExecutables:
      - /security-profiles-operator
    filesystem:
      readOnlyPaths:
      - /proc/@{pid}/cgroup
      - /proc/@{pid}/maps
      - /proc/sys/net/core/somaxconn
      - /sys/devices/kprobe/type
      - /sys/devices/system/cpu/online
      - /sys/fs/bpf/**
      - /sys/kernel/btf/vmlinux
      - /sys/kernel/debug/tracing/events/raw_syscalls/sys_enter/id
      - /sys/kernel/debug/tracing/events/sched/sched_process_exec/id
      - /sys/kernel/debug/tracing/events/sched/sched_process_exit/id
      - /sys/kernel/debug/tracing/events/syscalls/sys_enter_execve/id
      - /sys/kernel/debug/tracing/events/syscalls/sys_enter_getgid/id
      - /sys/kernel/debug/tracing/events/syscalls/sys_enter_prctl/id
      - /sys/kernel/debug/tracing/events/syscalls/sys_enter_socket/id
      - /sys/kernel/debug/tracing/events/syscalls/sys_exit_clone/id
      - /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
      - /sys/kernel/security/lsm
      - /var/run/secrets/kubernetes.io/serviceaccount/**
      - /var/run/secrets/kubernetes.io/serviceaccount/**
      readWritePaths:
      - /var/run/grpc/bpf-recorder.sock
    network:
      allowedProtocols:
        allowTcp: true
        allowUdp: true
  disabled: false
