apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: AppArmorProfile
metadata:
  labels:
    spo.x-k8s.io/container-id: security-profiles-operator
  name: spo-apparmor
  namespace: security-profiles-operator
spec:
  abstract:
    capability:
      allowedCapabilities:
      - dac_override
      - dac_read_search
      - mac_admin
      - sys_admin
      - sys_chroot
    executable:
      allowedExecutables:
      - /security-profiles-operator
      - /usr/sbin/apparmor_parser
      - /sbin/apparmor_parser
    filesystem:
      readOnlyPaths:
      - /  # workaround for apparmor bug
      - /etc/apparmor/parser.conf
      - /proc/@{pid}/maps
      - /proc/@{pid}/mounts
      - /proc/sys/kernel/osrelease
      - /proc/sys/net/core/somaxconn
      - /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
      - /var/run/secrets/kubernetes.io/serviceaccount/**
      - /var/run/secrets/metrics/**
      - /sys/module/apparmor/parameters/enabled
      - /sys/devices/system/cpu/possible
      readWritePaths:
      - "ptrace (read),  # ugly template injection hack"
      - /var/run/grpc/metrics.sock
      - /tmp/aa_profile_bin_*
      - /etc/apparmor.d/**
      - /sys/kernel/security/apparmor/
      - /sys/kernel/security/apparmor/**
      - /var/lib/kubelet/seccomp/operator/**
    network:
      allowedProtocols:
        allowTcp: true
        allowUdp: true
  disabled: false
