apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: AppArmorProfile
metadata:
  labels:
    spo.x-k8s.io/container-id: security-profiles-operator
  name: spo-apparmor
  namespace: security-profiles-operator
spec:
  abstract:
    capability:
      allowedCapabilities:
      - dac_override
      - dac_read_search
      - sys_admin
      - sys_chroot
    executable:
      allowedExecutables:
      - /security-profiles-operator
    filesystem:
      readOnlyPaths:
      - /  # workaround for apparmor bug
      - /proc/@{pid}/maps
      - /proc/sys/net/core/somaxconn
      - /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
      - /var/lib/kubelet/seccomp/operator/security-profiles-operator/spo-recording-seccomp-bpf-recorder.json
      - /var/lib/kubelet/seccomp/operator/security-profiles-operator/spo-recording-seccomp-security-profiles-operator.json
      - /var/run/secrets/kubernetes.io/serviceaccount/**
      - /var/run/secrets/kubernetes.io/serviceaccount/**
      - /var/run/secrets/metrics/**
      - /var/run/secrets/metrics/**
      - /sys/module/apparmor/parameters/enabled
      writeOnlyPaths:
      - /etc/apparmor.d/**
      - /tmp/aa_profile_bin_*
      readWritePaths:
      - "ptrace (read),  # ugly template injection hack"
      - /var/run/grpc/metrics.sock
    network:
      allowedProtocols:
        allowTcp: true
        allowUdp: true
  disabled: false
