apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
  - name: volume-plugin-dir
    value: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
  criSocket: "unix:///run/containerd/containerd.sock"
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
networking:
  podSubnet: 192.168.0.0/16
controllerManager:
  extraArgs:
  - name: flex-volume-plugin-dir
    value: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
