# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant box for testing
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/33-cloud-base"
  memory = 6144
  cpus = 4

  config.vm.provider :virtualbox do |v|
    v.memory = memory
    v.cpus = cpus
  end

  config.vm.provider :libvirt do |v|
    v.memory = memory
    v.cpus = cpus
  end

  config.vm.provision "install-dependencies", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
      set -euxo pipefail

      export GO_VERSION=1.16
      curl -sSfL -o- https://dl.google.com/go/go"$GO_VERSION".linux-amd64.tar.gz |
        tar xfz - -C /usr/local

      echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
      echo 'export GOPATH="$HOME/go"' >> /etc/profile
      echo 'export GOBIN="$GOPATH/bin"' >> /etc/profile
      echo '. /etc/profile' >> $HOME/.bashrc

      dnf install -y \
        conntrack \
        container-selinux \
        golang-go \
        iptables \
        jq \
        make \
        oci-seccomp-bpf-hook \
        openssl \
        podman

      # Use a non-localhost DNS to avoid cluster DNS lookup loops
      echo "nameserver 8.8.8.8" > /etc/resolv.conf

      # Configure system to work seamlessly on single node clusters
      modprobe br_netfilter
      ip6tables --list >/dev/null
      iptables -F
      sysctl -w net.ipv4.conf.all.route_localnet=1
      sysctl -w net.ipv4.ip_forward=1
      sysctl -w net.bridge.bridge-nf-call-iptables=1
      sysctl -w fs.inotify.max_user_watches=1048576
      iptables -t nat -I POSTROUTING -s 127.0.0.0/8 ! -d 127.0.0.0/8 -j MASQUERADE
    SHELL
  end

  config.vm.provision "load-test-image", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
      set -euxo pipefail
      sudo podman load -i /vagrant/image.tar
    SHELL
  end

  config.vm.provision "install-cri-o", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
      set -euxo pipefail
      sudo /vagrant/hack/ci/install-cri-o.sh
    SHELL
  end

  config.vm.provision "install-kubernetes", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
      set -euxo pipefail
      sudo /vagrant/hack/ci/install-kubernetes.sh
    SHELL
  end
end
