# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant box for testing
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/33-cloud-base"
  memory = 6144
  cpus = 4

  config.vm.provider :virtualbox do |v|
    v.memory = memory
    v.cpus = cpus
  end

  config.vm.provider :libvirt do |v|
    v.memory = memory
    v.cpus = cpus
  end

  config.vm.provision "install-dependencies", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
    whoami
      set -euxo pipefail
      dnf install -y \
        conntrack \
        container-selinux \
        golang-go \
        iptables \
        jq \
        make \
        oci-seccomp-bpf-hook \
        openssl \
        podman
    SHELL
  end

  config.vm.provision "load-test-image", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
      set -euxo pipefail
      sudo podman load -i /vagrant/image.tar
    SHELL
  end

  config.vm.provision "install-cri-o", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
      set -euxo pipefail
      sudo /vagrant/hack/ci/install-cri-o.sh
    SHELL
  end

  config.vm.provision "install-kubernetes", type: "shell", run: "once" do |sh|
    sh.inline = <<~SHELL
      set -euxo pipefail
      sudo /vagrant/hack/ci/install-kubernetes.sh
    SHELL
  end
end
