# This is the namespaced deployment, which only watches configMaps for one
# namespace.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../cluster

patchesStrategicMerge:
  - webhook_config.yaml

patches:
  - target:
      kind: ClusterRole
      name: security-profiles-operator
    path: role.yaml

resources:
  - webhook_cert.yaml
  - webhook_deployment.yaml
  - webhook_service.yaml
