---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-cert
  namespace: security-profiles-operator
  labels:
    app: security-profiles-operator
spec:
  secretName: webhook-server-cert
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  dnsNames:
    - webhook-service.security-profiles-operator.svc
    - webhook-service.security-profiles-operator.svc.cluster.local
