---
# Keep in sync with getValidatingWebhookConfig in
# internal/pkg/manager/spod/bindata/webhook.go.
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: spo-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: "security-profiles-operator/webhook-cert"
webhooks:
  - name: rawselinuxprofile-validation.spo.io
    failurePolicy: Fail
    timeoutSeconds: 10
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["security-profiles-operator.x-k8s.io"]
        apiVersions: ["v1"]
        resources: ["rawselinuxprofiles"]
    clientConfig:
      service:
        namespace: "security-profiles-operator"
        name: "webhook-service"
        path: "/validate-rawselinuxprofile"
      caBundle: "Cg=="
    admissionReviewVersions:
    - v1
  - name: binding-image.spo.io
    failurePolicy: Fail
    timeoutSeconds: 10
    sideEffects: None
    rules:
      - operations: ["UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    matchConditions:
      - name: container-image-change
        expression: >-
          object.spec.containers.exists(c, oldObject.spec.containers.exists(o,
          o.name == c.name && o.image != c.image)) ||
          (has(object.spec.initContainers) && has(oldObject.spec.initContainers) &&
          object.spec.initContainers.exists(c, oldObject.spec.initContainers.exists(o,
          o.name == c.name && o.image != c.image)))
    namespaceSelector:
      matchExpressions:
        - key: spo.x-k8s.io/enable-binding
          operator: Exists
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["security-profiles-operator"]
    clientConfig:
      service:
        namespace: "security-profiles-operator"
        name: "webhook-service"
        path: "/validate-v1-pod-binding-image"
      caBundle: "Cg=="
    admissionReviewVersions:
    - v1
