//
//Copyright 2021 The Kubernetes Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/grpc/bpfrecorder/api.proto

package api_bpfrecorder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BpfRecorder_Start_FullMethodName              = "/api_bpfrecorder.BpfRecorder/Start"
	BpfRecorder_Stop_FullMethodName               = "/api_bpfrecorder.BpfRecorder/Stop"
	BpfRecorder_SyscallsForProfile_FullMethodName = "/api_bpfrecorder.BpfRecorder/SyscallsForProfile"
	BpfRecorder_ApparmorForProfile_FullMethodName = "/api_bpfrecorder.BpfRecorder/ApparmorForProfile"
)

// BpfRecorderClient is the client API for BpfRecorder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BpfRecorderClient interface {
	Start(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Stop(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	SyscallsForProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*SyscallsResponse, error)
	ApparmorForProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ApparmorResponse, error)
}

type bpfRecorderClient struct {
	cc grpc.ClientConnInterface
}

func NewBpfRecorderClient(cc grpc.ClientConnInterface) BpfRecorderClient {
	return &bpfRecorderClient{cc}
}

func (c *bpfRecorderClient) Start(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, BpfRecorder_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfRecorderClient) Stop(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, BpfRecorder_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfRecorderClient) SyscallsForProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*SyscallsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyscallsResponse)
	err := c.cc.Invoke(ctx, BpfRecorder_SyscallsForProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bpfRecorderClient) ApparmorForProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ApparmorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApparmorResponse)
	err := c.cc.Invoke(ctx, BpfRecorder_ApparmorForProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BpfRecorderServer is the server API for BpfRecorder service.
// All implementations must embed UnimplementedBpfRecorderServer
// for forward compatibility.
type BpfRecorderServer interface {
	Start(context.Context, *EmptyRequest) (*EmptyResponse, error)
	Stop(context.Context, *EmptyRequest) (*EmptyResponse, error)
	SyscallsForProfile(context.Context, *ProfileRequest) (*SyscallsResponse, error)
	ApparmorForProfile(context.Context, *ProfileRequest) (*ApparmorResponse, error)
	mustEmbedUnimplementedBpfRecorderServer()
}

// UnimplementedBpfRecorderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBpfRecorderServer struct{}

func (UnimplementedBpfRecorderServer) Start(context.Context, *EmptyRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedBpfRecorderServer) Stop(context.Context, *EmptyRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedBpfRecorderServer) SyscallsForProfile(context.Context, *ProfileRequest) (*SyscallsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyscallsForProfile not implemented")
}
func (UnimplementedBpfRecorderServer) ApparmorForProfile(context.Context, *ProfileRequest) (*ApparmorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApparmorForProfile not implemented")
}
func (UnimplementedBpfRecorderServer) mustEmbedUnimplementedBpfRecorderServer() {}
func (UnimplementedBpfRecorderServer) testEmbeddedByValue()                     {}

// UnsafeBpfRecorderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BpfRecorderServer will
// result in compilation errors.
type UnsafeBpfRecorderServer interface {
	mustEmbedUnimplementedBpfRecorderServer()
}

func RegisterBpfRecorderServer(s grpc.ServiceRegistrar, srv BpfRecorderServer) {
	// If the following call pancis, it indicates UnimplementedBpfRecorderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BpfRecorder_ServiceDesc, srv)
}

func _BpfRecorder_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfRecorderServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfRecorder_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfRecorderServer).Start(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfRecorder_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfRecorderServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfRecorder_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfRecorderServer).Stop(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfRecorder_SyscallsForProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfRecorderServer).SyscallsForProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfRecorder_SyscallsForProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfRecorderServer).SyscallsForProfile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BpfRecorder_ApparmorForProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpfRecorderServer).ApparmorForProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BpfRecorder_ApparmorForProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpfRecorderServer).ApparmorForProfile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BpfRecorder_ServiceDesc is the grpc.ServiceDesc for BpfRecorder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BpfRecorder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api_bpfrecorder.BpfRecorder",
	HandlerType: (*BpfRecorderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _BpfRecorder_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _BpfRecorder_Stop_Handler,
		},
		{
			MethodName: "SyscallsForProfile",
			Handler:    _BpfRecorder_SyscallsForProfile_Handler,
		},
		{
			MethodName: "ApparmorForProfile",
			Handler:    _BpfRecorder_ApparmorForProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/bpfrecorder/api.proto",
}
