/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by counterfeiter. DO NOT EDIT.
package artifactfakes

import (
	"context"
	"io"
	"sync"

	"github.com/google/go-containerregistry/pkg/name"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
	v1a "github.com/sigstore/protobuf-specs/gen/pb-go/bundle/v1"
	"github.com/sigstore/sigstore-go/pkg/root"
	"github.com/sigstore/sigstore-go/pkg/sign"
	"github.com/sigstore/sigstore-go/pkg/verify"
	oras "oras.land/oras-go/v2"
	"oras.land/oras-go/v2/content"
	"oras.land/oras-go/v2/content/file"
	"oras.land/oras-go/v2/registry/remote"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type FakeImpl struct {
	CopyStub        func(context.Context, oras.ReadOnlyTarget, string, oras.Target, string, oras.CopyOptions) (v1.Descriptor, error)
	copyMutex       sync.RWMutex
	copyArgsForCall []FakeImplCopyArgs
	copyReturns     struct {
		result1 v1.Descriptor
		result2 error
	}
	copyReturnsOnCall map[int]struct {
		result1 v1.Descriptor
		result2 error
	}
	FetchAllStub        func(context.Context, *remote.Repository, *v1.Descriptor) ([]byte, error)
	fetchAllMutex       sync.RWMutex
	fetchAllArgsForCall []FakeImplFetchAllArgs
	fetchAllReturns     struct {
		result1 []byte
		result2 error
	}
	fetchAllReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	FetchReferenceStub        func(context.Context, *remote.Repository, string, int64) (v1.Descriptor, []byte, error)
	fetchReferenceMutex       sync.RWMutex
	fetchReferenceArgsForCall []FakeImplFetchReferenceArgs
	fetchReferenceReturns     struct {
		result1 v1.Descriptor
		result2 []byte
		result3 error
	}
	fetchReferenceReturnsOnCall map[int]struct {
		result1 v1.Descriptor
		result2 []byte
		result3 error
	}
	FileCloseStub        func(*file.Store) error
	fileCloseMutex       sync.RWMutex
	fileCloseArgsForCall []FakeImplFileCloseArgs
	fileCloseReturns     struct {
		result1 error
	}
	fileCloseReturnsOnCall map[int]struct {
		result1 error
	}
	FileNewStub        func(string) (*file.Store, error)
	fileNewMutex       sync.RWMutex
	fileNewArgsForCall []FakeImplFileNewArgs
	fileNewReturns     struct {
		result1 *file.Store
		result2 error
	}
	fileNewReturnsOnCall map[int]struct {
		result1 *file.Store
		result2 error
	}
	FilepathAbsStub        func(string) (string, error)
	filepathAbsMutex       sync.RWMutex
	filepathAbsArgsForCall []FakeImplFilepathAbsArgs
	filepathAbsReturns     struct {
		result1 string
		result2 error
	}
	filepathAbsReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	IDTokenStub        func(context.Context, string, bool) (string, error)
	iDTokenMutex       sync.RWMutex
	iDTokenArgsForCall []FakeImplIDTokenArgs
	iDTokenReturns     struct {
		result1 string
		result2 error
	}
	iDTokenReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	MkdirTempStub        func(string, string) (string, error)
	mkdirTempMutex       sync.RWMutex
	mkdirTempArgsForCall []FakeImplMkdirTempArgs
	mkdirTempReturns     struct {
		result1 string
		result2 error
	}
	mkdirTempReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	NewRepositoryStub        func(string) (*remote.Repository, error)
	newRepositoryMutex       sync.RWMutex
	newRepositoryArgsForCall []FakeImplNewRepositoryArgs
	newRepositoryReturns     struct {
		result1 *remote.Repository
		result2 error
	}
	newRepositoryReturnsOnCall map[int]struct {
		result1 *remote.Repository
		result2 error
	}
	PackManifestStub        func(context.Context, content.Pusher, oras.PackManifestVersion, string, oras.PackManifestOptions) (v1.Descriptor, error)
	packManifestMutex       sync.RWMutex
	packManifestArgsForCall []FakeImplPackManifestArgs
	packManifestReturns     struct {
		result1 v1.Descriptor
		result2 error
	}
	packManifestReturnsOnCall map[int]struct {
		result1 v1.Descriptor
		result2 error
	}
	ParseReferenceStub        func(string, ...name.Option) (name.Reference, error)
	parseReferenceMutex       sync.RWMutex
	parseReferenceArgsForCall []FakeImplParseReferenceArgs
	parseReferenceReturns     struct {
		result1 name.Reference
		result2 error
	}
	parseReferenceReturnsOnCall map[int]struct {
		result1 name.Reference
		result2 error
	}
	ReadFileStub        func(string) ([]byte, error)
	readFileMutex       sync.RWMutex
	readFileArgsForCall []FakeImplReadFileArgs
	readFileReturns     struct {
		result1 []byte
		result2 error
	}
	readFileReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	ReadProfileStub        func([]byte) (client.Object, error)
	readProfileMutex       sync.RWMutex
	readProfileArgsForCall []FakeImplReadProfileArgs
	readProfileReturns     struct {
		result1 client.Object
		result2 error
	}
	readProfileReturnsOnCall map[int]struct {
		result1 client.Object
		result2 error
	}
	RemoveAllStub        func(string) error
	removeAllMutex       sync.RWMutex
	removeAllArgsForCall []FakeImplRemoveAllArgs
	removeAllReturns     struct {
		result1 error
	}
	removeAllReturnsOnCall map[int]struct {
		result1 error
	}
	RepositoryPushStub        func(context.Context, *remote.Repository, *v1.Descriptor, io.Reader) error
	repositoryPushMutex       sync.RWMutex
	repositoryPushArgsForCall []FakeImplRepositoryPushArgs
	repositoryPushReturns     struct {
		result1 error
	}
	repositoryPushReturnsOnCall map[int]struct {
		result1 error
	}
	ResolveRepositoryStub        func(context.Context, *remote.Repository, string) (v1.Descriptor, error)
	resolveRepositoryMutex       sync.RWMutex
	resolveRepositoryArgsForCall []FakeImplResolveRepositoryArgs
	resolveRepositoryReturns     struct {
		result1 v1.Descriptor
		result2 error
	}
	resolveRepositoryReturnsOnCall map[int]struct {
		result1 v1.Descriptor
		result2 error
	}
	SignBundleStub        func(context.Context, sign.Content, *sign.BundleOptions) (*v1a.Bundle, error)
	signBundleMutex       sync.RWMutex
	signBundleArgsForCall []FakeImplSignBundleArgs
	signBundleReturns     struct {
		result1 *v1a.Bundle
		result2 error
	}
	signBundleReturnsOnCall map[int]struct {
		result1 *v1a.Bundle
		result2 error
	}
	SignatureReferrersStub        func(context.Context, *remote.Repository, *v1.Descriptor) ([]v1.Descriptor, error)
	signatureReferrersMutex       sync.RWMutex
	signatureReferrersArgsForCall []FakeImplSignatureReferrersArgs
	signatureReferrersReturns     struct {
		result1 []v1.Descriptor
		result2 error
	}
	signatureReferrersReturnsOnCall map[int]struct {
		result1 []v1.Descriptor
		result2 error
	}
	SigningConfigStub        func(context.Context) (*root.SigningConfig, error)
	signingConfigMutex       sync.RWMutex
	signingConfigArgsForCall []FakeImplSigningConfigArgs
	signingConfigReturns     struct {
		result1 *root.SigningConfig
		result2 error
	}
	signingConfigReturnsOnCall map[int]struct {
		result1 *root.SigningConfig
		result2 error
	}
	StoreAddStub        func(context.Context, *file.Store, string, string, string) (v1.Descriptor, error)
	storeAddMutex       sync.RWMutex
	storeAddArgsForCall []FakeImplStoreAddArgs
	storeAddReturns     struct {
		result1 v1.Descriptor
		result2 error
	}
	storeAddReturnsOnCall map[int]struct {
		result1 v1.Descriptor
		result2 error
	}
	StoreFetchStub        func(context.Context, *file.Store, *v1.Descriptor) (io.ReadCloser, error)
	storeFetchMutex       sync.RWMutex
	storeFetchArgsForCall []FakeImplStoreFetchArgs
	storeFetchReturns     struct {
		result1 io.ReadCloser
		result2 error
	}
	storeFetchReturnsOnCall map[int]struct {
		result1 io.ReadCloser
		result2 error
	}
	StorePushStub        func(context.Context, *file.Store, *v1.Descriptor, io.Reader) error
	storePushMutex       sync.RWMutex
	storePushArgsForCall []FakeImplStorePushArgs
	storePushReturns     struct {
		result1 error
	}
	storePushReturnsOnCall map[int]struct {
		result1 error
	}
	StoreTagStub        func(context.Context, *file.Store, *v1.Descriptor, string) error
	storeTagMutex       sync.RWMutex
	storeTagArgsForCall []FakeImplStoreTagArgs
	storeTagReturns     struct {
		result1 error
	}
	storeTagReturnsOnCall map[int]struct {
		result1 error
	}
	TrustedMaterialStub        func(context.Context, string, bool) (root.TrustedMaterial, error)
	trustedMaterialMutex       sync.RWMutex
	trustedMaterialArgsForCall []FakeImplTrustedMaterialArgs
	trustedMaterialReturns     struct {
		result1 root.TrustedMaterial
		result2 error
	}
	trustedMaterialReturnsOnCall map[int]struct {
		result1 root.TrustedMaterial
		result2 error
	}
	VerifyEntityStub        func(verify.SignedEntity, root.TrustedMaterial, []verify.VerifierOption, verify.ArtifactPolicyOption, *verify.CertificateIdentity) error
	verifyEntityMutex       sync.RWMutex
	verifyEntityArgsForCall []FakeImplVerifyEntityArgs
	verifyEntityReturns     struct {
		result1 error
	}
	verifyEntityReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// FakeImplCopyArgs holds the arguments of one call to Copy.
type FakeImplCopyArgs struct {
	Arg1 context.Context
	Arg2 oras.ReadOnlyTarget
	Arg3 string
	Arg4 oras.Target
	Arg5 string
	Arg6 oras.CopyOptions
}

// FakeImplFetchAllArgs holds the arguments of one call to FetchAll.
type FakeImplFetchAllArgs struct {
	Arg1 context.Context
	Arg2 *remote.Repository
	Arg3 *v1.Descriptor
}

// FakeImplFetchReferenceArgs holds the arguments of one call to FetchReference.
type FakeImplFetchReferenceArgs struct {
	Arg1 context.Context
	Arg2 *remote.Repository
	Arg3 string
	Arg4 int64
}

// FakeImplFileCloseArgs holds the arguments of one call to FileClose.
type FakeImplFileCloseArgs struct {
	Arg1 *file.Store
}

// FakeImplFileNewArgs holds the arguments of one call to FileNew.
type FakeImplFileNewArgs struct {
	Arg1 string
}

// FakeImplFilepathAbsArgs holds the arguments of one call to FilepathAbs.
type FakeImplFilepathAbsArgs struct {
	Arg1 string
}

// FakeImplIDTokenArgs holds the arguments of one call to IDToken.
type FakeImplIDTokenArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 bool
}

// FakeImplMkdirTempArgs holds the arguments of one call to MkdirTemp.
type FakeImplMkdirTempArgs struct {
	Arg1 string
	Arg2 string
}

// FakeImplNewRepositoryArgs holds the arguments of one call to NewRepository.
type FakeImplNewRepositoryArgs struct {
	Arg1 string
}

// FakeImplPackManifestArgs holds the arguments of one call to PackManifest.
type FakeImplPackManifestArgs struct {
	Arg1 context.Context
	Arg2 content.Pusher
	Arg3 oras.PackManifestVersion
	Arg4 string
	Arg5 oras.PackManifestOptions
}

// FakeImplParseReferenceArgs holds the arguments of one call to ParseReference.
type FakeImplParseReferenceArgs struct {
	Arg1 string
	Arg2 []name.Option
}

// FakeImplReadFileArgs holds the arguments of one call to ReadFile.
type FakeImplReadFileArgs struct {
	Arg1 string
}

// FakeImplReadProfileArgs holds the arguments of one call to ReadProfile.
type FakeImplReadProfileArgs struct {
	Arg1 []byte
}

// FakeImplRemoveAllArgs holds the arguments of one call to RemoveAll.
type FakeImplRemoveAllArgs struct {
	Arg1 string
}

// FakeImplRepositoryPushArgs holds the arguments of one call to RepositoryPush.
type FakeImplRepositoryPushArgs struct {
	Arg1 context.Context
	Arg2 *remote.Repository
	Arg3 *v1.Descriptor
	Arg4 io.Reader
}

// FakeImplResolveRepositoryArgs holds the arguments of one call to ResolveRepository.
type FakeImplResolveRepositoryArgs struct {
	Arg1 context.Context
	Arg2 *remote.Repository
	Arg3 string
}

// FakeImplSignBundleArgs holds the arguments of one call to SignBundle.
type FakeImplSignBundleArgs struct {
	Arg1 context.Context
	Arg2 sign.Content
	Arg3 *sign.BundleOptions
}

// FakeImplSignatureReferrersArgs holds the arguments of one call to SignatureReferrers.
type FakeImplSignatureReferrersArgs struct {
	Arg1 context.Context
	Arg2 *remote.Repository
	Arg3 *v1.Descriptor
}

// FakeImplSigningConfigArgs holds the arguments of one call to SigningConfig.
type FakeImplSigningConfigArgs struct {
	Arg1 context.Context
}

// FakeImplStoreAddArgs holds the arguments of one call to StoreAdd.
type FakeImplStoreAddArgs struct {
	Arg1 context.Context
	Arg2 *file.Store
	Arg3 string
	Arg4 string
	Arg5 string
}

// FakeImplStoreFetchArgs holds the arguments of one call to StoreFetch.
type FakeImplStoreFetchArgs struct {
	Arg1 context.Context
	Arg2 *file.Store
	Arg3 *v1.Descriptor
}

// FakeImplStorePushArgs holds the arguments of one call to StorePush.
type FakeImplStorePushArgs struct {
	Arg1 context.Context
	Arg2 *file.Store
	Arg3 *v1.Descriptor
	Arg4 io.Reader
}

// FakeImplStoreTagArgs holds the arguments of one call to StoreTag.
type FakeImplStoreTagArgs struct {
	Arg1 context.Context
	Arg2 *file.Store
	Arg3 *v1.Descriptor
	Arg4 string
}

// FakeImplTrustedMaterialArgs holds the arguments of one call to TrustedMaterial.
type FakeImplTrustedMaterialArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 bool
}

// FakeImplVerifyEntityArgs holds the arguments of one call to VerifyEntity.
type FakeImplVerifyEntityArgs struct {
	Arg1 verify.SignedEntity
	Arg2 root.TrustedMaterial
	Arg3 []verify.VerifierOption
	Arg4 verify.ArtifactPolicyOption
	Arg5 *verify.CertificateIdentity
}

func (fake *FakeImpl) Copy(arg1 context.Context, arg2 oras.ReadOnlyTarget, arg3 string, arg4 oras.Target, arg5 string, arg6 oras.CopyOptions) (v1.Descriptor, error) {
	fake.copyMutex.Lock()
	ret, specificReturn := fake.copyReturnsOnCall[len(fake.copyArgsForCall)]
	fake.copyArgsForCall = append(fake.copyArgsForCall, FakeImplCopyArgs{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.CopyStub
	fakeReturns := fake.copyReturns
	fake.recordInvocation("Copy", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.copyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) CopyCallCount() int {
	fake.copyMutex.RLock()
	defer fake.copyMutex.RUnlock()
	return len(fake.copyArgsForCall)
}

func (fake *FakeImpl) CopyCalls(stub func(context.Context, oras.ReadOnlyTarget, string, oras.Target, string, oras.CopyOptions) (v1.Descriptor, error)) {
	fake.copyMutex.Lock()
	defer fake.copyMutex.Unlock()
	fake.CopyStub = stub
}

func (fake *FakeImpl) CopyArgsForCall(i int) (context.Context, oras.ReadOnlyTarget, string, oras.Target, string, oras.CopyOptions) {
	fake.copyMutex.RLock()
	defer fake.copyMutex.RUnlock()
	argsForCall := fake.copyArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4, argsForCall.Arg5, argsForCall.Arg6
}

func (fake *FakeImpl) CopyArgs() []FakeImplCopyArgs {
	fake.copyMutex.RLock()
	defer fake.copyMutex.RUnlock()
	args := make([]FakeImplCopyArgs, len(fake.copyArgsForCall))
	copy(args, fake.copyArgsForCall)
	return args
}

func (fake *FakeImpl) CopyReturns(result1 v1.Descriptor, result2 error) {
	fake.copyMutex.Lock()
	defer fake.copyMutex.Unlock()
	fake.CopyStub = nil
	fake.copyReturns = struct {
		result1 v1.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) CopyReturnsOnCall(i int, result1 v1.Descriptor, result2 error) {
	fake.copyMutex.Lock()
	defer fake.copyMutex.Unlock()
	fake.CopyStub = nil
	if fake.copyReturnsOnCall == nil {
		fake.copyReturnsOnCall = make(map[int]struct {
			result1 v1.Descriptor
			result2 error
		})
	}
	fake.copyReturnsOnCall[i] = struct {
		result1 v1.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) FetchAll(arg1 context.Context, arg2 *remote.Repository, arg3 *v1.Descriptor) ([]byte, error) {
	fake.fetchAllMutex.Lock()
	ret, specificReturn := fake.fetchAllReturnsOnCall[len(fake.fetchAllArgsForCall)]
	fake.fetchAllArgsForCall = append(fake.fetchAllArgsForCall, FakeImplFetchAllArgs{arg1, arg2, arg3})
	stub := fake.FetchAllStub
	fakeReturns := fake.fetchAllReturns
	fake.recordInvocation("FetchAll", []interface{}{arg1, arg2, arg3})
	fake.fetchAllMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) FetchAllCallCount() int {
	fake.fetchAllMutex.RLock()
	defer fake.fetchAllMutex.RUnlock()
	return len(fake.fetchAllArgsForCall)
}

func (fake *FakeImpl) FetchAllCalls(stub func(context.Context, *remote.Repository, *v1.Descriptor) ([]byte, error)) {
	fake.fetchAllMutex.Lock()
	defer fake.fetchAllMutex.Unlock()
	fake.FetchAllStub = stub
}

func (fake *FakeImpl) FetchAllArgsForCall(i int) (context.Context, *remote.Repository, *v1.Descriptor) {
	fake.fetchAllMutex.RLock()
	defer fake.fetchAllMutex.RUnlock()
	argsForCall := fake.fetchAllArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeImpl) FetchAllArgs() []FakeImplFetchAllArgs {
	fake.fetchAllMutex.RLock()
	defer fake.fetchAllMutex.RUnlock()
	args := make([]FakeImplFetchAllArgs, len(fake.fetchAllArgsForCall))
	copy(args, fake.fetchAllArgsForCall)
	return args
}

func (fake *FakeImpl) FetchAllReturns(result1 []byte, result2 error) {
	fake.fetchAllMutex.Lock()
	defer fake.fetchAllMutex.Unlock()
	fake.FetchAllStub = nil
	fake.fetchAllReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) FetchAllReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.fetchAllMutex.Lock()
	defer fake.fetchAllMutex.Unlock()
	fake.FetchAllStub = nil
	if fake.fetchAllReturnsOnCall == nil {
		fake.fetchAllReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.fetchAllReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) FetchReference(arg1 context.Context, arg2 *remote.Repository, arg3 string, arg4 int64) (v1.Descriptor, []byte, error) {
	fake.fetchReferenceMutex.Lock()
	ret, specificReturn := fake.fetchReferenceReturnsOnCall[len(fake.fetchReferenceArgsForCall)]
	fake.fetchReferenceArgsForCall = append(fake.fetchReferenceArgsForCall, FakeImplFetchReferenceArgs{arg1, arg2, arg3, arg4})
	stub := fake.FetchReferenceStub
	fakeReturns := fake.fetchReferenceReturns
	fake.recordInvocation("FetchReference", []interface{}{arg1, arg2, arg3, arg4})
	fake.fetchReferenceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeImpl) FetchReferenceCallCount() int {
	fake.fetchReferenceMutex.RLock()
	defer fake.fetchReferenceMutex.RUnlock()
	return len(fake.fetchReferenceArgsForCall)
}

func (fake *FakeImpl) FetchReferenceCalls(stub func(context.Context, *remote.Repository, string, int64) (v1.Descriptor, []byte, error)) {
	fake.fetchReferenceMutex.Lock()
	defer fake.fetchReferenceMutex.Unlock()
	fake.FetchReferenceStub = stub
}

func (fake *FakeImpl) FetchReferenceArgsForCall(i int) (context.Context, *remote.Repository, string, int64) {
	fake.fetchReferenceMutex.RLock()
	defer fake.fetchReferenceMutex.RUnlock()
	argsForCall := fake.fetchReferenceArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeImpl) FetchReferenceArgs() []FakeImplFetchReferenceArgs {
	fake.fetchReferenceMutex.RLock()
	defer fake.fetchReferenceMutex.RUnlock()
	args := make([]FakeImplFetchReferenceArgs, len(fake.fetchReferenceArgsForCall))
	copy(args, fake.fetchReferenceArgsForCall)
	return args
}

func (fake *FakeImpl) FetchReferenceReturns(result1 v1.Descriptor, result2 []byte, result3 error) {
	fake.fetchReferenceMutex.Lock()
	defer fake.fetchReferenceMutex.Unlock()
	fake.FetchReferenceStub = nil
	fake.fetchReferenceReturns = struct {
		result1 v1.Descriptor
		result2 []byte
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeImpl) FetchReferenceReturnsOnCall(i int, result1 v1.Descriptor, result2 []byte, result3 error) {
	fake.fetchReferenceMutex.Lock()
	defer fake.fetchReferenceMutex.Unlock()
	fake.FetchReferenceStub = nil
	if fake.fetchReferenceReturnsOnCall == nil {
		fake.fetchReferenceReturnsOnCall = make(map[int]struct {
			result1 v1.Descriptor
			result2 []byte
			result3 error
		})
	}
	fake.fetchReferenceReturnsOnCall[i] = struct {
		result1 v1.Descriptor
		result2 []byte
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeImpl) FileClose(arg1 *file.Store) error {
	fake.fileCloseMutex.Lock()
	ret, specificReturn := fake.fileCloseReturnsOnCall[len(fake.fileCloseArgsForCall)]
	fake.fileCloseArgsForCall = append(fake.fileCloseArgsForCall, FakeImplFileCloseArgs{arg1})
	stub := fake.FileCloseStub
	fakeReturns := fake.fileCloseReturns
	fake.recordInvocation("FileClose", []interface{}{arg1})
	fake.fileCloseMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) FileCloseCallCount() int {
	fake.fileCloseMutex.RLock()
	defer fake.fileCloseMutex.RUnlock()
	return len(fake.fileCloseArgsForCall)
}

func (fake *FakeImpl) FileCloseCalls(stub func(*file.Store) error) {
	fake.fileCloseMutex.Lock()
	defer fake.fileCloseMutex.Unlock()
	fake.FileCloseStub = stub
}

func (fake *FakeImpl) FileCloseArgsForCall(i int) *file.Store {
	fake.fileCloseMutex.RLock()
	defer fake.fileCloseMutex.RUnlock()
	argsForCall := fake.fileCloseArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) FileCloseArgs() []FakeImplFileCloseArgs {
	fake.fileCloseMutex.RLock()
	defer fake.fileCloseMutex.RUnlock()
	args := make([]FakeImplFileCloseArgs, len(fake.fileCloseArgsForCall))
	copy(args, fake.fileCloseArgsForCall)
	return args
}

func (fake *FakeImpl) FileCloseReturns(result1 error) {
	fake.fileCloseMutex.Lock()
	defer fake.fileCloseMutex.Unlock()
	fake.FileCloseStub = nil
	fake.fileCloseReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) FileCloseReturnsOnCall(i int, result1 error) {
	fake.fileCloseMutex.Lock()
	defer fake.fileCloseMutex.Unlock()
	fake.FileCloseStub = nil
	if fake.fileCloseReturnsOnCall == nil {
		fake.fileCloseReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fileCloseReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) FileNew(arg1 string) (*file.Store, error) {
	fake.fileNewMutex.Lock()
	ret, specificReturn := fake.fileNewReturnsOnCall[len(fake.fileNewArgsForCall)]
	fake.fileNewArgsForCall = append(fake.fileNewArgsForCall, FakeImplFileNewArgs{arg1})
	stub := fake.FileNewStub
	fakeReturns := fake.fileNewReturns
	fake.recordInvocation("FileNew", []interface{}{arg1})
	fake.fileNewMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) FileNewCallCount() int {
	fake.fileNewMutex.RLock()
	defer fake.fileNewMutex.RUnlock()
	return len(fake.fileNewArgsForCall)
}

func (fake *FakeImpl) FileNewCalls(stub func(string) (*file.Store, error)) {
	fake.fileNewMutex.Lock()
	defer fake.fileNewMutex.Unlock()
	fake.FileNewStub = stub
}

func (fake *FakeImpl) FileNewArgsForCall(i int) string {
	fake.fileNewMutex.RLock()
	defer fake.fileNewMutex.RUnlock()
	argsForCall := fake.fileNewArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) FileNewArgs() []FakeImplFileNewArgs {
	fake.fileNewMutex.RLock()
	defer fake.fileNewMutex.RUnlock()
	args := make([]FakeImplFileNewArgs, len(fake.fileNewArgsForCall))
	copy(args, fake.fileNewArgsForCall)
	return args
}

func (fake *FakeImpl) FileNewReturns(result1 *file.Store, result2 error) {
	fake.fileNewMutex.Lock()
	defer fake.fileNewMutex.Unlock()
	fake.FileNewStub = nil
	fake.fileNewReturns = struct {
		result1 *file.Store
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) FileNewReturnsOnCall(i int, result1 *file.Store, result2 error) {
	fake.fileNewMutex.Lock()
	defer fake.fileNewMutex.Unlock()
	fake.FileNewStub = nil
	if fake.fileNewReturnsOnCall == nil {
		fake.fileNewReturnsOnCall = make(map[int]struct {
			result1 *file.Store
			result2 error
		})
	}
	fake.fileNewReturnsOnCall[i] = struct {
		result1 *file.Store
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) FilepathAbs(arg1 string) (string, error) {
	fake.filepathAbsMutex.Lock()
	ret, specificReturn := fake.filepathAbsReturnsOnCall[len(fake.filepathAbsArgsForCall)]
	fake.filepathAbsArgsForCall = append(fake.filepathAbsArgsForCall, FakeImplFilepathAbsArgs{arg1})
	stub := fake.FilepathAbsStub
	fakeReturns := fake.filepathAbsReturns
	fake.recordInvocation("FilepathAbs", []interface{}{arg1})
	fake.filepathAbsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) FilepathAbsCallCount() int {
	fake.filepathAbsMutex.RLock()
	defer fake.filepathAbsMutex.RUnlock()
	return len(fake.filepathAbsArgsForCall)
}

func (fake *FakeImpl) FilepathAbsCalls(stub func(string) (string, error)) {
	fake.filepathAbsMutex.Lock()
	defer fake.filepathAbsMutex.Unlock()
	fake.FilepathAbsStub = stub
}

func (fake *FakeImpl) FilepathAbsArgsForCall(i int) string {
	fake.filepathAbsMutex.RLock()
	defer fake.filepathAbsMutex.RUnlock()
	argsForCall := fake.filepathAbsArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) FilepathAbsArgs() []FakeImplFilepathAbsArgs {
	fake.filepathAbsMutex.RLock()
	defer fake.filepathAbsMutex.RUnlock()
	args := make([]FakeImplFilepathAbsArgs, len(fake.filepathAbsArgsForCall))
	copy(args, fake.filepathAbsArgsForCall)
	return args
}

func (fake *FakeImpl) FilepathAbsReturns(result1 string, result2 error) {
	fake.filepathAbsMutex.Lock()
	defer fake.filepathAbsMutex.Unlock()
	fake.FilepathAbsStub = nil
	fake.filepathAbsReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) FilepathAbsReturnsOnCall(i int, result1 string, result2 error) {
	fake.filepathAbsMutex.Lock()
	defer fake.filepathAbsMutex.Unlock()
	fake.FilepathAbsStub = nil
	if fake.filepathAbsReturnsOnCall == nil {
		fake.filepathAbsReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.filepathAbsReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) IDToken(arg1 context.Context, arg2 string, arg3 bool) (string, error) {
	fake.iDTokenMutex.Lock()
	ret, specificReturn := fake.iDTokenReturnsOnCall[len(fake.iDTokenArgsForCall)]
	fake.iDTokenArgsForCall = append(fake.iDTokenArgsForCall, FakeImplIDTokenArgs{arg1, arg2, arg3})
	stub := fake.IDTokenStub
	fakeReturns := fake.iDTokenReturns
	fake.recordInvocation("IDToken", []interface{}{arg1, arg2, arg3})
	fake.iDTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) IDTokenCallCount() int {
	fake.iDTokenMutex.RLock()
	defer fake.iDTokenMutex.RUnlock()
	return len(fake.iDTokenArgsForCall)
}

func (fake *FakeImpl) IDTokenCalls(stub func(context.Context, string, bool) (string, error)) {
	fake.iDTokenMutex.Lock()
	defer fake.iDTokenMutex.Unlock()
	fake.IDTokenStub = stub
}

func (fake *FakeImpl) IDTokenArgsForCall(i int) (context.Context, string, bool) {
	fake.iDTokenMutex.RLock()
	defer fake.iDTokenMutex.RUnlock()
	argsForCall := fake.iDTokenArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeImpl) IDTokenArgs() []FakeImplIDTokenArgs {
	fake.iDTokenMutex.RLock()
	defer fake.iDTokenMutex.RUnlock()
	args := make([]FakeImplIDTokenArgs, len(fake.iDTokenArgsForCall))
	copy(args, fake.iDTokenArgsForCall)
	return args
}

func (fake *FakeImpl) IDTokenReturns(result1 string, result2 error) {
	fake.iDTokenMutex.Lock()
	defer fake.iDTokenMutex.Unlock()
	fake.IDTokenStub = nil
	fake.iDTokenReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) IDTokenReturnsOnCall(i int, result1 string, result2 error) {
	fake.iDTokenMutex.Lock()
	defer fake.iDTokenMutex.Unlock()
	fake.IDTokenStub = nil
	if fake.iDTokenReturnsOnCall == nil {
		fake.iDTokenReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.iDTokenReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) MkdirTemp(arg1 string, arg2 string) (string, error) {
	fake.mkdirTempMutex.Lock()
	ret, specificReturn := fake.mkdirTempReturnsOnCall[len(fake.mkdirTempArgsForCall)]
	fake.mkdirTempArgsForCall = append(fake.mkdirTempArgsForCall, FakeImplMkdirTempArgs{arg1, arg2})
	stub := fake.MkdirTempStub
	fakeReturns := fake.mkdirTempReturns
	fake.recordInvocation("MkdirTemp", []interface{}{arg1, arg2})
	fake.mkdirTempMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) MkdirTempCallCount() int {
	fake.mkdirTempMutex.RLock()
	defer fake.mkdirTempMutex.RUnlock()
	return len(fake.mkdirTempArgsForCall)
}

func (fake *FakeImpl) MkdirTempCalls(stub func(string, string) (string, error)) {
	fake.mkdirTempMutex.Lock()
	defer fake.mkdirTempMutex.Unlock()
	fake.MkdirTempStub = stub
}

func (fake *FakeImpl) MkdirTempArgsForCall(i int) (string, string) {
	fake.mkdirTempMutex.RLock()
	defer fake.mkdirTempMutex.RUnlock()
	argsForCall := fake.mkdirTempArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeImpl) MkdirTempArgs() []FakeImplMkdirTempArgs {
	fake.mkdirTempMutex.RLock()
	defer fake.mkdirTempMutex.RUnlock()
	args := make([]FakeImplMkdirTempArgs, len(fake.mkdirTempArgsForCall))
	copy(args, fake.mkdirTempArgsForCall)
	return args
}

func (fake *FakeImpl) MkdirTempReturns(result1 string, result2 error) {
	fake.mkdirTempMutex.Lock()
	defer fake.mkdirTempMutex.Unlock()
	fake.MkdirTempStub = nil
	fake.mkdirTempReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) MkdirTempReturnsOnCall(i int, result1 string, result2 error) {
	fake.mkdirTempMutex.Lock()
	defer fake.mkdirTempMutex.Unlock()
	fake.MkdirTempStub = nil
	if fake.mkdirTempReturnsOnCall == nil {
		fake.mkdirTempReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.mkdirTempReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) NewRepository(arg1 string) (*remote.Repository, error) {
	fake.newRepositoryMutex.Lock()
	ret, specificReturn := fake.newRepositoryReturnsOnCall[len(fake.newRepositoryArgsForCall)]
	fake.newRepositoryArgsForCall = append(fake.newRepositoryArgsForCall, FakeImplNewRepositoryArgs{arg1})
	stub := fake.NewRepositoryStub
	fakeReturns := fake.newRepositoryReturns
	fake.recordInvocation("NewRepository", []interface{}{arg1})
	fake.newRepositoryMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) NewRepositoryCallCount() int {
	fake.newRepositoryMutex.RLock()
	defer fake.newRepositoryMutex.RUnlock()
	return len(fake.newRepositoryArgsForCall)
}

func (fake *FakeImpl) NewRepositoryCalls(stub func(string) (*remote.Repository, error)) {
	fake.newRepositoryMutex.Lock()
	defer fake.newRepositoryMutex.Unlock()
	fake.NewRepositoryStub = stub
}

func (fake *FakeImpl) NewRepositoryArgsForCall(i int) string {
	fake.newRepositoryMutex.RLock()
	defer fake.newRepositoryMutex.RUnlock()
	argsForCall := fake.newRepositoryArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) NewRepositoryArgs() []FakeImplNewRepositoryArgs {
	fake.newRepositoryMutex.RLock()
	defer fake.newRepositoryMutex.RUnlock()
	args := make([]FakeImplNewRepositoryArgs, len(fake.newRepositoryArgsForCall))
	copy(args, fake.newRepositoryArgsForCall)
	return args
}

func (fake *FakeImpl) NewRepositoryReturns(result1 *remote.Repository, result2 error) {
	fake.newRepositoryMutex.Lock()
	defer fake.newRepositoryMutex.Unlock()
	fake.NewRepositoryStub = nil
	fake.newRepositoryReturns = struct {
		result1 *remote.Repository
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) NewRepositoryReturnsOnCall(i int, result1 *remote.Repository, result2 error) {
	fake.newRepositoryMutex.Lock()
	defer fake.newRepositoryMutex.Unlock()
	fake.NewRepositoryStub = nil
	if fake.newRepositoryReturnsOnCall == nil {
		fake.newRepositoryReturnsOnCall = make(map[int]struct {
			result1 *remote.Repository
			result2 error
		})
	}
	fake.newRepositoryReturnsOnCall[i] = struct {
		result1 *remote.Repository
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) PackManifest(arg1 context.Context, arg2 content.Pusher, arg3 oras.PackManifestVersion, arg4 string, arg5 oras.PackManifestOptions) (v1.Descriptor, error) {
	fake.packManifestMutex.Lock()
	ret, specificReturn := fake.packManifestReturnsOnCall[len(fake.packManifestArgsForCall)]
	fake.packManifestArgsForCall = append(fake.packManifestArgsForCall, FakeImplPackManifestArgs{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PackManifestStub
	fakeReturns := fake.packManifestReturns
	fake.recordInvocation("PackManifest", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.packManifestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) PackManifestCallCount() int {
	fake.packManifestMutex.RLock()
	defer fake.packManifestMutex.RUnlock()
	return len(fake.packManifestArgsForCall)
}

func (fake *FakeImpl) PackManifestCalls(stub func(context.Context, content.Pusher, oras.PackManifestVersion, string, oras.PackManifestOptions) (v1.Descriptor, error)) {
	fake.packManifestMutex.Lock()
	defer fake.packManifestMutex.Unlock()
	fake.PackManifestStub = stub
}

func (fake *FakeImpl) PackManifestArgsForCall(i int) (context.Context, content.Pusher, oras.PackManifestVersion, string, oras.PackManifestOptions) {
	fake.packManifestMutex.RLock()
	defer fake.packManifestMutex.RUnlock()
	argsForCall := fake.packManifestArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4, argsForCall.Arg5
}

func (fake *FakeImpl) PackManifestArgs() []FakeImplPackManifestArgs {
	fake.packManifestMutex.RLock()
	defer fake.packManifestMutex.RUnlock()
	args := make([]FakeImplPackManifestArgs, len(fake.packManifestArgsForCall))
	copy(args, fake.packManifestArgsForCall)
	return args
}

func (fake *FakeImpl) PackManifestReturns(result1 v1.Descriptor, result2 error) {
	fake.packManifestMutex.Lock()
	defer fake.packManifestMutex.Unlock()
	fake.PackManifestStub = nil
	fake.packManifestReturns = struct {
		result1 v1.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) PackManifestReturnsOnCall(i int, result1 v1.Descriptor, result2 error) {
	fake.packManifestMutex.Lock()
	defer fake.packManifestMutex.Unlock()
	fake.PackManifestStub = nil
	if fake.packManifestReturnsOnCall == nil {
		fake.packManifestReturnsOnCall = make(map[int]struct {
			result1 v1.Descriptor
			result2 error
		})
	}
	fake.packManifestReturnsOnCall[i] = struct {
		result1 v1.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ParseReference(arg1 string, arg2 ...name.Option) (name.Reference, error) {
	var arg2Copy []name.Option
	if arg2 != nil {
		arg2Copy = make([]name.Option, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.parseReferenceMutex.Lock()
	ret, specificReturn := fake.parseReferenceReturnsOnCall[len(fake.parseReferenceArgsForCall)]
	fake.parseReferenceArgsForCall = append(fake.parseReferenceArgsForCall, FakeImplParseReferenceArgs{arg1, arg2Copy})
	stub := fake.ParseReferenceStub
	fakeReturns := fake.parseReferenceReturns
	fake.recordInvocation("ParseReference", []interface{}{arg1, arg2Copy})
	fake.parseReferenceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) ParseReferenceCallCount() int {
	fake.parseReferenceMutex.RLock()
	defer fake.parseReferenceMutex.RUnlock()
	return len(fake.parseReferenceArgsForCall)
}

func (fake *FakeImpl) ParseReferenceCalls(stub func(string, ...name.Option) (name.Reference, error)) {
	fake.parseReferenceMutex.Lock()
	defer fake.parseReferenceMutex.Unlock()
	fake.ParseReferenceStub = stub
}

func (fake *FakeImpl) ParseReferenceArgsForCall(i int) (string, []name.Option) {
	fake.parseReferenceMutex.RLock()
	defer fake.parseReferenceMutex.RUnlock()
	argsForCall := fake.parseReferenceArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeImpl) ParseReferenceArgs() []FakeImplParseReferenceArgs {
	fake.parseReferenceMutex.RLock()
	defer fake.parseReferenceMutex.RUnlock()
	args := make([]FakeImplParseReferenceArgs, len(fake.parseReferenceArgsForCall))
	copy(args, fake.parseReferenceArgsForCall)
	return args
}

func (fake *FakeImpl) ParseReferenceReturns(result1 name.Reference, result2 error) {
	fake.parseReferenceMutex.Lock()
	defer fake.parseReferenceMutex.Unlock()
	fake.ParseReferenceStub = nil
	fake.parseReferenceReturns = struct {
		result1 name.Reference
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ParseReferenceReturnsOnCall(i int, result1 name.Reference, result2 error) {
	fake.parseReferenceMutex.Lock()
	defer fake.parseReferenceMutex.Unlock()
	fake.ParseReferenceStub = nil
	if fake.parseReferenceReturnsOnCall == nil {
		fake.parseReferenceReturnsOnCall = make(map[int]struct {
			result1 name.Reference
			result2 error
		})
	}
	fake.parseReferenceReturnsOnCall[i] = struct {
		result1 name.Reference
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ReadFile(arg1 string) ([]byte, error) {
	fake.readFileMutex.Lock()
	ret, specificReturn := fake.readFileReturnsOnCall[len(fake.readFileArgsForCall)]
	fake.readFileArgsForCall = append(fake.readFileArgsForCall, FakeImplReadFileArgs{arg1})
	stub := fake.ReadFileStub
	fakeReturns := fake.readFileReturns
	fake.recordInvocation("ReadFile", []interface{}{arg1})
	fake.readFileMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) ReadFileCallCount() int {
	fake.readFileMutex.RLock()
	defer fake.readFileMutex.RUnlock()
	return len(fake.readFileArgsForCall)
}

func (fake *FakeImpl) ReadFileCalls(stub func(string) ([]byte, error)) {
	fake.readFileMutex.Lock()
	defer fake.readFileMutex.Unlock()
	fake.ReadFileStub = stub
}

func (fake *FakeImpl) ReadFileArgsForCall(i int) string {
	fake.readFileMutex.RLock()
	defer fake.readFileMutex.RUnlock()
	argsForCall := fake.readFileArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) ReadFileArgs() []FakeImplReadFileArgs {
	fake.readFileMutex.RLock()
	defer fake.readFileMutex.RUnlock()
	args := make([]FakeImplReadFileArgs, len(fake.readFileArgsForCall))
	copy(args, fake.readFileArgsForCall)
	return args
}

func (fake *FakeImpl) ReadFileReturns(result1 []byte, result2 error) {
	fake.readFileMutex.Lock()
	defer fake.readFileMutex.Unlock()
	fake.ReadFileStub = nil
	fake.readFileReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ReadFileReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.readFileMutex.Lock()
	defer fake.readFileMutex.Unlock()
	fake.ReadFileStub = nil
	if fake.readFileReturnsOnCall == nil {
		fake.readFileReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.readFileReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ReadProfile(arg1 []byte) (client.Object, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.readProfileMutex.Lock()
	ret, specificReturn := fake.readProfileReturnsOnCall[len(fake.readProfileArgsForCall)]
	fake.readProfileArgsForCall = append(fake.readProfileArgsForCall, FakeImplReadProfileArgs{arg1Copy})
	stub := fake.ReadProfileStub
	fakeReturns := fake.readProfileReturns
	fake.recordInvocation("ReadProfile", []interface{}{arg1Copy})
	fake.readProfileMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) ReadProfileCallCount() int {
	fake.readProfileMutex.RLock()
	defer fake.readProfileMutex.RUnlock()
	return len(fake.readProfileArgsForCall)
}

func (fake *FakeImpl) ReadProfileCalls(stub func([]byte) (client.Object, error)) {
	fake.readProfileMutex.Lock()
	defer fake.readProfileMutex.Unlock()
	fake.ReadProfileStub = stub
}

func (fake *FakeImpl) ReadProfileArgsForCall(i int) []byte {
	fake.readProfileMutex.RLock()
	defer fake.readProfileMutex.RUnlock()
	argsForCall := fake.readProfileArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) ReadProfileArgs() []FakeImplReadProfileArgs {
	fake.readProfileMutex.RLock()
	defer fake.readProfileMutex.RUnlock()
	args := make([]FakeImplReadProfileArgs, len(fake.readProfileArgsForCall))
	copy(args, fake.readProfileArgsForCall)
	return args
}

func (fake *FakeImpl) ReadProfileReturns(result1 client.Object, result2 error) {
	fake.readProfileMutex.Lock()
	defer fake.readProfileMutex.Unlock()
	fake.ReadProfileStub = nil
	fake.readProfileReturns = struct {
		result1 client.Object
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ReadProfileReturnsOnCall(i int, result1 client.Object, result2 error) {
	fake.readProfileMutex.Lock()
	defer fake.readProfileMutex.Unlock()
	fake.ReadProfileStub = nil
	if fake.readProfileReturnsOnCall == nil {
		fake.readProfileReturnsOnCall = make(map[int]struct {
			result1 client.Object
			result2 error
		})
	}
	fake.readProfileReturnsOnCall[i] = struct {
		result1 client.Object
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) RemoveAll(arg1 string) error {
	fake.removeAllMutex.Lock()
	ret, specificReturn := fake.removeAllReturnsOnCall[len(fake.removeAllArgsForCall)]
	fake.removeAllArgsForCall = append(fake.removeAllArgsForCall, FakeImplRemoveAllArgs{arg1})
	stub := fake.RemoveAllStub
	fakeReturns := fake.removeAllReturns
	fake.recordInvocation("RemoveAll", []interface{}{arg1})
	fake.removeAllMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) RemoveAllCallCount() int {
	fake.removeAllMutex.RLock()
	defer fake.removeAllMutex.RUnlock()
	return len(fake.removeAllArgsForCall)
}

func (fake *FakeImpl) RemoveAllCalls(stub func(string) error) {
	fake.removeAllMutex.Lock()
	defer fake.removeAllMutex.Unlock()
	fake.RemoveAllStub = stub
}

func (fake *FakeImpl) RemoveAllArgsForCall(i int) string {
	fake.removeAllMutex.RLock()
	defer fake.removeAllMutex.RUnlock()
	argsForCall := fake.removeAllArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) RemoveAllArgs() []FakeImplRemoveAllArgs {
	fake.removeAllMutex.RLock()
	defer fake.removeAllMutex.RUnlock()
	args := make([]FakeImplRemoveAllArgs, len(fake.removeAllArgsForCall))
	copy(args, fake.removeAllArgsForCall)
	return args
}

func (fake *FakeImpl) RemoveAllReturns(result1 error) {
	fake.removeAllMutex.Lock()
	defer fake.removeAllMutex.Unlock()
	fake.RemoveAllStub = nil
	fake.removeAllReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) RemoveAllReturnsOnCall(i int, result1 error) {
	fake.removeAllMutex.Lock()
	defer fake.removeAllMutex.Unlock()
	fake.RemoveAllStub = nil
	if fake.removeAllReturnsOnCall == nil {
		fake.removeAllReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeAllReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) RepositoryPush(arg1 context.Context, arg2 *remote.Repository, arg3 *v1.Descriptor, arg4 io.Reader) error {
	fake.repositoryPushMutex.Lock()
	ret, specificReturn := fake.repositoryPushReturnsOnCall[len(fake.repositoryPushArgsForCall)]
	fake.repositoryPushArgsForCall = append(fake.repositoryPushArgsForCall, FakeImplRepositoryPushArgs{arg1, arg2, arg3, arg4})
	stub := fake.RepositoryPushStub
	fakeReturns := fake.repositoryPushReturns
	fake.recordInvocation("RepositoryPush", []interface{}{arg1, arg2, arg3, arg4})
	fake.repositoryPushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) RepositoryPushCallCount() int {
	fake.repositoryPushMutex.RLock()
	defer fake.repositoryPushMutex.RUnlock()
	return len(fake.repositoryPushArgsForCall)
}

func (fake *FakeImpl) RepositoryPushCalls(stub func(context.Context, *remote.Repository, *v1.Descriptor, io.Reader) error) {
	fake.repositoryPushMutex.Lock()
	defer fake.repositoryPushMutex.Unlock()
	fake.RepositoryPushStub = stub
}

func (fake *FakeImpl) RepositoryPushArgsForCall(i int) (context.Context, *remote.Repository, *v1.Descriptor, io.Reader) {
	fake.repositoryPushMutex.RLock()
	defer fake.repositoryPushMutex.RUnlock()
	argsForCall := fake.repositoryPushArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeImpl) RepositoryPushArgs() []FakeImplRepositoryPushArgs {
	fake.repositoryPushMutex.RLock()
	defer fake.repositoryPushMutex.RUnlock()
	args := make([]FakeImplRepositoryPushArgs, len(fake.repositoryPushArgsForCall))
	copy(args, fake.repositoryPushArgsForCall)
	return args
}

func (fake *FakeImpl) RepositoryPushReturns(result1 error) {
	fake.repositoryPushMutex.Lock()
	defer fake.repositoryPushMutex.Unlock()
	fake.RepositoryPushStub = nil
	fake.repositoryPushReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) RepositoryPushReturnsOnCall(i int, result1 error) {
	fake.repositoryPushMutex.Lock()
	defer fake.repositoryPushMutex.Unlock()
	fake.RepositoryPushStub = nil
	if fake.repositoryPushReturnsOnCall == nil {
		fake.repositoryPushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.repositoryPushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) ResolveRepository(arg1 context.Context, arg2 *remote.Repository, arg3 string) (v1.Descriptor, error) {
	fake.resolveRepositoryMutex.Lock()
	ret, specificReturn := fake.resolveRepositoryReturnsOnCall[len(fake.resolveRepositoryArgsForCall)]
	fake.resolveRepositoryArgsForCall = append(fake.resolveRepositoryArgsForCall, FakeImplResolveRepositoryArgs{arg1, arg2, arg3})
	stub := fake.ResolveRepositoryStub
	fakeReturns := fake.resolveRepositoryReturns
	fake.recordInvocation("ResolveRepository", []interface{}{arg1, arg2, arg3})
	fake.resolveRepositoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) ResolveRepositoryCallCount() int {
	fake.resolveRepositoryMutex.RLock()
	defer fake.resolveRepositoryMutex.RUnlock()
	return len(fake.resolveRepositoryArgsForCall)
}

func (fake *FakeImpl) ResolveRepositoryCalls(stub func(context.Context, *remote.Repository, string) (v1.Descriptor, error)) {
	fake.resolveRepositoryMutex.Lock()
	defer fake.resolveRepositoryMutex.Unlock()
	fake.ResolveRepositoryStub = stub
}

func (fake *FakeImpl) ResolveRepositoryArgsForCall(i int) (context.Context, *remote.Repository, string) {
	fake.resolveRepositoryMutex.RLock()
	defer fake.resolveRepositoryMutex.RUnlock()
	argsForCall := fake.resolveRepositoryArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeImpl) ResolveRepositoryArgs() []FakeImplResolveRepositoryArgs {
	fake.resolveRepositoryMutex.RLock()
	defer fake.resolveRepositoryMutex.RUnlock()
	args := make([]FakeImplResolveRepositoryArgs, len(fake.resolveRepositoryArgsForCall))
	copy(args, fake.resolveRepositoryArgsForCall)
	return args
}

func (fake *FakeImpl) ResolveRepositoryReturns(result1 v1.Descriptor, result2 error) {
	fake.resolveRepositoryMutex.Lock()
	defer fake.resolveRepositoryMutex.Unlock()
	fake.ResolveRepositoryStub = nil
	fake.resolveRepositoryReturns = struct {
		result1 v1.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ResolveRepositoryReturnsOnCall(i int, result1 v1.Descriptor, result2 error) {
	fake.resolveRepositoryMutex.Lock()
	defer fake.resolveRepositoryMutex.Unlock()
	fake.ResolveRepositoryStub = nil
	if fake.resolveRepositoryReturnsOnCall == nil {
		fake.resolveRepositoryReturnsOnCall = make(map[int]struct {
			result1 v1.Descriptor
			result2 error
		})
	}
	fake.resolveRepositoryReturnsOnCall[i] = struct {
		result1 v1.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) SignBundle(arg1 context.Context, arg2 sign.Content, arg3 *sign.BundleOptions) (*v1a.Bundle, error) {
	fake.signBundleMutex.Lock()
	ret, specificReturn := fake.signBundleReturnsOnCall[len(fake.signBundleArgsForCall)]
	fake.signBundleArgsForCall = append(fake.signBundleArgsForCall, FakeImplSignBundleArgs{arg1, arg2, arg3})
	stub := fake.SignBundleStub
	fakeReturns := fake.signBundleReturns
	fake.recordInvocation("SignBundle", []interface{}{arg1, arg2, arg3})
	fake.signBundleMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) SignBundleCallCount() int {
	fake.signBundleMutex.RLock()
	defer fake.signBundleMutex.RUnlock()
	return len(fake.signBundleArgsForCall)
}

func (fake *FakeImpl) SignBundleCalls(stub func(context.Context, sign.Content, *sign.BundleOptions) (*v1a.Bundle, error)) {
	fake.signBundleMutex.Lock()
	defer fake.signBundleMutex.Unlock()
	fake.SignBundleStub = stub
}

func (fake *FakeImpl) SignBundleArgsForCall(i int) (context.Context, sign.Content, *sign.BundleOptions) {
	fake.signBundleMutex.RLock()
	defer fake.signBundleMutex.RUnlock()
	argsForCall := fake.signBundleArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeImpl) SignBundleArgs() []FakeImplSignBundleArgs {
	fake.signBundleMutex.RLock()
	defer fake.signBundleMutex.RUnlock()
	args := make([]FakeImplSignBundleArgs, len(fake.signBundleArgsForCall))
	copy(args, fake.signBundleArgsForCall)
	return args
}

func (fake *FakeImpl) SignBundleReturns(result1 *v1a.Bundle, result2 error) {
	fake.signBundleMutex.Lock()
	defer fake.signBundleMutex.Unlock()
	fake.SignBundleStub = nil
	fake.signBundleReturns = struct {
		result1 *v1a.Bundle
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) SignBundleReturnsOnCall(i int, result1 *v1a.Bundle, result2 error) {
	fake.signBundleMutex.Lock()
	defer fake.signBundleMutex.Unlock()
	fake.SignBundleStub = nil
	if fake.signBundleReturnsOnCall == nil {
		fake.signBundleReturnsOnCall = make(map[int]struct {
			result1 *v1a.Bundle
			result2 error
		})
	}
	fake.signBundleReturnsOnCall[i] = struct {
		result1 *v1a.Bundle
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) SignatureReferrers(arg1 context.Context, arg2 *remote.Repository, arg3 *v1.Descriptor) ([]v1.Descriptor, error) {
	fake.signatureReferrersMutex.Lock()
	ret, specificReturn := fake.signatureReferrersReturnsOnCall[len(fake.signatureReferrersArgsForCall)]
	fake.signatureReferrersArgsForCall = append(fake.signatureReferrersArgsForCall, FakeImplSignatureReferrersArgs{arg1, arg2, arg3})
	stub := fake.SignatureReferrersStub
	fakeReturns := fake.signatureReferrersReturns
	fake.recordInvocation("SignatureReferrers", []interface{}{arg1, arg2, arg3})
	fake.signatureReferrersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) SignatureReferrersCallCount() int {
	fake.signatureReferrersMutex.RLock()
	defer fake.signatureReferrersMutex.RUnlock()
	return len(fake.signatureReferrersArgsForCall)
}

func (fake *FakeImpl) SignatureReferrersCalls(stub func(context.Context, *remote.Repository, *v1.Descriptor) ([]v1.Descriptor, error)) {
	fake.signatureReferrersMutex.Lock()
	defer fake.signatureReferrersMutex.Unlock()
	fake.SignatureReferrersStub = stub
}

func (fake *FakeImpl) SignatureReferrersArgsForCall(i int) (context.Context, *remote.Repository, *v1.Descriptor) {
	fake.signatureReferrersMutex.RLock()
	defer fake.signatureReferrersMutex.RUnlock()
	argsForCall := fake.signatureReferrersArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeImpl) SignatureReferrersArgs() []FakeImplSignatureReferrersArgs {
	fake.signatureReferrersMutex.RLock()
	defer fake.signatureReferrersMutex.RUnlock()
	args := make([]FakeImplSignatureReferrersArgs, len(fake.signatureReferrersArgsForCall))
	copy(args, fake.signatureReferrersArgsForCall)
	return args
}

func (fake *FakeImpl) SignatureReferrersReturns(result1 []v1.Descriptor, result2 error) {
	fake.signatureReferrersMutex.Lock()
	defer fake.signatureReferrersMutex.Unlock()
	fake.SignatureReferrersStub = nil
	fake.signatureReferrersReturns = struct {
		result1 []v1.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) SignatureReferrersReturnsOnCall(i int, result1 []v1.Descriptor, result2 error) {
	fake.signatureReferrersMutex.Lock()
	defer fake.signatureReferrersMutex.Unlock()
	fake.SignatureReferrersStub = nil
	if fake.signatureReferrersReturnsOnCall == nil {
		fake.signatureReferrersReturnsOnCall = make(map[int]struct {
			result1 []v1.Descriptor
			result2 error
		})
	}
	fake.signatureReferrersReturnsOnCall[i] = struct {
		result1 []v1.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) SigningConfig(arg1 context.Context) (*root.SigningConfig, error) {
	fake.signingConfigMutex.Lock()
	ret, specificReturn := fake.signingConfigReturnsOnCall[len(fake.signingConfigArgsForCall)]
	fake.signingConfigArgsForCall = append(fake.signingConfigArgsForCall, FakeImplSigningConfigArgs{arg1})
	stub := fake.SigningConfigStub
	fakeReturns := fake.signingConfigReturns
	fake.recordInvocation("SigningConfig", []interface{}{arg1})
	fake.signingConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) SigningConfigCallCount() int {
	fake.signingConfigMutex.RLock()
	defer fake.signingConfigMutex.RUnlock()
	return len(fake.signingConfigArgsForCall)
}

func (fake *FakeImpl) SigningConfigCalls(stub func(context.Context) (*root.SigningConfig, error)) {
	fake.signingConfigMutex.Lock()
	defer fake.signingConfigMutex.Unlock()
	fake.SigningConfigStub = stub
}

func (fake *FakeImpl) SigningConfigArgsForCall(i int) context.Context {
	fake.signingConfigMutex.RLock()
	defer fake.signingConfigMutex.RUnlock()
	argsForCall := fake.signingConfigArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) SigningConfigArgs() []FakeImplSigningConfigArgs {
	fake.signingConfigMutex.RLock()
	defer fake.signingConfigMutex.RUnlock()
	args := make([]FakeImplSigningConfigArgs, len(fake.signingConfigArgsForCall))
	copy(args, fake.signingConfigArgsForCall)
	return args
}

func (fake *FakeImpl) SigningConfigReturns(result1 *root.SigningConfig, result2 error) {
	fake.signingConfigMutex.Lock()
	defer fake.signingConfigMutex.Unlock()
	fake.SigningConfigStub = nil
	fake.signingConfigReturns = struct {
		result1 *root.SigningConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) SigningConfigReturnsOnCall(i int, result1 *root.SigningConfig, result2 error) {
	fake.signingConfigMutex.Lock()
	defer fake.signingConfigMutex.Unlock()
	fake.SigningConfigStub = nil
	if fake.signingConfigReturnsOnCall == nil {
		fake.signingConfigReturnsOnCall = make(map[int]struct {
			result1 *root.SigningConfig
			result2 error
		})
	}
	fake.signingConfigReturnsOnCall[i] = struct {
		result1 *root.SigningConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) StoreAdd(arg1 context.Context, arg2 *file.Store, arg3 string, arg4 string, arg5 string) (v1.Descriptor, error) {
	fake.storeAddMutex.Lock()
	ret, specificReturn := fake.storeAddReturnsOnCall[len(fake.storeAddArgsForCall)]
	fake.storeAddArgsForCall = append(fake.storeAddArgsForCall, FakeImplStoreAddArgs{arg1, arg2, arg3, arg4, arg5})
	stub := fake.StoreAddStub
	fakeReturns := fake.storeAddReturns
	fake.recordInvocation("StoreAdd", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.storeAddMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) StoreAddCallCount() int {
	fake.storeAddMutex.RLock()
	defer fake.storeAddMutex.RUnlock()
	return len(fake.storeAddArgsForCall)
}

func (fake *FakeImpl) StoreAddCalls(stub func(context.Context, *file.Store, string, string, string) (v1.Descriptor, error)) {
	fake.storeAddMutex.Lock()
	defer fake.storeAddMutex.Unlock()
	fake.StoreAddStub = stub
}

func (fake *FakeImpl) StoreAddArgsForCall(i int) (context.Context, *file.Store, string, string, string) {
	fake.storeAddMutex.RLock()
	defer fake.storeAddMutex.RUnlock()
	argsForCall := fake.storeAddArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4, argsForCall.Arg5
}

func (fake *FakeImpl) StoreAddArgs() []FakeImplStoreAddArgs {
	fake.storeAddMutex.RLock()
	defer fake.storeAddMutex.RUnlock()
	args := make([]FakeImplStoreAddArgs, len(fake.storeAddArgsForCall))
	copy(args, fake.storeAddArgsForCall)
	return args
}

func (fake *FakeImpl) StoreAddReturns(result1 v1.Descriptor, result2 error) {
	fake.storeAddMutex.Lock()
	defer fake.storeAddMutex.Unlock()
	fake.StoreAddStub = nil
	fake.storeAddReturns = struct {
		result1 v1.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) StoreAddReturnsOnCall(i int, result1 v1.Descriptor, result2 error) {
	fake.storeAddMutex.Lock()
	defer fake.storeAddMutex.Unlock()
	fake.StoreAddStub = nil
	if fake.storeAddReturnsOnCall == nil {
		fake.storeAddReturnsOnCall = make(map[int]struct {
			result1 v1.Descriptor
			result2 error
		})
	}
	fake.storeAddReturnsOnCall[i] = struct {
		result1 v1.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) StoreFetch(arg1 context.Context, arg2 *file.Store, arg3 *v1.Descriptor) (io.ReadCloser, error) {
	fake.storeFetchMutex.Lock()
	ret, specificReturn := fake.storeFetchReturnsOnCall[len(fake.storeFetchArgsForCall)]
	fake.storeFetchArgsForCall = append(fake.storeFetchArgsForCall, FakeImplStoreFetchArgs{arg1, arg2, arg3})
	stub := fake.StoreFetchStub
	fakeReturns := fake.storeFetchReturns
	fake.recordInvocation("StoreFetch", []interface{}{arg1, arg2, arg3})
	fake.storeFetchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) StoreFetchCallCount() int {
	fake.storeFetchMutex.RLock()
	defer fake.storeFetchMutex.RUnlock()
	return len(fake.storeFetchArgsForCall)
}

func (fake *FakeImpl) StoreFetchCalls(stub func(context.Context, *file.Store, *v1.Descriptor) (io.ReadCloser, error)) {
	fake.storeFetchMutex.Lock()
	defer fake.storeFetchMutex.Unlock()
	fake.StoreFetchStub = stub
}

func (fake *FakeImpl) StoreFetchArgsForCall(i int) (context.Context, *file.Store, *v1.Descriptor) {
	fake.storeFetchMutex.RLock()
	defer fake.storeFetchMutex.RUnlock()
	argsForCall := fake.storeFetchArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeImpl) StoreFetchArgs() []FakeImplStoreFetchArgs {
	fake.storeFetchMutex.RLock()
	defer fake.storeFetchMutex.RUnlock()
	args := make([]FakeImplStoreFetchArgs, len(fake.storeFetchArgsForCall))
	copy(args, fake.storeFetchArgsForCall)
	return args
}

func (fake *FakeImpl) StoreFetchReturns(result1 io.ReadCloser, result2 error) {
	fake.storeFetchMutex.Lock()
	defer fake.storeFetchMutex.Unlock()
	fake.StoreFetchStub = nil
	fake.storeFetchReturns = struct {
		result1 io.ReadCloser
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) StoreFetchReturnsOnCall(i int, result1 io.ReadCloser, result2 error) {
	fake.storeFetchMutex.Lock()
	defer fake.storeFetchMutex.Unlock()
	fake.StoreFetchStub = nil
	if fake.storeFetchReturnsOnCall == nil {
		fake.storeFetchReturnsOnCall = make(map[int]struct {
			result1 io.ReadCloser
			result2 error
		})
	}
	fake.storeFetchReturnsOnCall[i] = struct {
		result1 io.ReadCloser
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) StorePush(arg1 context.Context, arg2 *file.Store, arg3 *v1.Descriptor, arg4 io.Reader) error {
	fake.storePushMutex.Lock()
	ret, specificReturn := fake.storePushReturnsOnCall[len(fake.storePushArgsForCall)]
	fake.storePushArgsForCall = append(fake.storePushArgsForCall, FakeImplStorePushArgs{arg1, arg2, arg3, arg4})
	stub := fake.StorePushStub
	fakeReturns := fake.storePushReturns
	fake.recordInvocation("StorePush", []interface{}{arg1, arg2, arg3, arg4})
	fake.storePushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) StorePushCallCount() int {
	fake.storePushMutex.RLock()
	defer fake.storePushMutex.RUnlock()
	return len(fake.storePushArgsForCall)
}

func (fake *FakeImpl) StorePushCalls(stub func(context.Context, *file.Store, *v1.Descriptor, io.Reader) error) {
	fake.storePushMutex.Lock()
	defer fake.storePushMutex.Unlock()
	fake.StorePushStub = stub
}

func (fake *FakeImpl) StorePushArgsForCall(i int) (context.Context, *file.Store, *v1.Descriptor, io.Reader) {
	fake.storePushMutex.RLock()
	defer fake.storePushMutex.RUnlock()
	argsForCall := fake.storePushArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeImpl) StorePushArgs() []FakeImplStorePushArgs {
	fake.storePushMutex.RLock()
	defer fake.storePushMutex.RUnlock()
	args := make([]FakeImplStorePushArgs, len(fake.storePushArgsForCall))
	copy(args, fake.storePushArgsForCall)
	return args
}

func (fake *FakeImpl) StorePushReturns(result1 error) {
	fake.storePushMutex.Lock()
	defer fake.storePushMutex.Unlock()
	fake.StorePushStub = nil
	fake.storePushReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) StorePushReturnsOnCall(i int, result1 error) {
	fake.storePushMutex.Lock()
	defer fake.storePushMutex.Unlock()
	fake.StorePushStub = nil
	if fake.storePushReturnsOnCall == nil {
		fake.storePushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.storePushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) StoreTag(arg1 context.Context, arg2 *file.Store, arg3 *v1.Descriptor, arg4 string) error {
	fake.storeTagMutex.Lock()
	ret, specificReturn := fake.storeTagReturnsOnCall[len(fake.storeTagArgsForCall)]
	fake.storeTagArgsForCall = append(fake.storeTagArgsForCall, FakeImplStoreTagArgs{arg1, arg2, arg3, arg4})
	stub := fake.StoreTagStub
	fakeReturns := fake.storeTagReturns
	fake.recordInvocation("StoreTag", []interface{}{arg1, arg2, arg3, arg4})
	fake.storeTagMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) StoreTagCallCount() int {
	fake.storeTagMutex.RLock()
	defer fake.storeTagMutex.RUnlock()
	return len(fake.storeTagArgsForCall)
}

func (fake *FakeImpl) StoreTagCalls(stub func(context.Context, *file.Store, *v1.Descriptor, string) error) {
	fake.storeTagMutex.Lock()
	defer fake.storeTagMutex.Unlock()
	fake.StoreTagStub = stub
}

func (fake *FakeImpl) StoreTagArgsForCall(i int) (context.Context, *file.Store, *v1.Descriptor, string) {
	fake.storeTagMutex.RLock()
	defer fake.storeTagMutex.RUnlock()
	argsForCall := fake.storeTagArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeImpl) StoreTagArgs() []FakeImplStoreTagArgs {
	fake.storeTagMutex.RLock()
	defer fake.storeTagMutex.RUnlock()
	args := make([]FakeImplStoreTagArgs, len(fake.storeTagArgsForCall))
	copy(args, fake.storeTagArgsForCall)
	return args
}

func (fake *FakeImpl) StoreTagReturns(result1 error) {
	fake.storeTagMutex.Lock()
	defer fake.storeTagMutex.Unlock()
	fake.StoreTagStub = nil
	fake.storeTagReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) StoreTagReturnsOnCall(i int, result1 error) {
	fake.storeTagMutex.Lock()
	defer fake.storeTagMutex.Unlock()
	fake.StoreTagStub = nil
	if fake.storeTagReturnsOnCall == nil {
		fake.storeTagReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.storeTagReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) TrustedMaterial(arg1 context.Context, arg2 string, arg3 bool) (root.TrustedMaterial, error) {
	fake.trustedMaterialMutex.Lock()
	ret, specificReturn := fake.trustedMaterialReturnsOnCall[len(fake.trustedMaterialArgsForCall)]
	fake.trustedMaterialArgsForCall = append(fake.trustedMaterialArgsForCall, FakeImplTrustedMaterialArgs{arg1, arg2, arg3})
	stub := fake.TrustedMaterialStub
	fakeReturns := fake.trustedMaterialReturns
	fake.recordInvocation("TrustedMaterial", []interface{}{arg1, arg2, arg3})
	fake.trustedMaterialMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) TrustedMaterialCallCount() int {
	fake.trustedMaterialMutex.RLock()
	defer fake.trustedMaterialMutex.RUnlock()
	return len(fake.trustedMaterialArgsForCall)
}

func (fake *FakeImpl) TrustedMaterialCalls(stub func(context.Context, string, bool) (root.TrustedMaterial, error)) {
	fake.trustedMaterialMutex.Lock()
	defer fake.trustedMaterialMutex.Unlock()
	fake.TrustedMaterialStub = stub
}

func (fake *FakeImpl) TrustedMaterialArgsForCall(i int) (context.Context, string, bool) {
	fake.trustedMaterialMutex.RLock()
	defer fake.trustedMaterialMutex.RUnlock()
	argsForCall := fake.trustedMaterialArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeImpl) TrustedMaterialArgs() []FakeImplTrustedMaterialArgs {
	fake.trustedMaterialMutex.RLock()
	defer fake.trustedMaterialMutex.RUnlock()
	args := make([]FakeImplTrustedMaterialArgs, len(fake.trustedMaterialArgsForCall))
	copy(args, fake.trustedMaterialArgsForCall)
	return args
}

func (fake *FakeImpl) TrustedMaterialReturns(result1 root.TrustedMaterial, result2 error) {
	fake.trustedMaterialMutex.Lock()
	defer fake.trustedMaterialMutex.Unlock()
	fake.TrustedMaterialStub = nil
	fake.trustedMaterialReturns = struct {
		result1 root.TrustedMaterial
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) TrustedMaterialReturnsOnCall(i int, result1 root.TrustedMaterial, result2 error) {
	fake.trustedMaterialMutex.Lock()
	defer fake.trustedMaterialMutex.Unlock()
	fake.TrustedMaterialStub = nil
	if fake.trustedMaterialReturnsOnCall == nil {
		fake.trustedMaterialReturnsOnCall = make(map[int]struct {
			result1 root.TrustedMaterial
			result2 error
		})
	}
	fake.trustedMaterialReturnsOnCall[i] = struct {
		result1 root.TrustedMaterial
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) VerifyEntity(arg1 verify.SignedEntity, arg2 root.TrustedMaterial, arg3 []verify.VerifierOption, arg4 verify.ArtifactPolicyOption, arg5 *verify.CertificateIdentity) error {
	var arg3Copy []verify.VerifierOption
	if arg3 != nil {
		arg3Copy = make([]verify.VerifierOption, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.verifyEntityMutex.Lock()
	ret, specificReturn := fake.verifyEntityReturnsOnCall[len(fake.verifyEntityArgsForCall)]
	fake.verifyEntityArgsForCall = append(fake.verifyEntityArgsForCall, FakeImplVerifyEntityArgs{arg1, arg2, arg3Copy, arg4, arg5})
	stub := fake.VerifyEntityStub
	fakeReturns := fake.verifyEntityReturns
	fake.recordInvocation("VerifyEntity", []interface{}{arg1, arg2, arg3Copy, arg4, arg5})
	fake.verifyEntityMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) VerifyEntityCallCount() int {
	fake.verifyEntityMutex.RLock()
	defer fake.verifyEntityMutex.RUnlock()
	return len(fake.verifyEntityArgsForCall)
}

func (fake *FakeImpl) VerifyEntityCalls(stub func(verify.SignedEntity, root.TrustedMaterial, []verify.VerifierOption, verify.ArtifactPolicyOption, *verify.CertificateIdentity) error) {
	fake.verifyEntityMutex.Lock()
	defer fake.verifyEntityMutex.Unlock()
	fake.VerifyEntityStub = stub
}

func (fake *FakeImpl) VerifyEntityArgsForCall(i int) (verify.SignedEntity, root.TrustedMaterial, []verify.VerifierOption, verify.ArtifactPolicyOption, *verify.CertificateIdentity) {
	fake.verifyEntityMutex.RLock()
	defer fake.verifyEntityMutex.RUnlock()
	argsForCall := fake.verifyEntityArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4, argsForCall.Arg5
}

func (fake *FakeImpl) VerifyEntityArgs() []FakeImplVerifyEntityArgs {
	fake.verifyEntityMutex.RLock()
	defer fake.verifyEntityMutex.RUnlock()
	args := make([]FakeImplVerifyEntityArgs, len(fake.verifyEntityArgsForCall))
	copy(args, fake.verifyEntityArgsForCall)
	return args
}

func (fake *FakeImpl) VerifyEntityReturns(result1 error) {
	fake.verifyEntityMutex.Lock()
	defer fake.verifyEntityMutex.Unlock()
	fake.VerifyEntityStub = nil
	fake.verifyEntityReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) VerifyEntityReturnsOnCall(i int, result1 error) {
	fake.verifyEntityMutex.Lock()
	defer fake.verifyEntityMutex.Unlock()
	fake.VerifyEntityStub = nil
	if fake.verifyEntityReturnsOnCall == nil {
		fake.verifyEntityReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyEntityReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeImpl) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeImpl) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
