apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SeccompProfile
metadata:
  labels:
    app: security-profiles-operator
  name: nginx-1.19.1
  namespace: security-profiles-operator
spec:
  architectures:
  - SCMP_ARCH_X86_64
  - SCMP_ARCH_X86
  - SCMP_ARCH_X32
  defaultAction: SCMP_ACT_ERRNO
  syscalls:
  - action: SCMP_ACT_ALLOW
    names:
    - accept4
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - chown
    - clone
    - close
    - connect
    - dup2
    - epoll_create
    - epoll_ctl
    - epoll_pwait
    - epoll_wait
    - eventfd2
    - execve
    - exit
    - exit_group
    - faccessat
    - fadvise64
    - fchdir
    - fchown
    - fcntl
    - fgetxattr
    - fsetxattr
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents
    - getdents64
    - getegid
    - geteuid
    - getgid
    - getpid
    - getppid
    - getrlimit
    - getuid
    - ioctl
    - io_setup
    - listen
    - lseek
    - mkdir
    - mmap
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - open
    - openat
    - pipe
    - prctl
    - pread64
    - prlimit64
    - pwrite64
    - read
    - recvfrom
    - recvmsg
    - rename
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - rt_sigsuspend
    - sched_getaffinity
    - seccomp
    - sendfile
    - sendmsg
    - setgid
    - setgroups
    - setitimer
    - set_robust_list
    - setsockopt
    - set_tid_address
    - setuid
    - sigaltstack
    - socket
    - socketpair
    - stat
    - statfs
    - sysinfo
    - umask
    - uname
    - unlink
    - utimensat
    - wait4
    - write
    - writev
  targetWorkload: default-profiles
