name: helm-chart-package
on:
  pull_request:
  release:
    types: [published]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  helm-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
        with:
          version: v3.8.1
      - run: mkdir -p build
      - id: package
        run: |
          helm_output="$(helm package -d build deploy/helm)"
          tgz_path="${helm_output##*saved it to: }"
          echo "helm chart tgz path: '${tgz_path}'"
          [ ! -f "${tgz_path}" ] && echo "failed to find helm chart from 'helm package' stdout" && exit 1
          echo "helm_tgz_path=${tgz_path}" >> $GITHUB_OUTPUT
          echo "helm_tgz_name=${tgz_path##*/}" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ steps.package.outputs.helm_tgz_name}}
          path: ${{ steps.package.outputs.helm_tgz_path}}
          if-no-files-found: error
      - uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.package.outputs.helm_tgz_path}}
