name: olm
on:
  push:
    branches:
      - main
  pull_request:
env:
  KIND_IMG_TAG: v1.34.0
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  main:
    name: tests
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Download binaries
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/build
        echo "${GITHUB_WORKSPACE}/build" >> ${GITHUB_PATH}
        make operator-sdk opm

    - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: ./go.mod

    - name: Install dependencies
      run: |
        sudo ./hack/install-packages
        ./hack/install-crun

    - name: Create and verify bundle
      run: |
        make verify-bundle

    - name: Create and set up K8s KinD Cluster
      run: |
        ./hack/kind-with-registry.sh

    - name: Run the tests
      run: ./hack/ci/e2e-olm.sh
      env:
        XDG_RUNTIME_DIR: ''
