name: test
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  analyze:
    permissions:

      # write security-events is required by all codeql-action workflows
      security-events: write

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: github/codeql-action/init@c793b717bc78562f491db7b0e93a3a178b099162 # v4.32.5
        with:
          languages: go
      - uses: github/codeql-action/autobuild@c793b717bc78562f491db7b0e93a3a178b099162 # v4.32.5
      - uses: github/codeql-action/analyze@c793b717bc78562f491db7b0e93a3a178b099162 # v4.32.5

  coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: ./go.mod
      - name: Install dependencies
        run: sudo hack/install-packages
      - run: make test-unit
      - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          files: build/coverage.out
          flags: unittests
          verbose: true

  image:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: hack/install-crun
      - run: make image
        env:
          XDG_RUNTIME_DIR: ''
      - run: podman save -o image.tar security-profiles-operator
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: image
          path: image.tar

  e2e-fedora:
    needs: image
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    env:
      RUN: ./hack/ci/run-fedora.sh
    steps:
      - name: Set up vagrant
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox
      - name: Unload KVM modules
        run: |
          sudo modprobe -r kvm_amd kvm_intel kvm || true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: image
          path: .
      - name: Boot Virtual Machine
        run: make vagrant-up-fedora
      - name: Show environment information
        run: |
          $RUN kubectl wait --for=condition=ready --timeout=60s nodes --all
          $RUN kubectl get nodes -o wide
      - name: Set up git config
        run: |
          $RUN git config --global --add safe.directory /vagrant
      - name: Run E2E tests
        run: $RUN hack/ci/e2e-fedora.sh
      - name: Run Flaky E2E tests
        continue-on-error: true
        run: |
          $RUN "echo \"export E2E_TEST_FLAKY_TESTS_ONLY=true\" >> /vagrant/hack/ci/env.sh"
          $RUN hack/ci/e2e-fedora.sh

  e2e-ubuntu:
    needs: image
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    env:
      RUN: ./hack/ci/run-ubuntu.sh
    steps:
      - name: Set up vagrant
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox
      - name: Unload KVM modules
        run: |
          sudo modprobe -r kvm_amd kvm_intel kvm || true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: image
          path: .
      - name: Boot Virtual Machine
        run: make vagrant-up-ubuntu
      - name: Show environment information
        run: |
          $RUN kubectl wait --for=condition=ready --timeout=60s nodes --all
          $RUN kubectl get nodes -o wide
      - name: Set up git config
        run: |
          $RUN git config --global --add safe.directory /vagrant
      - name: Run E2E tests
        run: $RUN hack/ci/e2e-ubuntu.sh
      - name: Run Flaky E2E tests
        continue-on-error: true
        run: |
          $RUN "echo \"export E2E_TEST_FLAKY_TESTS_ONLY=true\" >> /vagrant/hack/ci/env.sh"
          $RUN hack/ci/e2e-ubuntu.sh

  e2e-flatcar:
    needs: image
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    env:
      RUN: ./hack/ci/run-flatcar.sh
    steps:
      - name: Set up vagrant
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox
      - name: Unload KVM modules
        run: |
          sudo modprobe -r kvm_amd kvm_intel kvm || true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Vagrant box version
        id: vagrant-box
        run: |
          echo "version=$(curl -s  https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_vagrant.json | jq '.versions[0].version' | tr -d '".')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Upgrade vagrant box
        run: |
          ln -sf hack/ci/Vagrantfile-flatcar Vagrantfile
          vagrant box update
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: image
          path: .
      - name: Boot Virtual Machine
        run: make vagrant-up-flatcar
      - name: Show environment information
        run: |
          $RUN kubectl wait --for=condition=ready --timeout=600s node localhost
          $RUN kubectl get nodes -o wide
      - name: Run E2E tests
        run: $RUN hack/ci/e2e-flatcar-dev-container.sh
      - name: Run Flaky E2E tests
        continue-on-error: true
        run: |
          $RUN "echo \"export E2E_TEST_FLAKY_TESTS_ONLY=true\" >> /vagrant/hack/ci/env-flatcar.sh"
          $RUN hack/ci/e2e-flatcar-dev-container.sh

  e2e-spoc:
    needs: image
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    env:
      RUN: ./hack/ci/run-debian.sh
    steps:
      - name: Set up vagrant
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox
      - name: Unload KVM modules
        run: |
          sudo modprobe -r kvm_amd kvm_intel kvm || true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: image
          path: .
      - name: Boot Virtual Machine
        run: make vagrant-up-debian
      - name: Show environment information
        run: |
          $RUN kubectl wait --for=condition=ready --timeout=60s nodes --all
          $RUN kubectl get nodes -o wide
      - name: Set up git config
        run: |
          $RUN git config --global --add safe.directory /vagrant
      - name: Run spoc E2E tests
        run: $RUN hack/ci/e2e-spoc.sh

  e2e-seccomp-profile:
    needs: image
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    env:
      RUN: ./hack/ci/run-debian.sh
    steps:
      - name: Set up vagrant
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox
      - name: Unload KVM modules
        run: |
          sudo modprobe -r kvm_amd kvm_intel kvm || true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: image
          path: .
      - name: Boot Virtual Machine
        run: make vagrant-up-debian
      - name: Show environment information
        run: |
          $RUN kubectl wait --for=condition=ready --timeout=60s nodes --all
          $RUN kubectl get nodes -o wide
      - name: Set up git config
        run: |
          $RUN git config --global --add safe.directory /vagrant
      - name: Run E2E test to record seccomp profile
        run: $RUN hack/ci/e2e-seccomp.sh

  e2e-apparmor-profile:
    needs: image
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    env:
      RUN: ./hack/ci/run-debian.sh
    steps:
      - name: Set up vagrant
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox
      - name: Unload KVM modules
        run: |
          sudo modprobe -r kvm_amd kvm_intel kvm || true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: image
          path: .
      - name: Boot Virtual Machine
        run: make vagrant-up-debian
      - name: Show environment information
        run: |
          $RUN kubectl wait --for=condition=ready --timeout=60s nodes --all
          $RUN kubectl get nodes -o wide
      - name: Set up git config
        run: |
          $RUN git config --global --add safe.directory /vagrant
      - name: Run E2E test to record apparmor profile
        run: $RUN hack/ci/e2e-apparmor.sh

  typos:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: crate-ci/typos@631208b7aac2daa8b707f55e7331f9112b0e062d # v1.44.0
        with:
          config: .typos.toml
