apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: seccomp-operator
  namespace: seccomp-operator
spec:
  template:
    spec:
      containers:
        - name: seccomp-operator
          env:
            - name: RESTRICT_TO_NAMESPACE
              value: NS_REPLACE
