apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-profiles-operator
  namespace: security-profiles-operator
spec:
  template:
    spec:
      containers:
        - name: security-profiles-operator
          env:
            - name: RESTRICT_TO_NAMESPACE
              value: NS_REPLACE
